### ISSUE TITLE
Tokio: Method arguments for servers

### ISSUE THREAD

**Issue by manuels** [diwic/dbus-rs#102]
I have a problem figuring out how to implement a tokio dbus server with method arguments.

The example states `f.amethod("Hello", (), move |m| { ... }` and apparently the `()` token is the argument list, right?
The documentation states

```
fn amethod<H, R, T>(
    &self, 
    t: T, 
    data: D::Method, 
    handler: H
) -> Method<MTFn<ATree<D>>, ATree<D>> where
    H: 'static + Fn(&MethodInfo<MTFn<ATree<D>>, ATree<D>>) -> R,
    T: Into<Member<'static>>,
    R: 'static + IntoFuture<Item = Vec<Message>, Error = MethodErr
```
and
```
type Method: Debug + Default
```

Still, I have no idea, how to add a function to the interface that has arguments...
A little help here would be appreciated!

**Comment by diwic** [comment]
Hmm, it seems like you are confusing `dbus::tree::Method` and `dbus::tree::DataType::Method`?

The `()`, which refers to `dbus::tree::DataType::Method` is not an argument list. It's some extra data you can store in-tree if you wish. You can probably ignore it for now.

Arguments are added like this:

    f.amethod( /*... */)
        .inarg::<i32,_>("foo")
        .inarg::<bool,_>("bar")
        .outarg::<&str,_>("baz")

In the example above, the method takes two arguments (foo and bar) and returns one output argument (baz).
