### ISSUE TITLE
Publish dbus-codegen on crates.io

### ISSUE THREAD

**Issue by tmccombs** [diwic/dbus-rs#104]
Are there any plans to publish dbus-codegen to crates.io?

**Comment by diwic** [comment]
Sure, why not? Have you used it and found it useful / ready enough to go to crates.io?

**Comment by Mange** [comment]
I wanted to test it but I'm having problems.

I checked out this repo and `cargo install`ed the codegen, but the code that is generated is using types that are not part of the published crate (`SignalArgs`).

The repo does not have any Git tags or branches that correspond to the different released versions so I do not know which revision to check out when installing the codegen to get a matching version.

How should I proceed here? :-)

**Comment by diwic** [comment]
@Mange The quick answer is that git head will work fine (i e, depend on the git head version of the dbus crate). The other answer is that I realize this is far from ideal and I now have to decide whether to revert a tiny breaking change and release `0.5.5`, or go `0.6.0` and if so if I want to break more stuff while I'm at it...

**Comment by Mange** [comment]
I tried HEAD and want you to know that the generated code did wonders. The
new APIs really helped clean up everything in my client.

I look forward to the next release. ♥️

**Comment by diwic** [comment]
@Mange @tmccombs 
Ok, so I've released a new version of the dbus crate now. And with that goes the initial release of dbus-codegen on crates.io. Enjoy!

**Comment by diwic** [comment]
I wen't for the "break more stuff while I'm at it" approach and did `0.6.0`. Hopefully the breaking changes should be very easy to follow along with, if they hit you at all.
