### ISSUE TITLE
`codegen`d objects are not introspectable

### ISSUE THREAD

**Issue by jonnymatts** [diwic/dbus-rs#105]
I'd like to use D-Feet to debug my dbus service, but it requires that services be introspectable.

At the moment, my workaround is to copy-paste all required interfaces into one xml file, that I use for code generation and also `include_str!` in my implementation of `org.freedesktop.DBus.Introspectable`. 

I wonder how difficult it would be to automatically implement `Introspectable` for all services, either by including the xml that was used to generate them, or by regenerating it from other metadata.

**Comment by diwic** [comment]
If you are using the `tree` module, just call `introspectable()` on the object paths you want to allow introspection on.

**Comment by albx79** [comment]
My bad for not reading the docs! 

Indeed, calling `introspectable()` does the trick. Perhaps it's worth adding it to the codegen examples, as it's quite easy to get lost in the code and forget how the API works.

**Comment by diwic** [comment]
Ok, feel free to submit a PR for better docs - as you probably know better than I do where they should have been to make it easier for you.
