### ISSUE TITLE
Signature::new() should return error that converts into a MethodErr

### ISSUE THREAD

**Issue by agrover** [diwic/dbus-rs#109]
Part of implementing methods is making MessageItemArrays, which need a Signature. Signature returns an error type (String), which does not convert to MethodErr. If it did, converting to use the new MessageItemArray API would be made easier. The same may also be true for `ArrayError` type, returned from `MessageItemArray::new()`.

cc @mulkieran

**Comment by diwic** [comment]
That can certainly be done quite easily, but is there a reason you're using `MessageItem` instead of the newer `Arg` or `RefArg` interface?

**Comment by diwic** [comment]
Also, instead of using `Signature::new` you can use `Signature::make` which cannot fail and always return valid signatures from Rust types. As a bonus, one more thing that Rust checks for you at compile time.

**Comment by agrover** [comment]
> That can certainly be done quite easily, but is there a reason you're using MessageItem instead of the newer Arg or RefArg interface?

inertia? 😃 I'll give both your suggestions a try, thanks!

**Comment by agrover** [comment]
wow, yeah, that's a lot easier. Thanks again.
