### ISSUE TITLE
Make Tree and subcomponents iterable

### ISSUE THREAD

**Issue by agrover** [diwic/dbus-rs#110]
We have a use case where we'd like to remove some secondary ObjectPaths when we remove a given main ObjectPath. (The secondary ObjectPaths expose an Interface with a "parent" property with a Path pointing to Main.)

We have a [proposed PR](https://github.com/stratis-storage/stratisd/pull/628) that tracks this relationship independently from the Tree, but if it were possible to iterate the tree for objectpaths, then iterate interfaces, then iterate properties of an interface (methods and signals too for completeness), then we could rely on the Tree to tell us which secondary ObjectPaths to remove. This would be better than the alternatives, such as the aforementioned independent tracking, as well as using GetManagedObjects to query ourselves (?!) for this info.

It looks like there already are internal methods for doing this, such as `Tree::children()` that could just be made public, or it look straightforward to add at the struct ObjectPath and Interface levels to iterate their collections.

cc @mulkieran

**Comment by diwic** [comment]
There's no reason that this does not exist, just that you're the first one to ask for it. I've added a commit (https://github.com/diwic/dbus-rs/commit/1eb5f813b8d1fd2d3df0602e1ba16080a64078ef) that should resolve this issue, give it a try and reopen this issue if it does not.

**Comment by agrover** [comment]
It works great! Thanks!

**Comment by agrover** [comment]
@diwic new version soon? 😺

**Comment by diwic** [comment]
@agrover Are you trying to bribe me with a cat emoji? :-)

No worries, 0.6.1 released just now. I've just been busy as I need to prioritize paid work over spare time projects like this one.
