### ISSUE TITLE
Connecting to a non-system/session bus

### ISSUE THREAD

**Issue by ammgws** [diwic/dbus-rs#112]
Is it correct that `dbus-rs` currently does not support connections to non-system/session buses, such as the sockets used by `ibus`?

**Comment by diwic** [comment]
So does `ibus` have a built-in server that speaks D-Bus protocol? Could you check if the just added commit has what you need?

**Comment by ammgws** [comment]
Cheers! That looks just like what I was asking about. I haven't found time to test it yet though.

And yes, `ibus`  [starts](https://github.com/ibus/ibus/blob/9937a0e4501ccf0cfd238ce7c97733c3099db3f7/bus/server.c#L151) it's own server

**Comment by ammgws** [comment]
Sorry for the long delay. I finally found some time and can confirm that the new method is working fine.

Cheers!
