### ISSUE TITLE
How to get the value of a Variant of an array of bytes?

### ISSUE THREAD

**Issue by LinkTed** [diwic/dbus-rs#114]
Hi, i want to write a server over dbus and one of the method has a parameter which is a Variant  of an array of bytes:
```rust
...
let input: Variant<Vec<u8>> = m.msg.read1()?;
println!("Print input: {:?}", input);
...
```
The Variant was printed correctly, for example:
```
...
Print input: Variant([17, 34])
...
```
How can i extract the vector?
I tried with the `as_iter()` and with `as_any()`.

**Comment by Mange** [comment]
From what I can tell from the docs, [the `read1` method](https://docs.rs/dbus/0.6.1/dbus/struct.Message.html#method.read1) should work on any type that implements the `Arg` and `Get` traits. The [`Arg` trait is implemented for `Vec<T: Arg>`](https://docs.rs/dbus/0.6.1/dbus/arg/trait.Arg.html#impl-Arg-30) already and [`Get` is implemented for `Vec<T: Arg + Get>`](https://docs.rs/dbus/0.6.1/dbus/arg/trait.Get.html#impl-Get%3C'a%3E-30) too. Both are implemented for `u8`.

So shouldn't this work?

```rust
let input: Vec<u8> = m.msg.read1()?;
println!("Print input: {:?}", input);
```

I might be misreading the docs, though.

**Comment by LinkTed** [comment]
This didn't work:
```rust
let input: Vec<u8> = m.msg.read1()?;
println!("Print input: {:?}", input);
```
I get the following error:
```
('g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.Failed: D-Bus '
 'argument type mismatch at position 1: expected Array/Dict, found Variant (0)')
```

**Comment by diwic** [comment]
The field inside `Variant` is public so you can just do `input.0` to get the `Vec` out. Like this:

    let input: Variant<Vec<u8>> = m.msg.read1()?;
    let input = input.0;

I think this oneliner should work too:

    let input = m.msg.read1::<Variant<Vec<u8>>>()?.0;

**Comment by LinkTed** [comment]
Thank you very much!
