### ISSUE TITLE
Add object path to the same tree at Runtime

### ISSUE THREAD

**Issue by LinkTed** [diwic/dbus-rs#115]
Hi it is me again,
it is possible to add a object path to the same tree at runtime?
My problem is that a dbus method create a new object path and I want to insert in the same tree, because the new object path have to access the data of the old object path(which created the new object path).
It can be done if it is possible to make the MethodInfo in the call handler mutable.
For example:
```rust 
factory.method("Method", (), move |m | { // if it is possible to make m mutable
...        
}
...
```

English is not my mother tongue: I hope you understand what i mean.

**Comment by diwic** [comment]
No, you don't get a mutable tree inside a method handler. (This would allow you to delete whatever method you're currently calling, which would be unsound.) 

I should probably write an example for this as it is slightly tricky. You need to write a loop like:

     let mut new_path = None;
     factory.method("Method", (), |m| { new_path = Some( /* new path */); })
     /* ... */
     loop {
        if let Some(p) = new_path.take() { tree.add(p); }
        if let Some(msg) = connection.incoming(1000).next() {
            let r = tree.handle(msg);
            /* And send msgs in r */
        }
     }

**Comment by LinkTed** [comment]
Yes, it works. :)
THANK YOU VERY MUCH.
