### ISSUE TITLE
dbus-rs-master (libdbus-sys) - build failed [HELP WANTED]

### ISSUE THREAD

**Issue by chip5441** [diwic/dbus-rs#118]
C:\devtools\rust-pkgs\dbus-rs-master>cargo build
   Compiling strsim v0.6.0
   Compiling vec_map v0.8.0
   Compiling ansi_term v0.10.2
   Compiling winapi v0.3.4
   Compiling error-chain v0.10.0
   Compiling lazycell v0.6.0
   Compiling slab v0.3.0
   Compiling pkg-config v0.3.9
   Compiling slab v0.4.0
   Compiling bitflags v0.7.0
   Compiling unicode-width v0.1.4
   Compiling winapi-build v0.1.1
   Compiling winapi v0.2.8
   Compiling libc v0.2.36
   Compiling cfg-if v0.1.2
   Compiling futures v0.1.17
   Compiling toml v0.2.1
   Compiling scoped-tls v0.1.0
   Compiling byteorder v1.2.1
   Compiling bitflags v1.0.1
   Compiling xml-rs v0.3.6
   Compiling textwrap v0.9.0
   Compiling kernel32-sys v0.2.2
   Compiling ws2_32-sys v0.2.1
   Compiling log v0.4.1
   Compiling log v0.3.9
   Compiling metadeps v1.1.2
   Compiling libdbus-sys v0.1.2 (file:///C:/devtools/rust-pkgs/dbus-rs-master/libdbus-sys)
error: failed to run custom build command for `libdbus-sys v0.1.2 (file:///C:/devtools/rust-pkgs/dbus-rs-master/libdbus-sys)`
process didn't exit successfully: `C:\devtools\rust-pkgs\dbus-rs-master\target\debug\build\libdbus-sys-713ec40ddb09088e\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unknown Error!', src\libcore\option.rs:891:5
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:91
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:383
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:397
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   4: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   8: core::option::expect_failed
             at C:\projects\rust\src\libcore\option.rs:891
   9: core::option::Option<std::collections::hash::map::HashMap<alloc::string::String, pkg_config::Library, std::collections::hash::map::RandomState>>::expect<std::collections::hash::map::HashMap<alloc::string::String, pkg_config::Library, std::collections::hash::map::RandomState>>
             at C:\projects\rust\src\libcore\option.rs:302
  10: build_script_build::main
             at .\build.rs:4
  11: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  12: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:476
  13: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:101
  14: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:50
  15: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  16: main
  17: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  18: BaseThreadInitThunk

warning: build failed, waiting for other jobs to finish...
error: build failed

C:\devtools\rust-pkgs\dbus-rs-master>

**Comment by diwic** [comment]
Hmm, so you're trying to compile this under Windows? Interesting. I've not heard of anyone trying to do this before.

First step is to double check that you have development libraries for D-Bus installed in a location where pkg-config can find them. Assuming that's the case, I guess it's up to you to try to pin down the error which is likely in the build system somewhere below my crate (metadeps, pkg-config crates).

**Comment by diwic** [comment]
Closing due to lack of reply.
