### ISSUE TITLE
[dbus-codegen] `dbus-codegen` panics on handles in arguments

### ISSUE THREAD

**Issue by 1wilkens** [diwic/dbus-rs#120]
When trying to use `dbus-codegen` to generate bindings for the [logind Manager API](https://www.freedesktop.org/wiki/Software/systemd/logind/) I noticed it panicking if an argument with the type "h"/Handle was encountered.

The panic message given was
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: StringError("Unknown character in signature Ok(UnixFd)")'`
```

It does not matter whether the argument is "in" or "out" as the following example quickly shows:
```xml
<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>
    <interface name="org.example">
        <method name="SomeMethod">
            <arg name="arg0" direction="in" type="h" />
            <arg name="result" direction="out" type="h" />
        </method>
    </interface>
</node>
```

I don't know if this error is based on any implementation specifics which prevent `UnixFd`s from appearing in arguments or if this is just not yet implemented. In any case the call to `unwrap` should probably replaced with an `expect` or handled otherwise.

I'll check out the code and see if I can whip up aquick PR.

EDIT: Okay although the backtrace was not helpful I think the `unwrap` occurs directly in `main` with the error being bubbled up from `generate`. Panicking should be fine here which leaves the question if and how the error message could be improved.
Also as I see [here](https://github.com/diwic/dbus-rs/blob/639ddbcf78fa9f1fb7e0a0a9d56cf12aef9405bf/dbus-codegen/src/generate.rs#L156) the issue seems indeed to point to a missing implementation.
@diwic Any pointers on how I could approach fixing this?

**Comment by diwic** [comment]
Yeah, it looks like the xml_to_rust_type function is missing a match for `Ok(ArgType::UnixFd) => dbus::OwnedFd`.
