### ISSUE TITLE
Properties example panic's at metadata unwrapping.

### ISSUE THREAD

**Issue by lynxcs** [diwic/dbus-rs#122]
Trying to run the Properties example, yet it keeps panicking.

`thread 'main' panicked at 'called 'Result::unwrap()' on an 'Err' value: D-Bus error: D-Bus argument type mismatch at position 0: expected Variant, found same but still different somehow (org.freedesktop.DBus.Error.Failed)', libcore/result.rs:945:5`

**Comment by diwic** [comment]
Thanks for the report! Example fixed now.
