### ISSUE TITLE
Accessing float from Variant<Box<RefArg>> ?

### ISSUE THREAD

**Issue by lynxcs** [diwic/dbus-rs#123]
In the Argument_guide's Variant section there's this sentence:

> Ok, so we retrieved our Box<RefArg>. We now need to use the RefArg methods to probe it, to see what's inside. Easiest is to use as_i64 or as_str if you want to test for integer or string types. **Use arg::cast for floating point values, and as_iter if the variant contains a complex type you need to iterate through.** Or match over arg_type if you need to know the exact type. 

In particular I'm interested in the casting floats part. I've been trying to modify the properties example print_refarg function to also accept floats yet I've had no luck so far.

The problems I've faced are:
- Checking if the value is a float (the method arg_type just returns Variant)
- Accessing the value inside of the Variant (This is just something I'm having trouble understanding)

I apologize if this is something really obvious, but I'm just starting out in rust and would really appreciate it if someone could help out.

**Comment by diwic** [comment]
The Variant's field is public, so you can access the value inside the Variant with `.0`, i e `my_variant.0.arg_type()`. I've added a few more sentences in the argument guide about this.

That said, adding a `as_f64` method wouldn't hurt. It's the only type that cannot be retreived using `as_i64`, `as_str` or `as_iter`.

**Comment by lynxcs** [comment]
Thank you for clearing things up for me. If I wanted to access an Array I'd use the as_iter() method yes?

And also how about UInt64? Trying to access it with as_i64 doesn't work.

**Comment by diwic** [comment]
> If I wanted to access an Array I'd use the as_iter() method yes?

Yes.

 > And also how about UInt64? Trying to access it with as_i64 doesn't work.

Right, so we need an `as_u64` too... 
Meanwhile, `arg::cast<u64>()` should work.

**Comment by diwic** [comment]
Ok, I have now implemented `as_u64` and `as_f64`, and documented which ArgTypes support which methods. It'll be in the next release. Until then, use `arg::cast`.

**Comment by lynxcs** [comment]
Ah ok, thank you.
