### ISSUE TITLE
Cannot create empty MessageItem::Array

### ISSUE THREAD

**Issue by manuels** [diwic/dbus-rs#13]
Great library, but I'm having a huge problem with the fact that you cannot create an empty array (see https://github.com/diwic/dbus-rs/blob/master/src/message.rs#L208) which is a huge problem (for example if you want to return a list of some search results that is empty).
I think that this issue could be resolved easily by just passing the type signature as a parameter.

**Comment by diwic** [comment]
Hi!

DBus needs to know the `TypeSig` of the array even if it's empty. 
If you know the `TypeSig` it's easy to construct an empty array, e g, for an array of doubles you could write `MessageItem::Array(vec!(), MessageItem::Double(0).type_sig())` or `MessageItem::Array(vec!(), Cow::Borrowed("d"))`.

The `new_array` function is just a helper function for arrays you know are non-empty.

**Comment by manuels** [comment]
Oh, ok. A warning in the docs would be great ;)

**Comment by diwic** [comment]
The docs currently say: "Note: Will panic if the vec is empty or if there are different types in the array". If you have a better suggestion feel free to submit a merge proposal :-)

**Comment by gfxmonk** [comment]
@dwic I hit this problem too, and it wasn't until finding this issue that I figured it out. I did consider manually constructing a `MessageItem::Array`, but it wasn't obvious how to get a type signature. So perhaps we could add the above example to the docs next to the warning about empty arrays?

It does also seem a little odd to construct an unused value just to get its signature. So I had a go at being able to represent types directly. It's in my [`item-type`](https://github.com/gfxmonk/dbus-rs/tree/item-type) branch, which introduces an `empty_array(type)` method. It might be too much effort just to support this edge case, but it's there if you want it :)

**Comment by diwic** [comment]
Hi @gfxmonk and thanks for looking into it.

I've been thinking and experimenting some about the array stuff too, but I'm not sure I hit the perfect spot yet. I'm wondering whether to actually create an `Array` struct that would always uphold the invariant of being a valid D-Bus array (right now, nothing is stopping you from creating an invalid typesig, or different element types in the array.

Anyhow, there is a fairly new array helper in `impl<'a, T> From<&'a [T]> for MessageItem where T: Into<MessageItem> + Clone + Default`, that is able to create empty arrays too. E g the below should create an array of `Int16` with correct typesig, regardless of whether or not `a` is empty:

     fn foo(a: &[i16]) {
         let z: MessageItem = a.into();
     }

**Comment by gfxmonk** [comment]
Ahh, that's very cool. I was wondering if a types-only approach would work, but couldn't think of anything that didn't involve excessive generics. Well I'm pretty happy with that then, although it'd be great if some of these examples could make their way into the docs :)

**Comment by diwic** [comment]
> Well I'm pretty happy with that then, although it'd be great if some of these examples could make their way into the docs :)

Certainly. I don't mind taking merge proposals for more examples. Meanwhile I added a quick comment in `new_array` [see this commit](https://github.com/diwic/dbus-rs/commit/73a47eb0a979e413212aacf56c33619473fa33ea)
