### ISSUE TITLE
`dbus-codegen` generates invalid Rust variable names

### ISSUE THREAD

**Issue by goose121** [diwic/dbus-rs#130]
When trying to create bindings for [org.freedesktop.Avahi.Server](https://github.com/lathiat/avahi/blob/98b881dca0323535ef12c3d5151feb00b096aab9/avahi-daemon/org.freedesktop.Avahi.Server.xml) interface ([here is the output generated](https://gist.github.com/goose121/1ec506479e1998aa01a5c8009aff1358)), it seems that `dbus-codegen` doesn't take into account that the names of D-BUS method parameters can be invalid Rust names, as it generates many variables named `type`, leading to invalid Rust code.

**Comment by diwic** [comment]
I pushed a commit I believe fixes this. Please test it and reopen in case it does not work as expected. Thanks!
