### ISSUE TITLE
dbus::Error to implement Sync trait (aka failures support)

### ISSUE THREAD

**Issue by flub** [diwic/dbus-rs#131]
Currently the dbus::Error type does not implement the Sync trait.  This means it can not automatically be converted to the failures::Fail trait to use failures-style error handling.  It would be somewhat nice if this was possible.

**Comment by diwic** [comment]
`dbus::Error` is correct to not implement `Sync`. It's an opaque FFI struct and there is no guarantee that the inner details of that C library follows Rust Sync conventions now or in the future.

Pro tip: You can convert from `dbus::Error` to `MethodErr` if you want something that implements `Sync`.

**Comment by flub** [comment]
Thanks for the explanation (I'm pretty new to all things Rust), and also many thanks for providing such a good D-Bus library!  I don't actually need it to be Sync as my tiny application is single-threaded.  It's only a way to get automatic failure::Fail trait implementation.  Do you think the library might at some point providing direct support for this trait or is it way to early in the life of the failure crate to consider this?

**Comment by diwic** [comment]
I have no intention, at least not right now, to make my dbus crate depend on `failure`.

**Comment by cmeister2** [comment]
I'm hitting this right now. I basically had to wrap common functions to make them work nicely in my codebase; having `.map_err` all over the place isn't terrible but it's a little bit messy.

Not saying you should fix this immediately (or indeed at all) - it might be that the easiest way for me to fix this long term is to write a wrapper library which hides the errors that aren't compatible with `failure` out of the box.

**Comment by diwic** [comment]
I'm hesitant to `failure` for the following reasons:

 * It seems to split the Rust ecosystem in two (those who use it and those who don't)
 * It requires errors to be Sync, which is an unnecessary restriction (how often do you want to read errors from more than one thread at a time?)
 * It attaches backtraces to errors (at least by default), which in most cases are an unnecessary performance penalty for error handling

All the above is AFAIK and I don't have in-depth knowledge, so take it with a grain of salt and correct me if I'm wrong.

All of that said, if anyone would like to submit a PR that introduces a `failure` dependency that's optional, not enabled by default, and doesn't disturb the rest of the code much, then I'm open for merging it.

**Comment by diwic** [comment]
Filed: https://github.com/rust-lang-nursery/failure/issues/201

**Comment by cmeister2** [comment]
I had a brief look into this. It seemed on the face of it that the general pattern here was:

- Create `Error` using `Error::empty()`
- Pass the inner `DBusError` into a dbus function using `get_mut()`
- Use the `name()` and `message()` functions when displaying the error.

I played with one option: having a `LwError` which is the same lightweight error wrapper as currently, and then an `Error` struct with `name` and `message` fields, and a way of converting `LwError` to `Error`. It seemed to broadly work, and in terms of performance it wouldn't affect the mainline too much. Perhaps a simpler alternative would be to just construct one-off `DBusError`s and extract the strings from them at the point of returning an `Err`.

However, in terms of the external interface, I think any option here is going to be tricky to be strictly backwards compatible. The `Error` struct would likely lose some methods (e.g. `get_mut()` and `empty()`) - so I'm not sure about "not disturbing the rest of the code too much".

Of course if I've missed something here (the internal DBusError being used for some other purpose) then this is mostly moot 😄

**Comment by diwic** [comment]
> I played with one option: having a LwError which is the same lightweight error wrapper as currently, and then an Error struct with name and message fields, and a way of converting LwError to Error.

Hmm, this is already present today, as `MethodErr` is the Error struct you're describing (and it implements `From<Error>`, so it's very simple to convert an Error to MethodErr).

It sounds like you want to change methods currently returning `Error` to instead return `MethodErr`, but I'm not happy about that, unless it's done as an optional feature.

**Comment by diwic** [comment]
Okay, so after some discussion in that other bug and a closer look at this, it does indeed seem like dbus::Error could in fact implement Sync!
