### ISSUE TITLE
Emitting PropertyChanged signals for related properties

### ISSUE THREAD

**Issue by flub** [diwic/dbus-rs#132]
I've have been trying to figure out how to emit the PropertyChanged signals for interlinked properties.  E.g. I have one PctValue and one RawValue property and if one changes the other changes too.  But emitting other signals, or sending any messages, from within the `on_set()` handler seems very difficult.  The best I've come up with is to generate the signal message from within `on_set()` -using `add_propertieschanged()` and `to_emit_message()`- and then pass it via an mpsc channel up to the mainloop.  The mainloop then does `conn.incoming(1000); for msg in ch.try_iter() { conn.send(msg) }` to send this.

This is far from ideal, two messages are sent while this could be a single signal and there is also an arbitrary delay for this as well.

Is there a better way to either generically send messages from inside handlers?  Or the more specific question of how to change multiple properties in one signal?

Thanks

**Comment by diwic** [comment]
I've been thinking about this issue and I don't think it has a clean solution right now. I have to figure out a good solution that does not break backwards compatibility.

Meanwhile, I can think of at least two workarounds:

The simplest workaround (just for the delay), just stuff your connection into an `Arc` or `Rc` and put a clone of it inside your handler. Then you can access the connection and send as many messages as you want from the handler.

Another workaround is to not call `connection.add_handler` on the tree, but instead call `tree.handle` for incoming messages (that you get from `conn.incoming()`). This way you can intercept the messages being returned from the handler and modify them to your liking before you send them.

**Comment by diwic** [comment]
So I think this is two problems in one:

> Or the more specific question of how to change multiple properties in one signal?

So I've just added a way to suppress the automatic emission of the PropertiesChanged signal, and you can do it manually instead. I think this is the most reasonable way to resolve this part. Please try it out.

> Is there a better way to either generically send messages from inside handlers? 

This one is the trickier one to solve without losing backwards compatibility. The question is only relevant for prop_get and prop_set methods. Maybe we could add something to `PropInfo` that would allow for people to add messages to be sent, but I wonder if I could sneak that in without anyone depending on the current layout of the struct...

**Comment by flub** [comment]
Oh nice, that makes things a bit simpler.  I started implementing the manual tree.handle way and was going to report back when it was all working, just haven't had time to continue writing this the last week.  But not having to filter these replies will make things easier.

Is it possible to have a Property.on_set(H) variation where H can return a vector of messages in it's Ok() value?

My current approach is to create the messages in the on_set handler and send them to the mainloop using an mpsc channel to be sent over the connection.

**Comment by diwic** [comment]
> Is it possible to have a Property.on_set(H) variation where H can return a vector of messages in it's Ok() value?

This is a good suggestion. It would be possible, but it would require changing the [MethodType](https://docs.rs/dbus/0.6.1/dbus/tree/trait.MethodType.html) trait, that hopefully nobody uses except dbus itself, but still it would be a backwards incompatible change.

 > My current approach is to create the messages in the on_set handler and send them to the mainloop using an mpsc channel to be sent over the connection.

Or just put the connection into an Rc/Arc and put a clone inside the on_set closure?
