### ISSUE TITLE
Sending signals with arguments?

### ISSUE THREAD

**Issue by AmarOk1412** [diwic/dbus-rs#133]
Hi!

I use this lib for one of my project (nice lib btw). I'm currently doing some unit-tests for it and I need to mock a daemon which use dbus.

The code is working to handle signals... but I don't succeed to send this signal with my mock.

The code I want to test:

```rust
    pub fn handle_signals(m: X) {
        // Use another dbus connection to listen signals.
        let dbus_listener = Connection::get_private(BusType::Session).unwrap();
        dbus_listener.add_match("interface=x,member=incomingTrustRequest").unwrap();
        
        // For each signals, call handlers.
        for i in dbus_listener.iter(100) {
            if let Some((account_id, from)) = m.handle_requests(&i) {
                println!("ok");
            };
        }
    }

    fn handle_requests(&self, ci: &ConnectionItem) -> Option<(String, String)> {
        // Check signal
        let msg = if let &ConnectionItem::Signal(ref signal) = ci { signal } else { return None };
        if &*msg.interface().unwrap() != "cx.ring.Ring.ConfigurationManager" { return None };
        if &*msg.member().unwrap() != "incomingTrustRequest" { return None };
        // incomingTrustRequest return three arguments
        let (account_id, from, _, _) = msg.get4::<&str, &str, Dict<&str, &str, _>, u64>();
        Some((account_id.unwrap().to_string(), from.unwrap().to_string()))
    }
```

The test is something like:

```rust
        let test = thread::spawn(move || {
            Manager::handle_signals(shared_manager_cloned, stop_cloned);
        });

        let two_sec = Duration::from_millis(22000);
        thread::sleep(two_sec); // wait for init

        emit_incoming_trust_request(); // MOCK

        //wait

        // A new anonymous user should be present
        assert!(shared_manager.lock().unwrap().server.anonymous_user.devices.len() == 1);

        stop.store(true, Ordering::SeqCst);
        let _ = test.join();
```

With something like that in the mock:

```rust
let f = Factory::new_fn::<(TData)>();

        let incoming_trust_request = Some(Arc::new(
            f.signal("incomingTrustRequest", ())
             .arg(("accountID", "s"))
             .arg(("from", "s"))
             .arg(("payload", "ay"))
             .arg(("receiveTime", "t"))
        ));
// (the signal is successfully shown in the tree)

loop {
            connection.incoming(100).next();
            let emit_incoming_trust_request = daemon.lock().unwrap().emit_incoming_trust_request.load(Ordering::SeqCst);
            if emit_incoming_trust_request {
                let signal = incoming_trust_request.clone().unwrap();
                let path = configuration_path.to_string().into();
                let iface = configuration_iface.to_string().into();
                let mut args: Vec<MessageItem> = Vec::new();
                args.push(MessageItem::from(String::from("GLaDOs_id")));
                args.push(MessageItem::from(String::from("Weasley")));
                args.push(MessageItem::from(DictEntry(Box::new(MessageItem::from(String::new())), Box::new(MessageItem::from(String::new())))));
                args.push(MessageItem::from(0));
                let msg = signal.emit(&path, &iface, &args);
                let _ = connection.send(msg).map_err(|_| "Sending DBus signal failed");
                // Ok(6)
                daemon.lock().unwrap().emit_incoming_trust_request.store(false, Ordering::SeqCst);
            }

            let stop = daemon.lock().unwrap().stop.load(Ordering::SeqCst);
            if stop {
                return;
            }
        }
```

It's like it's working for signals without any arguments... but not for my signal with 4 args...

I don't know what I'm missing. I don't even see the signal via `dbus-monitor`.

```rust
let msg = signal.emit(&path, &iface, &args);
let _ = connection.send(msg).map_err(|_| "Sending DBus signal failed");
// Ok(6)
```

is this correct?

**Comment by diwic** [comment]
The old `MessageItem` is error prone, but I haven't changed it in order not to break backwards compatibility. E g, you can't have a `DictEntry` if it's not inside an `Array`, that will lead to some D-Bus error. Not sure why this doesn't show up as an error when trying to send the message though.

Instead, don't use `MessageItem`, just append the arguments directly:

    let dict = arg::Dict::new(&[("", "")]); // IIRC
    let msg = signal.msg(&path, &iface).append4(["GLaDOs_id", "Weasley", dict, 0]);

This has the added benefit of giving you compiler errors instead of sending errors to D-Bus.

**Comment by AmarOk1412** [comment]
Oh I see, thx!

Note:

`append4` don't exists and I can't put a dict in args

`the trait `std::convert::From<dbus::arg::Dict<'_, &str, &str, std::vec::IntoIter<(&str, &str)>>>` is not implemented for `dbus::MessageItem`

But I don't need the Dict, so I tried
```rust
let dict = Dict::new(vec![("", "")]);
let msg = signal.msg(&path, &iface).append("GLaDOs_id").append("Weasley").append("").append(0);
```

and it works. So for now it's not a problem (but the fact I can't put a Dict into the append method will be problematic, I'll dig)

**Comment by diwic** [comment]
> append4 don't exists and I can't put a dict in args

Hrm, seems I only implemented up to three. How about:

    let dict = Dict::new(vec![("", "")]);
    let msg = signal.msg(&path, &iface).append2("GLaDOs_id", "Weasley").append2(dict, 0)

**Comment by AmarOk1412** [comment]
Yeah it works. I'm not sure to understand why `append2(dict, x)` works when `append(dict)` doesn't even compile. But it's perfectly what I want, so thank you!

**Comment by diwic** [comment]
I should perhaps deprecate `append` in favor of `append1`, `append2` and `append3` since the newer functions work better.

**Comment by AmarOk1412** [comment]
Yeah can be confusing indeed.
