### ISSUE TITLE
Migrate from tokio-core to tokio

### ISSUE THREAD

**Issue by o01eg** [diwic/dbus-rs#138]
Crate `tokio-core` is considered deprecated now.

**Comment by diwic** [comment]
Is this for tokio 0.1 or is it a part of the upcoming rewrite to tokio 0.2/0.3?

**Comment by o01eg** [comment]
I suppose `tokio` 0.1 is could be considered as a `tokio-core` 0.2.

**Comment by diwic** [comment]
I'm not following tokio development much but I know it is in flux. Before that has settled (i e with futures 0.3, I believe the current plan is) I'm happy to take PRs if they help, but I'm not planning on doing much work on my own.
