### ISSUE TITLE
Send signal to destination?

### ISSUE THREAD

**Issue by swalladge** [diwic/dbus-rs#139]
Is it possible to send a signal to a particular destination? When I send a signal with `connection.send(msg)` or return it from a method call as in the server.rs example, I see the following in the output of `dbus-monitor`:

```
signal time=1531979509.858182 sender=:1.103 -> destination=(null destination) serial=4 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
   int32 234
   int32 1
```

(`destination=(null destination)`)

I don't know much about dbus, so I'm not sure if that's a problem or not. I'm experimenting with building a desktop notifications daemon, and other daemons will set the `destination` id/bus/whatever for signals. I'm guessing the null destination is preventing the application that sent the notification from seeing the `NotificationClosed` signal back?

**Comment by diwic** [comment]
It's very seldom used, based on the fact that dbus-rs has been around for years and you're the first one asking for it :-) But I've added it now.

Signals would typically go to whoever has registered interest. Setting destination I assume means that only the specified destination would receive the signal.

**Comment by swalladge** [comment]
@diwic cool thanks! Yeah I think I need to read up more on dbus - if no-one else has needed it, then perhaps it's unnecessary. :)

**Comment by swalladge** [comment]
@diwic I've been attempting to use `set_destination` on a message, but
unsuccessfully. The following code:

```
let mret = < some message >
println!("{:?}", mret.destination());
let d = Some(BusName::new(":1.14").unwrap());
println!("{:?}", d);
mret.set_destination(d);
```

results in:

```
Some(BusName(":1.14"))
Some(BusName(":1.14"))
dbus[31106]: arguments to dbus_message_set_destination() were incorrect, assertion "destination == NULL || _dbus_check_is_valid_bus_name (destination)" failed in file dbus-message.c line 3656.
This is normally a bug in some application using the D-Bus library.
```

It seems that it's failing on an invalid bus name, while `BusName` is supposed
to be a valid name.

**Comment by swalladge** [comment]
Failing test:

```
diff --git a/dbus/src/message.rs b/dbus/src/message.rs
index 8706091..37711fb 100644
--- a/dbus/src/message.rs
+++ b/dbus/src/message.rs
@@ -995,7 +995,7 @@ pub fn message_set_serial(m: &mut Message, s: u32) {
 mod test {
     extern crate tempdir;
 
-    use super::super::{Connection, Message, MessageType, BusType, MessageItem, OwnedFd, libc, Path};
+    use super::super::{Connection, Message, MessageType, BusType, MessageItem, OwnedFd, libc, Path, BusName};
 
     #[test]
     fn unix_fd() {
@@ -1136,4 +1136,11 @@ mod test {
         m.append_items(&args);
         c.send(m).unwrap();
     }
+
+    #[test]
+    fn set_valid_destination() {
+        let mut m = Message::new_method_call("org.test.rust", "/", "org.test.rust", "Test").unwrap();
+        let d = Some(BusName::new(":1.14").unwrap());
+        m.set_destination(d);
+    }
 }
```
