### ISSUE TITLE
set_destination panic

### ISSUE THREAD

**Issue by swalladge** [diwic/dbus-rs#141]
I've been attempting to use `set_destination` on a message, but unsuccessfully. The following code:

```
let mret = < some message >
println!("{:?}", mret.destination());
let d = Some(BusName::new(":1.14").unwrap());
println!("{:?}", d);
mret.set_destination(d);
```

results in:

```
Some(BusName(":1.14"))
Some(BusName(":1.14"))
dbus[31106]: arguments to dbus_message_set_destination() were incorrect, assertion "destination == NULL || _dbus_check_is_valid_bus_name (destination)" failed in file dbus-message.c line 3656.
This is normally a bug in some application using the D-Bus library.
```

It seems that it's failing on an invalid bus name, while `BusName` is supposed to be a valid name.

Failing test:

```
diff --git a/dbus/src/message.rs b/dbus/src/message.rs
index 8706091..37711fb 100644
--- a/dbus/src/message.rs
+++ b/dbus/src/message.rs
@@ -995,7 +995,7 @@ pub fn message_set_serial(m: &mut Message, s: u32) {
 mod test {
     extern crate tempdir;
 
-    use super::super::{Connection, Message, MessageType, BusType, MessageItem, OwnedFd, libc, Path};
+    use super::super::{Connection, Message, MessageType, BusType, MessageItem, OwnedFd, libc, Path, BusName};
 
     #[test]
     fn unix_fd() {
@@ -1136,4 +1136,11 @@ mod test {
         m.append_items(&args);
         c.send(m).unwrap();
     }
+
+    #[test]
+    fn set_valid_destination() {
+        let mut m = Message::new_method_call("org.test.rust", "/", "org.test.rust", "Test").unwrap();
+        let d = Some(BusName::new(":1.14").unwrap());
+        m.set_destination(d);
+    }
 }
```

Maybe I'm just using it incorrectly?

By the way, my use case is to send signals from a dbus notifications daemon (eg. NotificationClosed) to client apps that launched the notification. Sending the signal without setting a destination doesn't seem to be alerting the client apps, so I'm trying to set the destination to see if that helps.

Thanks.

**Comment by diwic** [comment]
Thanks! I added your supplied test case and fixed the bug.

(Sorry for the slow reply - I've been on summer vacation.)

  > Sending the signal without setting a destination doesn't seem to be alerting the client apps, so I'm trying to set the destination to see if that helps.

I doubt it helps - sending the signal without setting a destination should send it to any client that has subscribed to that specific signal.

**Comment by swalladge** [comment]
Thanks!

> I doubt it helps - sending the signal without setting a destination should send it to any client that has subscribed to that specific signal.

@diwic Yep, it didn't help setting the destination (although it now behaves the same as other programs i was comparing against)... I'm trying to implement a dbus [desktop notifications](https://developer.gnome.org/notification-spec/) server, and can't work out why sending a notification closed signal doesn't get picked up by the client. The only final difference I can see is that the signal sends int instead of uint values back in the signal, even though i set the parameter type to `u32`. Do you know of a good place to get advice/help about implementing and debugging dbus applications?

Thanks again for your support. :smile:

**Comment by diwic** [comment]
@swalladge 

 > The only final difference I can see is that the signal sends int instead of uint values back in the signal, even though i set the parameter type to u32. Do you know of a good place to get advice/help about implementing and debugging dbus applications?

Getting the right type can be important, so make sure you do append an u32 to your signal and nothing else (not sure what you mean by "set the parameter type").

**Comment by swalladge** [comment]
@diwic sorry I mean the type parameter when declaring the signal:

```
    let notification_closed = Arc::new(
        f.signal("NotificationClosed", ())
            .sarg::<&u32, _>("id")
            .sarg::<&u32, _>("reason"),
    );
```

I ended up needing to ensure the args to append were u32 as you suggested:

```
            let mut sig = notification_closed
                .msg(&path, &interface)
                .append1(12 as u32)
                .append1(2 as u32);
```

Thanks for your help, and sorry for taking github issues offtopic. :)
