### ISSUE TITLE
Support: How to use as_iter to read arrays of variants?

### ISSUE THREAD

**Issue by Mange** [diwic/dbus-rs#142]
So I've been spending days trying to get this to work. I have a `Variant<Box<RefArg>>` that I get from reading a dict of "string -> variant".

I'm transforming all values into my own enum type in order to make things easier downstream.

Here's a simplified example:

```rust
use dbus::arg::{cast, RefArg, Variant, ArgType};

enum Value {
  Unsupported,
  String(String),
  Int32(i32),
  // … many variants
}

impl Value {
  fn from_variant(variant: Variant<Box<RefArg>>) -> Value {
      let data = &variant.0;
      match data.arg_type() {
          ArgType::String => Value::String(data.as_str().unwrap().into()),
          ArgType::Int32 => Value::Int32(*cast::<i32>(data).unwrap()),
          // … many variants, some with ::as_foo, some with cast::<foo>.
          _ => Value::Unsupported,
      }
  }
}
```

Now I want to support Arrays too, but then I can no longer use `cast`:

```rust
use dbus::arg::{cast, RefArg, Variant, ArgType};

enum Value {
  Unsupported,
  Array(Vec<Value>),
  String(String),
  Int32(i32),
}

impl Value {
  fn from_variant(variant: Variant<Box<RefArg>>) -> Value {
      Value::from_refarg(&variant.0)
  }

  fn from_refarg(data: &RefArg) -> Value {
      match data.arg_type() {
          ArgType::Array => Value::Array(data.as_iter().unwrap().map(Value::from_refarg).collect()),
          ArgType::String => Value::String(data.as_str().unwrap().into()),
          // ArgType::Int32 => Value::Int32(*cast::<i32>(data).unwrap()),
          _ => Value::Unsupported,
      }
  }
}
```

If I uncomment that line I get this compiler error:

```
error[E0621]: explicit lifetime required in the type of `data`
  --> src/foo.rs:25:55
   |
21 |   fn from_refarg(data: &RefArg) -> Value {
   |                  ---- consider changing the type of `data` to `&'static dbus::arg::RefArg + 'static`
...
25 |           ArgType::Int32 => Value::Int32(*cast::<i32>(data).unwrap()),
   |                                                       ^^^^ lifetime `'static` required

error: aborting due to previous error
```

Taking the advice and changing the reference to a `'static` type, and attaching the `'static` bound on `RefArg` yields this:

```rust
// …
  fn from_refarg(data: &'static (RefArg + 'static)) -> Value {
// …
```

```
error[E0597]: `variant.0` does not live long enough
  --> src/foo.rs:12:27
   |
12 |       Value::from_refarg(&variant.0)
   |                           ^^^^^^^^^ borrowed value does not live long enough
13 |   }
   |   - borrowed value only lives until here
   |
   = note: borrowed value must be valid for the static lifetime...

error: aborting due to previous error
```

So now I cannot deal with the `Box` anymore since I cannot borrow from it `'static`ally.

It seems to me that the signatures `Variant<Box<RefArg>>` and the type that `as_iter` yields (`&'a RefArg`) cannot be used in the same context. I've also been trying to just duplicate all the code between the methods, but the problem remains because I cannot call `from_refarg` from `from_variant` if it sees an `Array` so I have no way of actually reading the array contents.

Please tell me I'm missing something here. :sweat_smile:
I also suggest an example where it does something like this, both to serve as documentation, but also to highlight how much ceremony one has to follow to use `Variant` in a program. That might help you evolve this part of the API.

---

Extra context:

* I have a `Variant<Box<RefArg>>` because that is what the codegen generated for me. I'm fine with reading the property some other way if that simplifies things.
* I'm building a client that receives this data, I'm not sending it.
* I need it to supports arrays inside arrays.

**Comment by Mange** [comment]
I think I figured out an alternative solution... I upgraded to 0.6.2 where `as_f64` exists, and then I implemented it this way:

```rust
        match ref_arg.arg_type() {
            ArgType::Array => ref_arg.as_iter().map(|iter| {
                iter.flat_map(Value::from_ref_arg).collect::<Vec<_>>()
            }).map(Value::from),
            ArgType::Boolean => ref_arg.as_u64().map(|n| n == 1).map(Value::from),
            ArgType::Byte => ref_arg.as_u64().map(|n| n as u8).map(Value::from),
            ArgType::Double => ref_arg.as_f64().map(Value::from),
            ArgType::Int16 => ref_arg.as_i64().map(|n| n as i16).map(Value::from),
            ArgType::Int32 => ref_arg.as_i64().map(|n| n as i32).map(Value::from),
            ArgType::Int64 => ref_arg.as_i64().map(Value::from),
            ArgType::String => ref_arg.as_str().map(String::from).map(Value::from),
            ArgType::UInt16 => ref_arg.as_u64().map(|n| n as u16).map(Value::from),
            ArgType::UInt32 => ref_arg.as_u64().map(|n| n as u32).map(Value::from),
            ArgType::UInt64 => ref_arg.as_u64().map(Value::from),
            _ => Some(Value::Unsupported),
        }

```

I avoided `cast` altogether. :tada: 

Is this semi-sane, or will this come back and haunt me later? :ghost:

**Comment by diwic** [comment]
Sounds like you have reinvented `MessageItem`. :-)

In general I would recommend your second approach that avoids cast altogether. But the cast version should work too.
Having pondered about this a bit, I think we should maybe try to get a `Box<RefArg + 'static>` out of codegen instead of a `Box<RefArg>`. With this we could make something like

     from_refarg(data: &(RefArg + 'static)) -> Value

Would you mind to donate the xml file with introspection data, so I can see if it's possible to change codegen to get a `Box<RefArg + 'static>` out?

**Comment by diwic** [comment]
Ok, I changed the code generation slightly so that it returns a `Box<RefArg + 'static>` where it seemed appropriate. Can you regenerate and see if that helps?

**Comment by Mange** [comment]
Interesting. I'll take a look.

The code is in https://github.com/Mange/mpris-rs. Specifically, this is the commit that used my workaround above: https://github.com/Mange/mpris-rs/commit/66529412f1f2288dce783782c785bba02ccecfec

https://github.com/Mange/mpris-rs/blob/66529412f1f2288dce783782c785bba02ccecfec/src/metadata/value.rs#L53-L75

> Sounds like you have reinvented `MessageItem`. :-)

Hmm, yeah that looks very similar. Of course the whole point here is that I'm writing a library and don't want `dbus` to be part of the external API so I have to wrap it anyway. :stuck_out_tongue: 
But it would be easier for me to convert it from that structure for sure.

**Comment by Mange** [comment]
I changed the generated code to always output `RefArg + 'static` and then adjusted my code in the same fasion. Sadly, it didn't work. `rustc` is complaining that `flat_map`/`map` on the `iter` requires `'static` lifetime.

```rust
    pub(crate) fn from_ref_arg(ref_arg: &(RefArg + 'static)) -> Option<Value> {
        match ref_arg.arg_type() {
            ArgType::Array => ref_arg.as_iter().map(|iter| {
                iter.flat_map(Value::from_ref_arg).collect::<Vec<_>>()
            }).map(Value::from),
            _ => Some(Value::Unsupported),
        }
    }
```

```
error[E0621]: explicit lifetime required in the type of `ref_arg`
  --> src/metadata/value.rs:61:22
   |
58 |     pub(crate) fn from_ref_arg(ref_arg: &(RefArg + 'static)) -> Option<Value> {
   |                                ------- consider changing the type of `ref_arg` to `&'static dbus::arg::RefArg + 'static`
...
61 |                 iter.flat_map(Value::from_ref_arg).collect::<Vec<_>>()
   |                      ^^^^^^^^ lifetime `'static` required

error: aborting due to previous error
```

This is why I switched to using `&'static (RefArg + 'static)` in my initial experimentation. :see_no_evil:

Trying to add a new explicit lifetime does not help:

```rust
    pub(crate) fn from_ref_arg<'a>(ref_arg: &'a (RefArg + 'static)) -> Option<Value> {
        match ref_arg.arg_type() {
            ArgType::Array => ref_arg.as_iter().map(|iter| {
                iter.flat_map(Value::from_ref_arg).collect::<Vec<_>>()
            }).map(Value::from),
            _ => Some(Value::Unsupported),
        }
    }
```

```
error[E0495]: cannot infer an appropriate lifetime for autoref due to conflicting requirements
  --> src/metadata/value.rs:60:39
   |
60 |             ArgType::Array => ref_arg.as_iter().map(|iter| {
   |                                       ^^^^^^^
   |
note: first, the lifetime cannot outlive the lifetime 'a as defined on the method body at 58:5...
  --> src/metadata/value.rs:58:5
   |
58 |     pub(crate) fn from_ref_arg<'a>(ref_arg: &'a (RefArg + 'static)) -> Option<Value> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...so that reference does not outlive borrowed content
  --> src/metadata/value.rs:60:31
   |
60 |             ArgType::Array => ref_arg.as_iter().map(|iter| {
   |                               ^^^^^^^
   = note: but, the lifetime must be valid for the static lifetime...
   = note: ...so that the types are compatible:
           expected std::ops::FnMut<(&dbus::arg::RefArg,)>
              found for<'a> std::ops::FnMut<(&'a dbus::arg::RefArg + 'static,)>

error: aborting due to previous error
```

I'm a newbie when it comes to `'static` (I just recently tried to understand it to work on this issue), and my problem with it is the "double meaning" of "May outlive the entire lifetime" when it's attached to a borrow and the "Does not contain a borrow" when attached to a type. I'm not sure if that's really how I should be internalizing it, but right now that's my idea. I can't see why borrowck think that `'a` must be `'static` to fulfill the `FnMut` thing with this internal model.

Anyway, maybe you have a better idea on how this all fits together.

**Comment by Mange** [comment]
I found a much better solution. Instead of relying on the generated method that returns variants of boxed refargs, I implemented `dbus::arg::Get` for my custom type and read it directly in the form I want them to be in.

```rust
impl<'a> dbus::arg::Get<'a> for Value {
    fn get(i: &mut dbus::arg::Iter) -> Option<Self> {
        use dbus::arg::ArgType;

        let arg_type = i.arg_type();
        // Trying to calculate signature of an invalid arg will panic, so abort early.
        if let ArgType::Invalid = arg_type {
            return None;
        }
        let signature = i.signature();

        match arg_type {
            // Hashes in DBus are arrays of Dict pairs ({string, variant})
            ArgType::Array if *signature == *"a{sv}" => {
                i.get::<HashMap<String, Value>>().map(Value::Map)
            }
            ArgType::Array => i.get::<Vec<Value>>().map(Value::Array),
            ArgType::Boolean => i.get::<bool>().map(Value::Bool),
            ArgType::Byte => i.get::<u8>().map(Value::U8),
            ArgType::Double => i.get::<f64>().map(Value::F64),
            ArgType::Int16 => i.get::<i16>().map(Value::I16),
            ArgType::Int32 => i.get::<i32>().map(Value::I32),
            ArgType::Int64 => i.get::<i64>().map(Value::I64),
            ArgType::String => i.get::<String>().map(Value::String),
            ArgType::UInt16 => i.get::<u16>().map(Value::U16),
            ArgType::UInt32 => i.get::<u32>().map(Value::U32),
            ArgType::UInt64 => i.get::<u64>().map(Value::U64),
            ArgType::Variant => i.recurse(ArgType::Variant).and_then(|mut iter| iter.get()),
            ArgType::Invalid => unreachable!("Early return at the top of the method"),
            ArgType::DictEntry
            | ArgType::UnixFd
            | ArgType::Signature
            | ArgType::ObjectPath
            | ArgType::Struct => Some(Value::Unsupported),
        }
    }
}
```

```rust
        use dbus::stdintf::org_freedesktop_dbus::Properties;

        let connection_path = self.connection_path();

        Properties::get::<HashMap<String, Metadata::Value>>(
            &connection_path,
            "org.mpris.MediaPlayer2.Player",
            "Metadata",
        ).map(Metadata::from)
            .map_err(DBusError::from)
```

That, to me, is easier to reason about and clearer since it involves fewer steps. So for me I don't need any more help.

I'm not sure if the underlying issue of trying to use the array types from codegen still deserves its own issue. Perhaps it should be opened as a new issue then to avoid all the noise I've been making here.

No matter what, I hope future code explorers with the same issue learns something useful from this thread.

Thank you for your help, @diwic! :heart:
