### ISSUE TITLE
Support: How to get array out of Variant

### ISSUE THREAD

**Issue by ammgws** [diwic/dbus-rs#146]
New to Rust and having some trouble working with Variants.
Could I please have some guidance on how to get the array out of this Variant?
(I want to work with the values such as "xkb:usa::eng" etc inside of it)

Code:
```rust
    let c = Connection::open_private(&ibus_address).unwrap();
    let p = c.with_path("org.freedesktop.IBus", "/org/freedesktop/IBus", 5000);
    use stdintf::org_freedesktop_dbus::Properties;
    let info: arg::Variant<Box<arg::RefArg>> = p.get("org.freedesktop.IBus", "GlobalEngine").unwrap();
    print_refarg(&info); 
    let data = &info.0;
    println!("{:?}", data);
```

Output:
```
Variant(["IBusEngineDesc", {}, "xkb:us::eng", "English (US)", "English (US)", "en", "GPL", "Peng Huang <shawn.p.huang@gmail.com>", "ibus-keyboard", "us", 99, "", "", "", "", "", "", "", ""])

["IBusEngineDesc", {}, "xkb:us::eng", "English (US)", "English (US)", "en", "GPL", "Peng Huang <shawn.p.huang@gmail.com>", "ibus-keyboard", "us", 99, "", "", "", "", "", "", "", ""]
```

Do I need to cast it after accessing .0?

For reference - output from CLI tool:
```sh
>qdbus --bus unix:abstract=/tmp/dbus-xasfd3 --literal org.freedesktop.IBus /org/freedesktop/IBus org.freedesktop.DBus.Properties.Get org.freedesktop.IBus GlobalEngine

[Variant: [Variant: [Argument: (sa{sv}ssssssssussssssss) "IBusEngineDesc", [Argument: a{sv} {}], "xkb:us::eng", "English (US)", "English (US)", "en", "GPL", "Peng Huang <shawn.p.huang@gmail.com>", "ibus-keyboard", "us", 99, "", "", "", "", "", "", "", ""]]]
```

**Comment by diwic** [comment]
`info.0` contains a `Box<RefArg>` and `RefArg` has methods such as `as_iter` and `as_str`. So if you have strings inside the array, try something like:

    for x in info.0.as_iter() {
        println!("{}", x.as_str());
    }

**Comment by ammgws** [comment]
Thanks for the reply. I've actually tried that but it fails to compile:
```
error[E0599]: no method named `as_str` found for type `std::boxed::Box<dyn std::iter::Iterator<Item=&dyn dbus::arg::RefArg>>` in the current scope
```
`info` is `dbus::arg::Variant<std::boxed::Box<dyn dbus::arg::RefArg>>`
`info.0` is `std::boxed::Box<dyn dbus::arg::RefArg>`

**Comment by diwic** [comment]
Sorry, there's a missing unwrap (or other error handling). This works:

    for x in info.0.as_iter().unwrap() {
        println!("{:?}", x.as_str());
    }

(Side note: The error message without unwrap is confusing, because without the `unwrap` what you get is an `Option<Box<Iterator>>` and there an `as_iter` method on the `Option` itself, that turns the option into an iterator of 0 or 1 elements...)

**Comment by ammgws** [comment]
Cheers for that! Ended up getting the element I need as such:
`let x = info.0.as_iter().unwrap().nth(2).unwrap().as_str().unwrap();`
Now I can continue to code and hopefully come back for these unwraps later.
Thank you again!
