### ISSUE TITLE
Parse input arguments

### ISSUE THREAD

**Issue by yohanesu** [diwic/dbus-rs#15]
Thank you for the great rust wrapper! I have a question.

I can't find any example on how to parse the input arguments and convert from MessageItem to for example String. Is this not implemented yet? If it is, how can get the incoming arguments as native types, ie, i32, String, etc?

**Comment by yohanesu** [comment]
Found it!  I can get the string by using
if let Some(&MessageItem::Str(ref s)) = msg.get_items().get(0)

But that means the "Input arguments" vec can be left empty and has not effect. Are those for different purpose?

**Comment by diwic** [comment]
> But that means the "Input arguments" vec can be left empty and has not effect. Are those for different purpose?

Sorry, I don't understand this question. But maybe I could try to make use of the from/into traits to make conversion to and from MessageItem more ergonomic.

**Comment by yohanesu** [comment]
In the Method::new there are parameters which are vectors for input and output parameters. I'm not sure how to use theses. Even leaving the input vec parameters empty like in the server example code I can receive and parse input argument if sent by the client side. Are these vectors only for introspection?

**Comment by diwic** [comment]
> Are these vectors only for introspection?

Yes.

**Comment by yohanesu** [comment]
Ok. Thanks!

**Comment by diwic** [comment]
> But maybe I could try to make use of the from/into traits to make conversion to and from MessageItem more ergonomic.

I've now done that, so instead of

    if let Some(&MessageItem::Str(ref s)) = msg.get_items().get(0)

you can now also write:

    let s: &str = try!(try!(msg.get_items().get(0).ok_or(())).inner());
