### ISSUE TITLE
Not preserving type information in Variant<_>, going from `a{ss}` to `a{sv}`

### ISSUE THREAD

**Issue by pinkisemils** [diwic/dbus-rs#152]
I have to apologize for issuing yet another issue, but there might be another issue with the library. As with #151, I'm still trying to change the network settings. (Or trying to phish you into changing yours).

There seems to be some type garbling going on - NM is now complaining about types not matching, which is indeed very weird because what was received was definitely not changed.
> D-Bus error: The settings specified are invalid: 802-3-ethernet.s390-options: can't set property of type 'a{ss}' from value of type 'a{sv}' (org.freedesktop.NetworkManager.Settings.Connection.InvalidProperty)', libcore/result.rs:1009:5
All other types seem to be correct. Looking through the code, I can't really tell how or why the type information would change or be downgraded from `s` to `v`.

The [example code](https://github.com/pinkisemils/dbus-nm-fail) has been updated to reflect this. I've also added a small python script that achieves what I'm trying to do in Rust.

By the way, great job with the library, and especially with the quick fix for the previous issue :+1:!

**Comment by diwic** [comment]
Yeah, I discovered that too. It's the same with Dicts as it is for Arrays and we could get away with that as long as no one tried to do what you're trying to do :-)
