### ISSUE TITLE
generated code triggers `trivial_casts` warning

### ISSUE THREAD

**Issue by hoodie** [diwic/dbus-rs#154]
Hi there,
I was just trying to use something generated by dbus-codegen in a codebase that has `#[deny(trivial_casts)]` set - the generated code uses casts though.
In #153 I added the  `#[deny(trivial_casts)]` flag, could spend some more time to replace those with coercions but that might have further consequences I guess.

Have a nice day

**Comment by diwic** [comment]
Hi!

So I tried enabling trivial_casts, and it seemed to show up on `as &RefArg` in SignalArgs::append, so given that, it means that your fix was incorrect as it was only applied when `opts.methodtype.is_some`. 

Instead I changed the code generator in the commit above. Could you check if this fixes your problem and if it does not, please supply the full xml used to generate the code and reopen this bug? Thanks!
