### ISSUE TITLE
Default as requirement for tree::DataType?

### ISSUE THREAD

**Issue by untoldwind** [diwic/dbus-rs#155]
Problem: I would like to use a reference to a singleton-like struct holding the overall state of the daemon inside the handler methods of a tree.

My guess was to use my own DataType for this, unluckily this forces me to implement a Default for a reference. My current workaround is to use lazy_static and implement Default for "&'static State" ... that kind of works, but feels terribly wrong.

Is there any other way to pass references to functions in a tree without heavily depending on move closures?

**Comment by diwic** [comment]
First, DataType is not your actual State struct. It's just glue. If your struct is singleton, that's `DataType::Tree`, like this:

    struct MyDataType {}
    impl tree::DataType for MyDataType {
        type Tree = State; // Or 'a State, or Rc<State>, etc...
        type Interface = ();
        type Method = ();
        type Signal = ();
        type ObjectPath = ();
    }

I don't think there will be any `Default` bound on either `MyDataType` or `State` this way (although deriving Default for MyDataType would be trivial). Am I missing something?
