### ISSUE TITLE
How to tell if a message needs a reply

### ISSUE THREAD

**Issue by Timidger** [diwic/dbus-rs#156]
While Oxidizing some C code that uses D-Bus I couldn't find a way to do the equivalent of [`dbus_message_get_no_reply`](https://dbus.freedesktop.org/doc/api/html/group__DBusMessage.html#ga622d051a2e5f578814116a958b240aa4).

How do I determine if a `Message` needs a reply or not?

**Comment by diwic** [comment]
Okay, I just fixed it. Let me know if you need a release. Enjoy!

**Comment by Timidger** [comment]
Thanks, probably not just yet but I will eventually want a release with this.

Side note -- is there a reason your -sys crate doesn't simply use bindgen to generate all the function signatures? It would make it much easier to use since you know what's not wrapped and library users can simply use those functions if they are not wrapped (providing you give access to the underlying raw pointers, like in the `Message `).

**Comment by diwic** [comment]
> Side note -- is there a reason your -sys crate doesn't simply use bindgen to generate all the function signatures?

A long time ago, when I made the first functions, I couldn't get bindgen to work. So that's the historical reason for it. I remember trying it again for some other project a few months ago and it was working but the code was really ugly. 

 > library users can simply use those functions if they are not wrapped

I'd much prefer if it was all wrapped, because the primary point of this library is to provide safe wrappers, and it seems like a potential footgun/UB if one could call functions that interact with the wrappers in an unanticipated way. 

>  (providing you give access to the underlying raw pointers, like in the Message ).

I don't give away raw pointers to Message to anything outside the dbus crate, or do I? (Well, you can currently use transmute to get one, but there is no guarantee that will continue to work.)

**Comment by Timidger** [comment]
> I'd much prefer if it was all wrapped, because the primary point of this library is to provide safe wrappers, and it seems like a potential footgun/UB if one could call functions that interact with the wrappers in an unanticipated way.

It is a footgun, but one users can opt into with `unsafe`, because all of the low level functions would require `unsafe`.

I've historically found that crates that don't expose at least the pointer types of each C struct their wrapping to eventually either:
1) Annoy me if I try to use a function that hasn't been wrapped yet.
2) Annoy me if I try to use that type with another C library but can't because it's all wrapped up in a Rust type that I can't unwrap.

For 1.0 libraries, 1) should never happen. However even after a C wrapper library has become stable 2) can come up fairly frequently.

> I don't give away raw pointers to Message to anything outside the dbus crate, or do I?

Correct you don't, what I meant was for example you _could_ expose that and then I could have used the autogenerated functions from the `-sys` crate with `unsafe` and been on my merry way.

This is just my opinion, one I've formed with struggling with libraries that are of much lower quality than this one (e.g. I found it impossible to get cairo-rs to work with pango exactly because of 2)). Feel free to disregard it.

**Comment by diwic** [comment]
Right. So for 1) the solution is to wrap the function, and your annoyance hopefully leads to a PR, which I consider to be a good thing :-)
For 2), I have yet to see another C library that needs raw pointers to libdbus structs, but if that really happens then I might have to reconsider.

Libdbus is a complex library with more than one edge case and strange corner. It is far from trivial to figure out what other dbus API functions you can call without messing up dbus-rs. That weighs against handing out raw pointers.
