### ISSUE TITLE
u16 values not properly marshalled on s390x

### ISSUE THREAD

**Issue by agrover** [diwic/dbus-rs#158]
On s390x, a big-endian 64 bit architecture, we are seeing nonzero u16 property values being exported as 0, whereas u64 property values are correct.

In looking at the code, `iter_append_basic` in message.rs looks questionable to me:
```
unsafe {
    let p: *const c_void = mem::transmute(&v);
    ffi::dbus_message_iter_append_basic(i, t as c_int, p);
}
```
I think this may cause the problem, because p is a pointer to the entire i64 value. If libdbus expects p to point at a value with size based on t (the type) then it will get the upper zeroed bits rather than the lower significant bits.

@tasleson and I are still working to characterize this behavior a little more, but wanted to open an issue as a heads up, and if you had any thoughts on if you think this spot might be to blame, or another area perhaps. Issues like this are a pain for everyone to detect and fix because big endian is so scarce these days.

**Comment by tasleson** [comment]
@diwic @agrover I added a bit of code to test the one remaining path `iter_get_basic` and it appears to work.  Would it be possible to get a new release published?

Thanks!

**Comment by diwic** [comment]
@tasleson v0.6.4 released now, enjoy!
