### ISSUE TITLE
Make MethodHandler FnMut?

### ISSUE THREAD

**Issue by yohanesu** [diwic/dbus-rs#16]
Hi (again)

Is it possible to make MethodHandler FnMut? I want to be able to change the state of my program from the method callback but this is not possible if Fn is used for the closure..

**Comment by diwic** [comment]
[Fixed!](https://github.com/diwic/dbus-rs/commit/952dbda7814c1f61119eb9f4dce7f0f1a9470970)

**Comment by yohanesu** [comment]
Works perfect now. Thank you!
