### ISSUE TITLE
ObjectManager support

### ISSUE THREAD

**Issue by agrover** [diwic/dbus-rs#17]
Don't know how much work this would be, but just wanted to open this issue to indicate it is desired :smile:

**Comment by diwic** [comment]
Patches welome :-)

Out of curiosity, which part(s) are the most interesting to you, of
 * Client call to GetManagedObjects
 * Server side handling of GetManagedObjects
 * Client side signal handling (InterfacesAdded, InterfacesRemoved)
 * Server side signal handling

There's also no support currently for PropertiesChanged.

**Comment by diwic** [comment]
BTW, do you know a good test service that's installed on most systems by default? E g, I use a call to policykit just to test my properties implementation. Is there a service I can use to test getmanagedobjects too?

**Comment by agrover** [comment]
I'm interested in server side, so 2 and 4 from your list above. Willing to contribute patches in the medium-term :smile:

**Comment by boghison** [comment]
Hi! I have lots of free time and want to help make this better, because I intend to write a crate for a dbus service. What I'd like to help with is Signal support, mostly 2 things:
1) Add capability for the server to send a signal
2) Automatically send PropertiesChanged when a property changes (could be optional)

Has this already been implemented? The documentation doesn't really say much :(

**Comment by diwic** [comment]
> 1) Add capability for the server to send a signal

Hi! To send a signal, just call `Message::new_signal`, add whatever data you want to that message, then send it with `Connection::send`. This can be done for both servers and clients.

 >  2) Automatically send PropertiesChanged when a property changes (could be optional)

This has not been implemented yet. Maybe it needs some thinking too about how to do it in the best way, considering that the property could have been set from both the local/server side and the remote side in some use cases.

 > Has this already been implemented? The documentation doesn't really say much :(

Patches to improve the documentation are also welcome :-) Or if you could point out where you looked for that information but couldn't find it.

**Comment by boghison** [comment]
@diwic It doesn't really seem that hard, only edit the property handlers (server-side) and Props::set() (client-side) to send this signal and for the remote side, just listen for the signal?

**Comment by diwic** [comment]
`Props::set` could send a signal, but would we really want that? `Props::set` sets a remote property, so we would want the remote to send the signal, not us (right)?

And `obj::Property` currently does not know what interface and object path it belongs to, this has to be fixed before it can send a PropertiesChanged signal.

**Comment by diwic** [comment]
Also; the most common use case for PropertiesChanged might be that the server itself changes the value - the value might be read-only for the remote side, but the server might change it and then send a signal.

And, there are four values of EmitsChangedSignal (const, true, false, invalidates). Are you planning to support all four of them?

**Comment by boghison** [comment]
Tbh, I just had a great idea, how about some refactoring?

**Comment by diwic** [comment]
> Tbh, I just had a great idea, how about some refactoring?

Well, any patch that improves the code is welcome, but if you want to do some larger refactoring you might want to discuss it first so we're both on the same page before you write the code?

**Comment by boghison** [comment]
@diwic Could there be a RFC system? :)

**Comment by diwic** [comment]
Just explain what you want to do and how in a github issue (preferably a new one, since this originally was about ObjectManager support).

**Comment by boghison** [comment]
@diwic Yeah, that's what I thought, but I think I want to test some changes first, then open up an issue

**Comment by diwic** [comment]
Hi!

So I was writing a lot of code last weekend, a rewrite of the entire `obj` module. The new `mdisp` module should have both `EmitsChangedSignal` and `ObjectManager` support, but so far I haven't written a test case for it, so would you like to try it out and see if it works?

**Comment by diwic** [comment]
Ok, so the new `tree` module has now been released as dbus v0.2.0 and it has both `EmitsChangedSignal` and `GetManagedObjects` support. Enjoy!
