### ISSUE TITLE
Tree redesign

### ISSUE THREAD

**Issue by diwic** [diwic/dbus-rs#171]
I've been working a bit on dbus-futures lately, but the hardest part remains: To get the server part right. The current tree isn't exactly async friendly and I'm not satisfied with some parts of the design anyway, so I would like to rethink it.

Requirements (or at least nice to haves):

 * Built-in support for standard DBus interfaces: Introspectable, Properties, ObjectManager, including signals

 * Support both async and sync use cases, share common code

 * Support both Send + Sync and non-Send use cases, as some people want their trees parallelizable and others want to use non-Send stuff inside their method handlers

 * Support updates of the tree from within a method call handler

 * Memory efficiency: let's not duplicate interface info for similar object paths

 * And, try to avoid too much of Boxing/Arcing and virtual dispatch. OTOH, making things extremely generic makes code hard to read and compile times long.

 * A method handler needs to access the current message (to check sender etc)

 * No unsafe

Rust modeling:

Is an object path a "struct" and an interface a "trait" implemented for that struct? That seems the most logical modeling, but...

 * Is it the same struct for every object path?

 * Is the object path struct stored in-tree or not?

 * What about signal support, that goes in the other direction? (We have some support with the SignalArgs struct today, probably integrate with that?)

 * How do we support signaling that a property has changed? And what is a property anyway? Is a property list a `Map<String, Box<RefArg>>`, or is it some kind of struct? Or is get and set just functions that are not supposed to have a storage at all?

 * Method signature, same as client side? Or something else, like `&mut self` instead of `&self`? Add a `msg: Message` parameter?

 * Or maybe something ecs-like? Where every object path is an entity and every interface is a component? 

As for writing the code:

 * Manually?

 * With macros?

 * From dbus-codegen?

**Comment by zeenix** [comment]
>     * Support updates of the tree from within a method call handler

What's the use case for this? The only folks I've seen modifying tree on the fly is ofono folks and they do D-Bus wrong in some many ways. The right way to handle a dynamic API is to nicely divide it in smaller interfaces so that an objects can add/remove interfaces as needed. Typically you wouldn't even need to change interfaces on objects on the fly, I'd say.

So unless you've a specific use case in mind, I'd suggest not to worry about this.

>     * No unsafe

I thought you can't implement `Sync` or `Send` w/o unsafe code.

>     * Is it the same struct for every object path?

Maybe I misunderstand here but I'd expect something similar to GDBus:

https://developer.gnome.org/gio/stable/GDBusObjectSkeleton.html

i-e One instance per path+connection on the server side.

>     * Is the object path struct stored in-tree or not?

Based on what i wrote above, I think so.

>     * How do we support signaling that a property has changed?

Well it's a signal like other signals but we should make the emission implicit when user sets the property on the server side.

>     * And what is a property anyway? Is a property list a `Map<String, Box<RefArg>>`, or is it some kind of struct? Or is get and set just functions that are not supposed to have a storage at all?

I'd suggest modelling that after GDBus as well, if possible. i-e apps don't need to know how you manage them internally. Interface just provide generic get/set and generated code provides specific get/set.

>     * Method signature, same as client side? Or something else, like `&mut self` instead of `&self`?

I'd say make both `&mut self` and `& self` possible, though different methods on the tree. Having `mut` where it's not needed is not nice and compiler rightfully warns about it.

>  Add a `msg: Message` parameter?

I think so, yes and maybe even a more specific API, like https://developer.gnome.org/gio/stable/GDBusMethodInvocation.html

>     * Or maybe something ecs-like? Where every object path is an entity and every interface is a component?

No clue what that is but doesn't sound too attractive to me gdbus- and Vala-spoiled mind. :)

> As for writing the code:
> 
>     * Manually?
> 
>     * With macros?
> 
>     * From dbus-codegen?

For a good DBus crate, I'd expect all of them to be possible but I'd focus first on manual and dbus-codegen first. For Geoclue, I really want to use `dbus-codegen` as that's what i already do through `gdbus-codegen`.

**Comment by diwic** [comment]
> Very sorry for the late reply but I've a lot to learn in my new job. 

No worries, congrats on the new job :-)

> > ```
> > * Support updates of the tree from within a method call handler
> > ```
> 
> What's the use case for this? The only folks I've seen modifying tree on the fly is ofono folks and they do D-Bus wrong in some many ways. The right way to handle a dynamic API is to nicely divide it in smaller interfaces so that an objects can add/remove interfaces as needed. Typically you wouldn't even need to change interfaces on objects on the fly, I'd say.
> 
> So unless you've a specific use case in mind, I'd suggest not to worry about this.

I remember that it has come up in the past. It's more like, if we don't think about this, I'm sure someone would need it badly... that said, it's possible we can defer the updates to after the method call handler has finished, as long as there is some supported way to do it.

> 
> > ```
> > * No unsafe
> > ```
> 
> I thought you can't implement `Sync` or `Send` w/o unsafe code.

It's more about restricting yourself to types that are already send and sync. We shouldn't need to create new primitives for synchronisation, but use existing ones.

> 
> > ```
> > * Is it the same struct for every object path?
> > ```
> 
> Maybe I misunderstand here but I'd expect something similar to GDBus:
> 
> https://developer.gnome.org/gio/stable/GDBusObjectSkeleton.html
> 
> i-e One instance per path+connection on the server side.

GObject has support for inheritance, so every type of object that is in the tree inherits from GDBusObject. That's how they manage different types of objects in the same tree. But Rust does not have inheritance for objects, because we don't even have objects...we have structs and traits. So we can't do the same unless we implement something as complex as GObject, which I prefer not to do. :-)

**Comment by diwic** [comment]
> > ```
> > * How do we support signaling that a property has changed?
> > ```
> 
> Well it's a signal like other signals but we should make the emission implicit when user sets the property on the server side.

Which means that the properties need to be stored inside the tree as well, otherwise we can't know when they change as a result of something happening on the server...

> 
> > ```
> > * And what is a property anyway? Is a property list a `Map<String, Box<RefArg>>`, or is it some kind of struct? Or is get and set just functions that are not supposed to have a storage at all?
> > ```
> 
> I'd suggest modelling that after GDBus as well, if possible. i-e apps don't need to know how you manage them internally. Interface just provide generic get/set and generated code provides specific get/set.

I'm not sure how GDBus handles properties. After skimming through the documentation, I didn't find anything like GDBusProperty, just GDBusPropertyInfo which looked mostly like introspection info.

GObject has properties but I don't want to make anything that complex...

> 
> > ```
> > * Method signature, same as client side? Or something else, like `&mut self` instead of `&self`?
> > ```
> 
> I'd say make both `&mut self` and `& self` possible, though different methods on the tree. Having `mut` where it's not needed is not nice and compiler rightfully warns about it.

So when dbus-codegen generates properly typed methods, should there be a global switch - which applies to all code generated - which determines whether the methods take `&self` or `&mut self`? I mean, probably you want some methods taking &self and others taking &mut self, but codegen has no idea which ones need &mut self... 

> 
> > Add a `msg: Message` parameter?
> 
> I think so, yes and maybe even a more specific API, like https://developer.gnome.org/gio/stable/GDBusMethodInvocation.html
> 
> > ```
> > * Or maybe something ecs-like? Where every object path is an entity and every interface is a component?
> > ```
> 
> No clue what that is but doesn't sound too attractive to me gdbus- and Vala-spoiled mind. :)

It's about memory management. GObject is reference counted, IIRC. And C always have interior mutability for everything. Whereas Rust needs Rc/RefCell or Arc/Mutex to accomplish the same thing.
ECS is an alternative to that, where you have one big object owning everything else, but I'm not sure it's the right option here.

**Comment by zeenix** [comment]
> GObject has support for inheritance, so every type of object that is in the tree inherits from GDBusObject. That's how they manage different types of objects in the same tree. But Rust does not have inheritance for objects, because we don't even have objects...we have structs and traits. 

Yeah, I realize that but I didn't mean we should have the same API, just as similar as possible. GDBusObject is an interface btw, which maps nicely to traits in Rust.

> So we can't do the same unless we implement something as complex as GObject, which I prefer not to do. :-)

I don't think we need to do that to have a similar API.

> I'm not sure how GDBus handles properties. After skimming through the documentation, I didn't find anything like GDBusProperty, just GDBusPropertyInfo which looked mostly like introspection info.

That's cause normal gobject properties are used. Since GObject properties are dynamic, they can be added at runtime. You might want to have a look a the generated code from gdbus-codegen for server-side. Geoclue would be one place to look for example.

> So when dbus-codegen generates properly typed methods, should there be a global switch - which applies to all code generated - which determines whether the methods take `&self` or `&mut self`? I mean, probably you want some methods taking &self and others taking &mut self, but codegen has no idea which ones need &mut self...

Good point. I guess you'll want to provide an option like '--mutable-methods=Iface1.Xy,Iface2.Zx'?

**Comment by diwic** [comment]
I've mostly thought of how to dispatch a method and come up with this data structure:

    pub struct Tree {
        paths: BTreeMap<PathName, Path>
    }
    
    pub struct Path {
        interfaces: Vec<Box<Iface>>
    }
    
    pub trait Iface: Any + 'static {
        fn call_method_ref(&self, &Path, &Tree, &Message) -> CallRefResult;
        // Add methods for e g introspection
    }
    
    pub enum CallRefResult {
        Called,
        Mut(fn (&mut Iface, &Message)),
        MutPath(fn (&mut Path, &Message)),
        MutTree(fn (&mut Tree, &Message)),
        Unknown,
    }

Method dispatch will then be:
 1) Find the path by name
 2) Find the interface by name
 3) Call call_method_ref. The function will contain a (possibly autogenerated) match on the method name and then call the method, if the method is read-only. If the method needs mutable access to path or tree then return a function pointer to that method. If the method needs mutable self, it will return a function pointer to that, but due to Rust's object safety rules, it will first have to be downcasted.

**Comment by diwic** [comment]
Or maybe like this:

    pub struct Tree {
        paths: BTreeMap<PathName, Path>,
        ifaces: BTreeMap<IfaceName, Vec<MethodInfo>>,
    }
    
    pub struct Path {
        ifaces: Vec<Box<Iface>>
    }
    
    pub trait Iface: Any + 'static {
        fn name() -> IfaceName<'static> where Self: Sized;
        fn methods() -> Vec<MethodInfo> where Self: Sized;
        // signals, props
    }
    
    pub struct MethodInfo {
        name: MemberName,
        handler: MethodFn,
        // args
    }
    
    pub enum MethodFn {
        Ref(fn (&Iface, &Path, &Tree, &Message)),
        Mut(fn (&mut Iface, &Message)),
        MutPath(fn (&mut Path, &Message)),
        MutTree(fn (&mut Tree, &Message)),
    }

It ties the method pointer to the introspection data, which removes one footgun. OTOH, all methods (also readonly ones) need to downcast if they need access to self.

**Comment by zeenix** [comment]
Seems fine but what's the point of `ifaces` in `Tree` when `Path` has it?

**Comment by zeenix** [comment]
BTW I got gsoc students interested in [oxidizing of geoclue idea](https://gitlab.freedesktop.org/geoclue/geoclue/issues/103) so I need to figure out how to proceed in the short run at least. Options I see:

1. Use current codegen in sync mode.
1. Don't codegen for now but rather just go for the new futures crate.
1. Same as above but use `dbus-tokio` crate.

Which approach would you suggest?

**Comment by diwic** [comment]
If you want production quality code and within a certain time frame, I would probably go for option 1. The new futures depend on nightly Rust and things are still in flux there. And dbus-tokio is a stopgap until things are no longer in flux.

But it also depends on how bad you need async, I suppose.

**Comment by diwic** [comment]
> Seems fine but what's the point of ifaces in Tree when Path has it?

Good call. It's likely that many paths share the same interface(s) because they are of the same type/class/etc. The question is how to best make use of that fact in order to improve performance and save memory. But maybe it isn't necessary...at least not at this point.

**Comment by diwic** [comment]
Maybe something like this is better.

    pub trait Iface: Any + 'static {
        fn info(&self) -> Option<&IfaceInfo> { None }
    }

    pub struct IfaceInfo {
        name: IfaceName<'static>,
        methods: Vec<MethodInfo>,
        // signals, props
    }

    impl Tree {
        pub fn register_iface<I: Iface>(&mut self, info: IfaceInfo) { /* */ }
    }

The normal case is that all instances of the same `Iface` implementing struct shares the same `IfaceInfo`. If so, then one can just call `register_iface` once and that fast-path will be used. If not, then there is a fallback where the path searches for the interface by calling `info` on each one of them.

**Comment by zeenix** [comment]
> If you want production quality code and within a certain time frame, I would probably go for option 1.

Ok, I'll do that. Since I'll be designing the rest of the code around tokio and futures, I wondered if there is an easy way to run the loop nicely in a tokio task even if the service implementation is sync, or am I better off just isolating the D-Bus service in it's own thread that communicates with rest of the code through channels?

**Comment by diwic** [comment]
> an easy way to run the loop nicely in a tokio task

If so, you need to poll it repeatedly for incoming messages, i e, on a timer every x ms call `connection.incoming(1)`

**Comment by diwic** [comment]
Another option though is to use dbus-codegen to generate a "sync" tree but still use dbus-tokio's `AConnection`?

**Comment by zeenix** [comment]
> Another option though is to use dbus-codegen to generate a "sync" tree but still use dbus-tokio's `AConnection`?

Aha, that sounds like the best option. Didn't think this was possible. Doesn't that imply that I've to use a `ATree`? `dbus-codegen` will give me a `Tree`.

**Comment by diwic** [comment]
> > Another option though is to use dbus-codegen to generate a "sync" tree but still use dbus-tokio's `AConnection`?
> 
> Aha, that sounds like the best option. Didn't think this was possible. Doesn't that imply that I've to use a `ATree`? `dbus-codegen` will give me a `Tree`.

It depends on where you need the asyncness.

`AConnection` means that receiving (and sending) messages is non-blocking.

`ATree` means that method handlers can be non-blocking.

Because both just deal with messages, they can be combined with their blocking versions the way you see fit.

**Comment by zeenix** [comment]
> It depends on where you need the asyncness.

In the beginning I just need integration with tokio so i can easily run the connection/loop with tokio. The method implementation remain sync for now.

> Because both just deal with messages, they can be combined with their blocking versions the way you see fit.

But how? `Tree.set_registered` takes a `Connection`, not `AConnection`.

**Comment by diwic** [comment]
> But how? Tree.set_registered takes a Connection, not AConnection.

`AConnection` takes a `Rc<Connection>`, so you can just clone the `Connection` and send one clone into `AConnection` and keep another clone around for when you want to call `set_registered`.

**Comment by diwic** [comment]
As of yesterday's commit, we can now have type-safe method handlers in the new design, without using code generation, which is quite cool:

        struct Score(u16);

        cr.register::<Score,_>("com.example.dbusrs.crossroads.score")
            .method("Hello", ("sender",), ("reply",), |score, _, (sender,): (String,)| {
                assert_eq!(score.0, 7u16);
                Ok((format!("Hello {}, my score is {}!", sender, score.0),))
            })
            .prop_ro("Score", |score, _| {
                assert_eq!(score.0, 7u16);
                Some(score.0)
            });

This registers the struct `Score` with the interface `com.example.dbusrs.crossroads.score` in the interface registry. So every time someone calls the interface `com.example.dbusrs.crossroads.score` on a path that has a `Score` in it, these methods/properties will be dispatched (if method names match, of course). 

The Rust compiler infers the D-Bus type signature of `method`: we can see that the third argument is a single-tuple `String`, which means that the method takes one input argument. Likewise the return value is a single-tuple `String`, so the method has one output argument as well. (For introspection, the name of the arguments are `sender` and `reply`.)

The single tuples are a bit funny but they are necessary to distinguish between the case of having several arguments and the one having one argument which is a struct.

**Comment by zeenix** [comment]
Looks good.

> So every time someone calls the interface `com.example.dbusrs.crossroads.score` on a path that has a `Score` in it, these methods/properties will be dispatched (if method names match, of course).

This part doesn't sound very good to me. I think the path should be specified or at least the prefix.

**Comment by diwic** [comment]
> > So every time someone calls the interface `com.example.dbusrs.crossroads.score` on a path that has a `Score` in it, these methods/properties will be dispatched (if method names match, of course).
> 
> This part doesn't sound very good to me. I think the path should be specified or at least the prefix.

The part "a path that has a Score in it" might need further explanation. Consider this code:

        let mut pdata = PathData::new();
        pdata.insert_mut(Score(7u16));
        cr.insert("/", pdata);

This is the part that actually makes sure that there is a path`/` in the tree and what interfaces it contains. In this case it only contains the interface `com.example.dbusrs.crossroads.score` (and potentially standard stuff such as introspection and properties). 

I could add some kind of path-matching when you add an interface, but I'm not sure what downside the current design has, could you elaborate?

**Comment by diwic** [comment]
> IIUC, you're assuming a pattern to the path, which isn't mandated by D-Bus. There could be multiple different objects with different interfaces on paths containing Score.

I'm not sure what a "pattern" is in this context? The structs inside `PathData` determine which interfaces the path implements. 

An important thing to remember is memory consumption. I can't have one "add_interface" per path, because then I would run into bug https://github.com/diwic/dbus-rs/issues/47 again, and that took substantial work to fix. The fix then was to start refcounting things, which comes with its own problems, so this new design avoids that in an elegant way, if I may say so myself 🙂

**Comment by zeenix** [comment]
> I can't have one "add_interface" per path, because then I would run into bug #47 again

Maybe you can have it the other way around: Add paths to an interface?

**Comment by zeenix** [comment]
> I'm not sure what a "pattern" is in this context? The structs inside `PathData` determine which interfaces the path implements.

Perhaps I'm just not understanding right. I understood that your example method will be called for all calls on this specific interface for *any* path that contains "Score" in it so if my path is `/no/special/name`, this won't work, while it really should. Or did I misunderstand?

**Comment by diwic** [comment]
`Score` is just a struct and it's connected to the interface name `"com.example.dbusrs.crossroads.score"` via the `register` function. That is in turn connected to the paths via pathdata like:

    let mut pdata = PathData::new();
    pdata.insert_mut(Score(7u16));
    cr.insert("/no/special/name", pdata);

You can see the `PathData` as the link between paths and interfaces, selecting which paths implement which interfaces.

**Comment by zeenix** [comment]
> You can see the `PathData` as the link between paths and interfaces, selecting which paths implement which interfaces.

Ah ok. Thanks for explaining again. :)

**Comment by diwic** [comment]
Thanks for reviewing!

**Comment by Spferical** [comment]
Hi! There seems to have been [exciting progress](https://github.com/diwic/dbus-rs/commit/8a96b4697389e145afaa351f1a84dce5738e9d36) recently. Is `dbus-crossroads` nearing a release or is the design still in flux?

Context: I want to help update [bluster](https://github.com/dfrankland/bluster) (currently using `dbus-tokio` 0.3) to async/await, but old 0.3 `dbus-tokio` requires a tokio 0.1 runtime to be passed in, and current `dbus-tokio` lacks an async tree. I would be happy to help test/etc as needed.

**Comment by diwic** [comment]
@Spferical 

 > Is dbus-crossroads nearing a release or is the design still in flux?
 > I would be happy to help test/etc as needed.

Hi, nice to see some interest!
I think the design is getting to where I want it, but indeed it would be very good if someone else were to try it out to see if the design is usable!

Two pieces are still missing:
 * Sending signals when properties change or paths/interfaces are added/removed
 * Modifying the tree, e g removing paths, adding/removing interfaces to paths and so on

The latter is mostly straight forward, I just need to sit down and write the methods. I ran into an issue on the former because `MsgArg` is not `Send`, but I'll figure out some way to resolve it.

**Comment by Spferical** [comment]
Thank you for the summary! I think what's there might be enough for my purposes -- I will try it out.

**Comment by diwic** [comment]
@Spferical and others:

So I finished up some loose ends and while not all features are there yet, it should be good enough for what it can do, so I have now released dbus-crossroads 0.1! 

https://docs.rs/dbus-crossroads/
https://github.com/diwic/dbus-rs/tree/master/dbus-crossroads

Go ahead and try it and see if you like it :-D

**Comment by Spferical** [comment]
Looks quite nice so far! I realized I need ObjectManager support for my use case, but I see that's planned. Handling errors in `method_with_cr_async` is also slightly awkward -- I ended up writing some code like:
```rust
b.method_with_cr_async("Foo", (), (), move |mut ctx, cr, ()| {
    async {
        // do things, return a Result<(), MethodErr>
    }
    .then(|result| async move {
        match result {
            Ok(_) => {
                ctx.reply_ok(());
            }
            Err(e) => ctx.reply_err(e),
        };
        std::marker::PhantomData::<()>
}
```
But that's probably just a matter of more helper functions. (It might also help if both `ctx.reply_ok` and `ctx.reply_err` returned the same thing? Or if all the `PhantomData`s in signatures could be removed.) Otherwise, I liked to see how e.g. inferred `read`/`write` flags cut down on boilerplate!

**Comment by diwic** [comment]
> But that's probably just a matter of more helper functions.

Yup, I've added a `reply_result` one now.

 > Or if all the PhantomDatas in signatures could be removed.

The PhantomData is what makes it possible for introspection to show what type your method is returning, so I think it's quite useful.

 > I realized I need ObjectManager support for my use case, but I see that's planned.

Okay, I've noted that it's needed :-)

**Comment by diwic** [comment]
@Spferical With today's commits ObjectManager should work. You need to call `set_object_manager_support` if you want signals to be spontaneously sent when you add and remove paths. The rest should be self explanatory, I hope.

I also changed `reply_result` to just `reply`. Seems more analogous to synchronous methods, which return Result.

**Comment by diwic** [comment]
And with today's release of dbus-crossroads v0.2.1 I think I'm ready to close this issue! :-D
