### ISSUE TITLE
dbus-codegen: Custom namespace option

### ISSUE THREAD

**Issue by zeenix** [diwic/dbus-rs#174]
Just like [gdbus-codegen](https://developer.gnome.org/gio/stable/gdbus-codegen.html), this tool should allow specifying the prefix using `--interface-prefix` and `--rust-namespace` options. 

It should also support something equivalent to `org.gtk.GDBus.C.Name` annotations but that's not as important.

**Comment by diwic** [comment]
I'm not sure what this means, since the generated code is likely to end up in its own module, that will automatically give it a namespace, because in Rust modules are namespaces? Adding prefixes is in general seen as non-Rustic.

Could you elaborate?

**Comment by zeenix** [comment]
I'm talking about the dbus namespaces that end up being part of the identifiers. For example, code generated for `org.freedesktop.GeoClue2.Client` interface, I get `OrgFreedesktopGeoClue2Client` and `org_freedesktop_geo_clue2_client_server`. I'd want to be able to tell the tool to name them `GClueClient` and `gclue_client_server` instead. This is currently achieved with C code generator with:

```
gdbus-codegen --interface-prefix org.freedesktop.GeoClue2. --c-namespace GClue
```

**Comment by diwic** [comment]
To remove prefixes like 'org.freedesktop.GeoClue2.' is already possible (check the 'skipprefix' option), and the C namespace option seems non Rustic, i e, you should put the generated code i gclue.rs instead. Does that make sense?

**Comment by zeenix** [comment]
> To remove prefixes like 'org.freedesktop.GeoClue2.' is already possible (check the 'skipprefix' option)

True. I didn't see that either. :)

> and the C namespace option seems non Rustic, i e, you should put the generated code i gclue.rs instead.

I already generate code for each D-Bus interface in a separate module/file. But you're right, I'm thinking in terms in C here.
