### ISSUE TITLE
dbus-codegen: Implement introspection for generated interfaces

### ISSUE THREAD

**Issue by zeenix** [diwic/dbus-rs#175]
Users of codegen tool should not need to worry about implementing introspection since they're already providing the XML that needs to be returned from interface: https://dbus.freedesktop.org/doc/dbus-specification.html#introspection-format

**Comment by diwic** [comment]
This is implemented since years back, just add [introspectable()](https://docs.rs/dbus/0.6.4/dbus/tree/struct.ObjectPath.html#method.introspectable) to the paths you want to be introspectable?

**Comment by zeenix** [comment]
> This is implemented since years back, just add [introspectable()](https://docs.rs/dbus/0.6.4/dbus/tree/struct.ObjectPath.html#method.introspectable) to the paths you want to be introspectable?

Oh, I missed that. I just grepped for 'introspect' in generated dbus and assumed it's not supported since search didn't yield any results.
