### ISSUE TITLE
Issues build with elongind-dbus

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [diwic/dbus-rs#176]
I am an unable to build [i3-status-rust](https://github.com/greshake/i3status-rust),
While building I get an error 
```rust
   Compiling libdbus-sys v0.1.3
   Compiling chrono-tz v0.4.1
error: failed to run custom build command for `libdbus-sys v0.1.3`
process didn't exit successfully: `/home/doc/Downs/i3status-rust/target/debug/build/libdbus-sys-cbdaf9b1ed5193ba/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1 >= 1.6\"", cause: Os { code: 2, kind: NotFound, message: "No such file or directory" } }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I am building on Void Linux (a non-systemd distro) with dbus-elogind(v 1.12.12) installed.
[i3-status-rust](https://github.com/greshake/i3status-rust) requires a minimum version of 1.6

I have tried installing dbus(v 1.12.12) and got the same results as with dbus-elogind

**Comment by diwic** [comment]
I'm not familiar with "void linux", but what is the output if you run 

   pkg-config --libs --cflags dbus-1 >= 1.6

...in a terminal? Do you have both development headers of libdbus installed as well as `pkg-config`? Maybe this can give you a hint of what needs installing.

**Comment by Th3Whit3Wolf** [comment]
Well this is embarassing... It appears I forgot to install pkg-config and jumped to conclusions.
Sorry for wasting your time and thank you for responding so quickly!
