### ISSUE TITLE
dbus-tokio: AMethodResult

### ISSUE THREAD

**Issue by LinkTed** [diwic/dbus-rs#178]
Hi,
is there any reason why the `AMethodResult` struct is private. I need the struct in my code because I implement my own `ATreeServer` struct based on the current `ATreeServer`. So if there is no reason to keep it private, could you please make the struct public? 

Thank you for your attention

**Comment by diwic** [comment]
It was a long time since I looked at that code so I don't remember clearly, but if you implement your own `ATreeServer`, how come you don't implement your own `AMethodResult` as well?

**Comment by LinkTed** [comment]
Yes, you are right.
