### ISSUE TITLE
What is the use of the `DataType` trait?

### ISSUE THREAD

**Issue by nikonthethird** [diwic/dbus-rs#179]
I am implementing a DBus service that has to mutate its state, so currently I'm using `MTFnMut` for this purpose. And I am assuming that is the primary purpose of MTFnMut anyway, to be able to capture mutable references in DBus methods.

On the other hand, there is the associated data `DataType` trait, which is also present everywhere in the tree. But the only use I could find for it is to access the data using the `get_data` methods on the various structs of the tree.

Is that really all? I wonder if I'm missing something and I have a hard time understanding what the use is, since all examples I could find always use `()` for the data type.

**Comment by diwic** [comment]
So the idea is that if you have many paths with the same interfaces, then you could store something "per path" in the tree, and you would access that with `get_data`. That's the most used scenario I believe. And then I added so you could store something per interface, per method or whatever as well, but I don't know if anybody uses it.

In hindsight, I'm not very happy with how the design ended up. I'm currently designing a successor to the tree module, but it's yet far from usable. There things will work differently and, hopefully, more intuitive.

**Comment by diwic** [comment]
The [adv_server example](https://github.com/diwic/dbus-rs/blob/master/dbus/examples/adv_server.rs) stores a struct per object path, if you're helped by an example.

**Comment by nikonthethird** [comment]
Thank you, that example helped a lot! That is also exactly what I need for my service!

I did not realize that the type implementing the trait and the types referenced in the implementation do not have to be the same type.
