### ISSUE TITLE
Panic when pkg-config not installed

### ISSUE THREAD

**Issue by david-mcgillicuddy-moixa** [diwic/dbus-rs#186]
When compiling on osx, `pkg-config` is a dependency but is not listed in the README's dependency section. Just trying to build the library results in:

```
   Compiling libdbus-sys v0.1.5
error: failed to run custom build command for `libdbus-sys v0.1.5`
process didn't exit successfully: `/Users/david/code/rust_monorepo/battery-dbus/target/debug/build/libdbus-sys-ef335b31aab97122/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1 >= 1.6\"", cause: Os { code: 2, kind: NotFound, message: "No such file or directory" } }', src/libcore/result.rs:997:5
```
and then after a `brew install pkg-config` it works without issue.

I suspect that this is the same issue as https://github.com/diwic/dbus-rs/issues/118

**Comment by diwic** [comment]
Sure, I can add a short notice about installing pkg-config.

But out of curiousity, does OS X have D-Bus, or are you cross compiling?

**Comment by david-mcgillicuddy-moixa** [comment]
I've had no issues (so far) using the version on homebrew: https://formulae.brew.sh/formula/dbus
and following these tutorials: https://github.com/zbentley/dbus-osx-examples/tree/master/installation

Happily using the session bus, I imagine the system bus might fail since it doesn't exist but have not actually tried it.

**Comment by david-mcgillicuddy-moixa** [comment]
Also (I might as well make a note here even just for myself) a number of linux services expect `DBUS_SESSION_BUS_ADDRESS` to be set and on osx you can set that with:
```
DBUS_SESSION_BUS_ADDRESS="unix:path=$(launchctl getenv DBUS_LAUNCHD_SESSION_BUS_SOCKET)"
```
