### ISSUE TITLE
Support for accepting messages with NULL interface header?

### ISSUE THREAD

**Issue by david-mcgillicuddy-moixa** [diwic/dbus-rs#188]
Hello,

I'm trying to interact with python code that sends its messages with no interface header. This is supported by the python dbus library: https://dbus.freedesktop.org/doc/dbus-python/dbus.lowlevel.html#dbus.lowlevel.MethodCallMessage
> interface is the interface qualifying the method name, or None to omit the interface from the message header.

Is this supported at all in the library? I spent a while looking and couldn't find anything, the `ObjectPath::handle` method just returns an error if there is no interface: https://github.com/diwic/dbus-rs/blob/442b3310feaf5dde827e1cf1ffb1348ddca4bc09/dbus/src/tree/objectpath.rs#L244

I'm not sure what the best solution would be, because the method are contained in the interface - so it's not just a matter of not verifying the interface but still passing the message to the right place. Perhaps a special null interface that you can register with? I'm pretty sure that the dbus server still has an interface (there is not actually an object with a null interface).

I'm not particularly happy about having to support this weird and seemingly non-spec conformant use case but until I can get the client to change their code I need to work out something on the server side  :)

**Comment by diwic** [comment]
Funny, actually the interface is optional for method calls, according to the spec. But I've never seen it in the wild.

I wonder how this would look like w r t introspection, but that usually comes from servers, not clients. Do you have introspection XML to show here?

The short-term workaround I can think of is to intercept the message before it goes into tree.handle, and then dispatch it the way you see fit. Long term we should support this to be compliant with the spec.

**Comment by david-mcgillicuddy-moixa** [comment]
Me neither! Unfortunately the introspection XML is almost certainly proprietary and I don't think I can share it here.
What is interesting is that the python client implementation calls what looks to be a method from the C bindings: dbus_message_get_interface [here](https://github.com/freedesktop/dbus-python/blob/master/dbus_bindings/message.c#L78) so I don't know if that's available to you or not.

I came up with a different workaround by changing some options on the client, so I don't really need this directly any more - although it would be nice to get rid of the client workaround at some point.

I'm pretty sure that the server still registers an interface - the parameters [here](https://dbus.freedesktop.org/doc/dbus-python/dbus.decorators.html#dbus.decorators.method) are 
> dbus_interface : str
> Name of a D-Bus interface

so not nullable on the server side. It's just that the client can choose to ignore them somehow, I have no idea what the routing would look like.

**Comment by diwic** [comment]
> Unfortunately the introspection XML is almost certainly proprietary

I'm not interested in the names, merely the structure of it. Should the "null" interface not show up in introspection at all? Or be an `interface` without the `name` key? Or something else?

 > dbus_message_get_interface here so I don't know if that's available to you or not.

`Message::interface()` is a wrapper around dbus_message_get_interface.

**Comment by david-mcgillicuddy-moixa** [comment]
The root xml looks like:
```
<node>
	<interface name="org.freedesktop.DBus.Introspectable">
		<method name="Introspect">
			<arg name="data" direction="out" type="s"/>
		</method>
	</interface>
	<interface name="org.freedesktop.DBus.Properties">
		<method name="Get">
			<arg direction="in" type="s" name="interface"/>
			<arg direction="in" type="s" name="property"/>
			<arg direction="out" type="v" name="value"/>
		</method>
	</interface>
	<interface name="com.victronenergy.BusItem">
		<method name="MyMethod">
			<arg direction="out" type="s" name="myarg"/>
		</method>
	</interface>
	<node name="Path1"/>
</node>
```
Where `/Path1` is accessable with a None interface and then the introspection from `/Path1` is:
```
<node>
	<interface name="org.freedesktop.DBus.Introspectable">
		<method name="Introspect">
			<arg name="data" direction="out" type="s"/>
		</method>
	</interface>
	<interface name="org.freedesktop.DBus.Properties">
		<method name="Get">
			<arg direction="in" type="s" name="interface"/>
			<arg direction="in" type="s" name="property"/>
			<arg direction="out" type="v" name="value"/>
		</method>
	</interface>
	<interface name="com.MyInterface">
		<method name="MyMethod">
			<arg direction="out" type="s" name="myarg"/>
		</method>
	</interface>
</node>
```

and then calling sending from python a:
```
dbus.lowlevel.MethodCallMessage('com.my_dest', '/Path1', None, 'MyMethod')
```
The response from `com.MyInterface.MyMethod` is returned, as far as I can tell identical to

```
dbus.lowlevel.MethodCallMessage('com.my_dest', '/Path1', 'com.MyInterface', 'MyMethod')
```
In summary: either 1) the interface shows up with its name as normal and the service chooses to route it to the `com.MyInterface` interface anyway, or 2) there is an entirely different interface that is hidden from introspection that is the null interface.

I think 1) is a lot more likely that it's entirely dependent on the service implementation that when a message comes in without an interface it chooses to route it in a particular way, based on the node name and the method.

**Comment by diwic** [comment]
Thanks! So something like the commit just pushed should solve it then. Feel free to submit a test case for it if you want to help out further. 🙂

**Comment by david-mcgillicuddy-moixa** [comment]
Just to confirm that this change is working as intended!

**Comment by diwic** [comment]
Thanks!
