### ISSUE TITLE
Forcing ObjectPaths to be registered

### ISSUE THREAD

**Issue by KillingSpark** [diwic/dbus-rs#189]
Hi,
I use your library to implement a dbus-server for a password-manager. First of all, thanks for all the work!

In ran into a problem though, the default message-callback (that i replaced with replace_message_callback) always returns "false" to libdbus for messages that are no signals. This results in libdbus getting confused if an objectpath that I handle correctly is not registered with libdbus. See below for why it is inconvenient for me to register all possible names with libdbus.
Libdbus sends an "Error org.freedesktop.DBus.Error.UnknownMethod: Method "OpenSession" with signature "" on interface "org.freedesktop.Secrets.Service" doesn't exist" instead of the message I generate in my handler. Which also lead me to beleive something else was wrong because it didnt complain about a missing object but about missing methods... But that seems to be weirdness on the libdbus side, not yours.

One solution I see with my limited knowledge of the codebase:
Put some logic into the default handler to allow for filtering of messages like "Objectpathes with prefix "aaa/bb/cccc" will be handled and the callback returns "true" to 

Or at least mention this limitation somewhere and point to the example in the "replace_message_callback" which is what I used: 
```
    let mut old_cb = c.replace_message_callback(None).unwrap();
    c.replace_message_callback(Some(Box::new(move |conn, m| {
        let my_b = match &m.headers() {
            (_,path,_,_) => {
                match path {
                    None => false,
                    Some(path) => {
                        path.starts_with("/org/freedesktop/Secrets")
                    }
                }
            },
        };
        let b = old_cb(conn, m);
        
        return my_b || b;
    })));
```

In my manager I do not have all the objectpathes that the [secret-storage API](https://freedesktop.org/wiki/Specifications/secret-storage-spec/secrets-api-0.1.html#eggdbus-interface-org.freedesktop.Secrets.Service) includes.

I can only register the individual secrets once the repo has been unlocked.

That means I need to register objectpaths after some interaction in  the handlers. I dont use the tree because the API does not map well with that amount of dynamic changes, which is why i dont automatically register all objects with libdbus.

**Comment by diwic** [comment]
Hi,

You can register object paths with libdbus without using the tree, using Connection::register_object_path function.

If you for some reason

**Comment by KillingSpark** [comment]
Replacing the callback works, so I guess that's fair enough.

I would love a small section in the Readme about using the library without the tree, that mentions the need to either register all objects with the connection, or replace the callback. I could try to come up with a text for this if you'd like me to. I can probably provide a simplified version of my handler for your examples directory that showcases this too.

**Comment by diwic** [comment]
Hi,

A PR with an example showcasing something would be welcome, and maybe just a short sentence in the Readme saying that the example exists. Not registering all paths with libdbus would be quite an edge case IMO so the example should explain why this is not an option.

Thanks!

**Comment by diwic** [comment]
On second thought, I'm working on a new version of the connection component where this would work very differently. So your example may become obsolete some time from now. For that reason maybe it's a waste of time for you to write that PR.

**Comment by KillingSpark** [comment]
I see, I guess the issue is somewhat irrelevant then. Thanks for your time though :)
