### ISSUE TITLE
Why arg_append_f64 have separate impl

### ISSUE THREAD

**Issue by a1ien** [diwic/dbus-rs#194]
For base arg we have 
https://github.com/diwic/dbus-rs/blob/95560dfddf6b2c770b398b13dc447a83da88c66d/dbus/src/arg/basic_impl.rs#L10
But for f64 we have separate function
https://github.com/diwic/dbus-rs/blob/95560dfddf6b2c770b398b13dc447a83da88c66d/dbus/src/arg/basic_impl.rs#L26
Why?

**Comment by diwic** [comment]
It was a leftover since `arg_append_basic` wasn't generic. Fixed now.
