### ISSUE TITLE
What do you think about replacing timeout_ms on the std::time::Duration

### ISSUE THREAD

**Issue by a1ien** [diwic/dbus-rs#195]
In the code timeout is used as i32 value. But meybe we can cange api to use std::time::Duration?

**Comment by diwic** [comment]
Sounds good, we should at least do this for the `blocking` module. For `ffidisp` let's leave it unchanged for backwards compatibility. Do you want to make a PR?

**Comment by a1ien** [comment]
Ok. I make PR. But 0.7 already have breaking changes. Why not change also in ffidisp?

**Comment by diwic** [comment]
I think of `ffidisp` primarily as a legacy module for people who don't want to migrate to `blocking` at this point. All they have to do then is to change imports.

**Comment by a1ien** [comment]
Ohh. I forgot about arg::messageitem::Props also replace?

**Comment by diwic** [comment]
Naah, I should probably deprecate `Props` altogether instead...
