### ISSUE TITLE
Process requests asynchonously

### ISSUE THREAD

**Issue by manuels** [diwic/dbus-rs#20]
I have requests that take a while until they are processed and a response can be given.
AFAIK, you would have to spawn a new process for each request to keep the dbus interface responsive while processing one request, so something like

                for n in conn.iter(1000) {
                        thread::spawn(|| {
                                match n {
                                        ConnectionItem::MethodCall(mut m) => {
                                                        o.handle_message(&mut m);
                                        },
                                        _ => (),
                                }
                        });
                }

However, `n` cannot be sent to another thread:

    src/dbus_service.rs:51:4: 51:17 error: the trait `core::marker::Send` is not implemented for the type `alloc::rc::Rc<dbus::objpath::IObjectPath<'_>>` [E0277]
    src/dbus_service.rs:51 			thread::spawn(|| {
                           			^~~~~~~~~~~~~
    note: in expansion of for loop expansion
    src/dbus_service.rs:50:3: 59:4 note: expansion site
    src/dbus_service.rs:51:4: 51:17 note: `alloc::rc::Rc<dbus::objpath::IObjectPath<'_>>` cannot be sent between threads safely
    src/dbus_service.rs:51 			thread::spawn(|| {
                           			^~~~~~~~~~~~~
    note: in expansion of for loop expansion
    src/dbus_service.rs:50:3: 59:4 note: expansion site
    src/dbus_service.rs:51:4: 51:17 error: the trait `core::marker::Sync` is not implemented for the type `*mut libc::types::common::c95::c_void` [E0277]
    src/dbus_service.rs:51 			thread::spawn(|| {
                           			^~~~~~~~~~~~~
    note: in expansion of for loop expansion
    src/dbus_service.rs:50:3: 59:4 note: expansion site
    src/dbus_service.rs:51:4: 51:17 note: `*mut libc::types::common::c95::c_void` cannot be shared between threads safely
    src/dbus_service.rs:51 			thread::spawn(|| {
                           			^~~~~~~~~~~~~
    note: in expansion of for loop expansion
    src/dbus_service.rs:50:3: 59:4 note: expansion site
    error: aborting due to 2 previous errors

Is there a way to fix this?

**Comment by diwic** [comment]
Hm, no, I don't think the thread safety story is currently a good one. It's very conservative, i e errs on the "safe" side.

Looking at it now, I think it would be safe for `Message` to implement `Send`, because the [API docs](http://dbus.freedesktop.org/doc/api/html/group__DBusThreads.html) seem to indicate that by saying "unless you lock them yourself".

Then your `n` will implement `Send`, too. 

But I'm not sure that will be enough. Because an `obj::ObjectPath` needs to reference a `Connection` (so it knows where it can send method return messages).

**Comment by diwic** [comment]
Furthermore, even if a `Connection` were to implement both `Send` and `Sync`, a call to `iter().next()` would lock it internally inside the D-Bus library for up to the timeout. So you wouldn't be able to send a reply, because the `Connection` is locked.

For this to work really well, we'll need async I/O, so that the `Connection` is unlocked while it waits for new events to come in.

**Comment by diwic** [comment]
Okay, so I actually had a half-made async I/O implementation so I finished that up last evening and it's now pushed to git master.
Not sure the API is the best one so I might change it around a bit.

The most complete example of how to use it is probably the test code in src/watch.rs.

The `obj::ObjectPath` is not `Sync`, so two methods cannot be called in parallel. But you should be able to handle method calls without `obj::ObjectPath`  by handling incoming method calls yourself.

**Comment by manuels** [comment]
Interesting, I'm gonna have a look at this.
Thanks!

**Comment by manuels** [comment]
I had a closer look at the code.
What do you think about the idea to box the `IConnection` into a `Arc<Mutex>` and to `derive(Clone)` for `Connection`?

**Comment by diwic** [comment]
> What do you think about the idea to box the IConnection into a Arc<Mutex> and to derive(Clone) for Connection?

To justify that overhead, how would that be more helpful compared to just doing `Arc<Mutex<Connection>>` in the code using the dbus library?

**Comment by manuels** [comment]
The thing is that `ObjectPath` uses a reference to `Connection`, right? So I think the `Arc<Mutex<IConnection>>` must be handled internally by dbus-rs

**Comment by diwic** [comment]
Hmm, so `ObjectPath` (currently) needs `Connection` for sending replies and to register/unregister itself. I wonder if it would make sense to make some kind of trait that Connection would implement? If so, you could then implement that trait yourself for an `Arc<Mutex<Connection>>` (by locking it and then calling the method). 

But again, I don't see where you're getting with all of this, because `Method` contains a `RefCell`, and refcells are not thread safe...

**Comment by manuels** [comment]
> But again, I don't see where you're getting with all of this, because Method contains a RefCell, and refcells are not thread safe...

But if you `derive(Send)` for a `Message`, it should be safe.

**Comment by diwic** [comment]
So I started to rewrite the `obj` module to fix this and a lot of other things. It's still WIP and does not fully work yet, but you can look at it if you like. For you, you want to use the `mdisp::Factory::new_sync()` version of the tree; that tree should be `Send` and `Sync` so you can make it handle messages in parallel.

**Comment by manuels** [comment]
Great, looks good. Thank you very much for your effort!
I'm gonna try it later this week.

**Comment by manuels** [comment]
Hi, sorry I did not give a response any sooner. I was pretty busy.
The new `Factory` interface works nicely! Thanks a lot!
But `Connection` cannot be shared between threads, so currently I use code something like this:

    let (tx, rx) = channel();
    for m in conn.iter(100) {
       match m {
           MethodCall(req) => {
               let tree2 = tree.clone();
               thread::spawn(move || {
                   let response = tree2.handle(req);
                   tx.send(reponse);
               }
           }
       }
       if let Some(resp) = rx.try_recv() {
           conn.send(resp);
       }
    }

Is there  a more elegant solution to that?

**Comment by diwic** [comment]
> Hi, sorry I did not give a response any sooner. I was pretty busy.

Same here. I should probably make a release with the new mdisp module sometime soon...

 > Is there a more elegant solution to that?

The only way to avoid `conn.iter` locking the connection for that time is to use the watchfd interface. Presumably together with mio (or some other async library, if there are any). I don't know if that counts as "elegant" though :-)

Also, I guess it should be safe to impl `Send` for `Connection` - that way you could keep it inside a `Mutex`, but that will only remove the channel, not the 100 msec delay.

**Comment by diwic** [comment]
Okay. So I released 0.2.0 now with the new API in it - after renaming `mdisp` to `tree` for aestetic reasons.
