### ISSUE TITLE
Possible to retrieve changed_properties from PropertiesChanged signal?

### ISSUE THREAD

**Issue by ohk2kt3t4** [diwic/dbus-rs#206]
I am using `dbus-rs` to subscribe to the PropertiesChanged signal for an interface, and then `get()`ing the new value of the property whenever there is an event. This works, however, since the new value of the property is actually contained in the PropertiesChanged signal message itself, I would like to parse it from there instead of making a separate get call. This is where I am stuck - I cannot figure out the right way to get the `changed_properties` value out of the signal message.

If I understand correctly, the message from the `org.freedesktop.DBus.Properties.PropertiesChanged` event is an array:
```
STRING interface_name  
DICT<STRING,VARIANT> changed_properties  
ARRAY<STRING> invalidated_properties
```

In my case the output is simple. The dict only has one key. Sample output from `dbus-monitor`:
```
string "local.statusbar.DBus"
array [
     dict entry(
          string "Status"
          variant string "test"
      )
]
array [
]
```

Is the following code the right way to go about getting the value of the variant string inside the dict?

```
fn parse_msg(msg: &Message) -> Option<&str> {
    if msg.msg_type() != MessageType::Signal { return None };
    if &*msg.interface().unwrap() != "localhost.statusbar.DBus" { return None };
    if &*msg.member().unwrap() != "PropertiesChanged" { return None };

    // Try to get the dict as a RefArg and get the values out by iterating over it.
    let (_, info) = msg.get2::<_, Box<dyn arg::RefArg>>();
    // When using "as_iter()" for a dict, we'll get one key, it's value, next key, it's value, etc.
    let mut iter = info.as_iter().unwrap();
    while let Some(key) = iter.next() {
        let status = iter.next().unwrap();
    }
    status
}

fn main() {
    let c = Connection::get_private(BusType::Session).unwrap();
    c.add_match("path='/localhost/statusbar/DBus', member='PropertiesChanged', interface='org.freedesktop.DBus.Properties'").unwrap();

    loop {
        if let Some(msg) = c.incoming(1000).next() {
            if let Some(status) = parse_msg(&msg) {
                println!("Status changed to: {}", status);
            }
        }
    }
}
```

Cheers for any help you are able to provide.

**Comment by Ichimonji10** [comment]
Rather than writing `parse_msg` yourself, you could generate parsing code with dbus-codegen. And TBH, I'm unsure how to parse a raw PropertiesChanged message - the generated code has worked well enough that I haven't needed to look at alternatives. Here's how I've done it in one of my projects:

I generated some code:

```bash
~/.cargo/bin/dbus-codegen-rust \
    --destination org.freedesktop.systemd1 \
    --path /org/freedesktop/systemd1 \
    > src/generated/org_freedesktop_systemd1.rs
```

I created `src/generated/mod.rs`, and I imported from `src/generated/org_freedesktop_systemd1.rs`:

```rust
use crate::generated::org_freedesktop_systemd1::OrgFreedesktopDBusPropertiesPropertiesChanged as PropertiesChanged;

// Some others may be necessary, so as to implement traits:
// use crate::generated::org_freedesktop_systemd1::OrgFreedesktopDBusProperties;
```

I then did some pattern-matching on incoming messages:

```rust
loop {
    for msg in self.connection.incoming(self.loop_timeout) {
        if let Some(msg_body) = PropertiesChanged::from_message(&msg) {
            self.handle_properties_changed(&msg, &msg_body, [SNIP])?;
        };
        // We don't care about other messages. We could log them at a low-level priority.
    }
}
```

Several other methods access `msg_body.changed_properties`. Here, I get the `ActiveState` property. You would probably get some other property.

```rust
// A unit's properties, as returned by a PropertiesChanged signal, or a call to
// org.freedesktop.systemd1.Unit.GetAll.
pub type UnitProps = HashMap<String, Variant<Box<dyn RefArg + 'static>>>;

// Return the value of the ActiveState property.
fn get_active_state(unit_props: &UnitProps) -> Result<ActiveState, CrateDBusError> {
    let active_state_str: &str = unit_props
        .get("ActiveState")
        .ok_or_else(|| CrateDBusError::PropertiesLacksActiveState)?
        .0
        .as_str()
        .ok_or_else(|| CrateDBusError::CastOrgFreedesktopSystemd1UnitActiveState)?;
    ActiveState::try_from(active_state_str)
        .map_err(CrateDBusError::DecodeOrgFreedesktopSystemd1UnitActiveState)
}
```

`CrateDBusError` is an enum wrapper around `dbus::Error`. It exists because the latter doesn't implement `Send`, and because I want more granular error types.

I might've missed something here, but I hope this'll get you on track.

**Comment by diwic** [comment]
> you could generate parsing code with dbus-codegen

You don't even have to do that; there is already an existing `PropertiesChanged` struct in the `stdintf` module.

 > dbus::Error. It exists because the latter doesn't implement Send, and because I want more granular error types.

`dbus::Error` should implement both `Send` and `Sync`, see https://docs.rs/dbus/0.6.5/src/dbus/lib.rs.html#76-82

**Comment by Ichimonji10** [comment]
> You don't even have to do that; there is already an existing PropertiesPropertiesChanged struct in the stdintf module.

Even better!

> dbus::Error should implement both Send and Sync, see https://docs.rs/dbus/0.6.5/src/dbus/lib.rs.html#76-82

Oh sweet. I'll look into that. I'm sure I saw an error about `Send` not being implemented - must be my mistake.

**Comment by ohk2kt3t4** [comment]
Thank you @Ichimonji10 and @diwic for your help so far! To be honest I am in a little bit over my head so I would very much appreciate if you could let me know if I am on the right track with the code below. 
(I do not have access to a *nix machine at the moment otherwise I would at least try and build it first.)

What I think the code should be doing:
* Listen to the session bus for `PropertiesChanged` signal at the specified path/interface
* Retrieve signal message as `PropertiesPropertiesChanged`
* Get the `changed_properties` dict out of it
* Get the first (and only) value that is in the dict which should be the new value of the property

```
extern crate dbus;
use dbus::{blocking::arg, Connection};

fn main() {
    let c = Connection::get_private(BusType::Session).unwrap();
    c.add_match("path='/localhost/statusbar/DBus', member='PropertiesChanged', interface='org.freedesktop.DBus.Properties'").unwrap();
    use dbus::blocking::stdintf::org_freedesktop_dbus::PropertiesPropertiesChanged as PropertiesChanged;
    loop {
        for msg in c.incoming(1000) {
            if let Some(msg_body) = PropertiesChanged::from_message(&msg) {
                let changed_properties = msg_body.changed_properties.unwrap();
                let mut iter = changed_properties.as_iter().unwrap();
                while let Some(key) = iter.next() {
                    let status = iter.next().unwrap();
                    println!("Status changed to: {}", &status);
                }
            };
        }
    }
}
```

**Comment by diwic** [comment]
What is `/localhost/statusbar/DBus` anyway, what program is it that provides this? I'm asking because it looks like you're going to need a complete example, so if I write that for you I could just as well submit that code to the examples directory as well. 🙂

**Comment by ohk2kt3t4** [comment]
Sorry for my incompetence. I will give the whole backstory just in case it helps:

There is a [status bar](https://github.com/greshake/i3status-rust) written in rust for [i3](https://i3wm.org/) or [sway](https://swaywm.org/) which lets you display the result of custom shell scripts every x seconds. I am using this to monitor the status of a couple things on my system, however I was not happy with the x second interval between updates so I [started writing](https://github.com/greshake/i3status-rust/pull/426) a component that uses DBus to get instant updates. 

The idea is that I [publish my own object](https://github.com/ammgws/dotfiles/blob/master/scripts/.local/bin/i3statusrs_dbus_server) (`/localhost/statusbar/DBus`) with some properties onto the session bus and subscribe to PropertiesChanged on those properties to get instant updates in the status bar. 

The linked code is working, however I want to try get the changed_property using only PropertiesPropertiesChanged without a separate get call, which lead to my attempt in the comment above.

**Comment by diwic** [comment]
Okay. So the code you posted seems to be a mix between 0.6 and the just released new 0.7 `blocking` connection. This needs to be fixed, but apart from that, here's the definition of the struct:

    pub struct PropertiesPropertiesChanged {
        pub interface_name: String,
        pub changed_properties: HashMap<String, Variant<Box<dyn RefArg + 'static>>>,
        pub invalidated_properties: Vec<String>,
    }

So if you have a `HashMap<String, Variant<Box<dyn RefArg + 'static>>>`, don't use `as_iter()`. Instead do something like:

    let value = ppc.changed_properties.get("status")?; // Or whatver the key name is

Next descend into the variant with `.0`. Then you can use `as_str()` if you know that the new status is a string, like this:

    let value = value.0.as_str()?;

Does that make sense?

**Comment by ammgws** [comment]
Got it working. Cheers for the help!

```
extern crate dbus;
use dbus::{BusType, Connection, SignalArgs};
use dbus::stdintf::org_freedesktop_dbus::PropertiesPropertiesChanged;

fn main() {
    let c = Connection::get_private(BusType::Session).unwrap();
    let matched_signal = PropertiesPropertiesChanged::match_str(Some(&"localhost.statusbar.DBus".into()), None);
    c.add_match(&matched_signal).unwrap();
    loop {
        for msg in c.incoming(1000) {
            if let Some(signal) = PropertiesPropertiesChanged::from_message(&msg) {
                let value = signal.changed_properties.get("Status").unwrap();
                let status = value.0.as_str().unwrap();
                println!("Status changed to: {}", &status);
            }
        }
    }
}
```

**Comment by ohk2kt3t4** [comment]
By the way, are there any performance enhancements or lightened dependencies to be gained from changing the code from 0.6 to 0.7?

I would like to make the switch, however it would be easier if I had some reason like that to convince other devs on the project.

**Comment by diwic** [comment]
@ohk2kt3t4 
See https://github.com/diwic/dbus-rs/blob/master/dbus/changes-in-0.7.md

There are some improvements, but the rework is also being the groundwork for future improvements which are not done yet.
