### ISSUE TITLE
How to `append` an empty Dict?

### ISSUE THREAD

**Issue by rschulman** [diwic/dbus-rs#207]
I'm dealing with the Bluez bluetooth DBus API, which in one case requires a method call with one argument being an (as far as I can tell from the documentation) empty dict. I'm struggling to figure out how to create one.

Any help is very appreciated!

**Comment by diwic** [comment]
D-Bus dicts are typed, so you need to specify the type to get it right. E g, if the D-Bus type is `DICT<STR, INT32>`, I think the easiest way would be

    let x: Option<(&str, i32)> = None;
    let myarg = dbus::arg::Dict::new(x);
 
Another option could be:

    let myarg = HashMap::<&str, i32>::new();

...you can just append the `HashMap` afterwards. Maybe the runtime cost is slightly higher for the latter version.

**Comment by rschulman** [comment]
That seems to have done it, thanks.

I've run into another question regarding `object_manager()`. Are issues the best place to ask one off questions, or is there an IRC room that might be better?

Thanks again.

**Comment by diwic** [comment]
> I've run into another question regarding object_manager(). Are issues the best place to ask one off questions, or is there an IRC room that might be better?

Issues are the best place so far, at least that's where I'm looking (and I'm the main developer/maintainer of dbus-rs). Perhaps other people can help you somewhere else, but if so, it's not something I'm aware of.
