### ISSUE TITLE
Whith new api we must use all path and clone object for tree

### ISSUE THREAD

**Issue by a1ien** [diwic/dbus-rs#208]
If we use `Factory::new_fn` with custom type we must pass this type in all paths to the final object.

if tree path log we must manual call add many times. And also get many objects
```rust
.add(f.object_path("/", type.clone()).introspectable())
.add(f.object_path("/com", type.clone()).introspectable())
.add(f.object_path("/com/somecompany", type.clone()).introspectable())
.add(f.object_path("/com/somecompany/someapp", type.clone()).introspectable())
...
```

Why we can't  use old function `set_registered` which call `dbus_connection_try_register_object_path` for all path to achieve tree introspection?

**Comment by diwic** [comment]
> If we use Factory::new_fn with custom type we must pass this type in all paths to the final object.
 > if tree path log we must manual call add many times. And also get many objects

If you have the same the object on every path, you should move that type from the object path to the tree. I e, instead of this:

    impl tree::DataType for Foo {
        type Tree = ();
        type ObjectPath = Bar;
        type Property = ();
        type Interface = ();
        type Method = ();
        type Signal = ();
    }

Have this:

    impl tree::DataType for Foo {
        type Tree = Bar;
        type ObjectPath = ();
        type Property = ();
        type Interface = ();
        type Method = ();
        type Signal = ();
    }

 > Why we can't use old function set_registered which call dbus_connection_try_register_object_path for all path to achieve tree introspection?

`dbus_connection_try_register_object_path` makes no sense to call unless you also call `dbus_connection_dispatch`, and avoiding the latter is one of the main points of the new `blocking` connection.

**Comment by diwic** [comment]
Also if you just want a struct on some of the objects you can use:

    impl tree::DataType for Foo {
        type Tree = ();
        type ObjectPath = Option<Bar>;
        type Property = ();
        type Interface = ();
        type Method = ();
        type Signal = ();
    }

This is no different in the old and new API. But I have thoughts about rewriting the `tree` part as well, and there this would work very differently. https://github.com/diwic/dbus-rs/issues/171

Maybe with 0.7 out the door this could be the next thing to work on...

**Comment by a1ien** [comment]
I probably didn't make the problem clear.
The problem about notice in migration guide.

> For trees, you must now make sure the root path (/) is always part of your tree.

We must not only make root part of our tree but all sequence path.

And it's also look wrong in d-feet. We see all path element as separate object. 
Like this
/
/com/
/com/somecompany
/com/somecompany/someapp
/com/somecompany/someapp/someobject
With old API in d-feet we see only last object
/com/somecompany/someapp/someobject

**Comment by diwic** [comment]
Ok, now I understand. As a quick workaround, can you see if this helps?

    --- a/dbus/src/tree/objectpath.rs
    +++ b/dbus/src/tree/objectpath.rs
    @@ -154,7 +154,7 @@ impl<M: MethodType<D>, D: DataType> ObjectPath<M, D> {
     pub(super) fn introspect(&self, tree: &Tree<M, D>) -> String {
         let ifacestr = introspect_map(&self.ifaces, "  ");
         let olen = if &**self.name == "/" { 1 } else { self.name.len()+1 };
    -    let childstr = tree.children(self, true).iter().fold("".to_string(), |na, n|
    +    let childstr = tree.children(self, false).iter().fold("".to_string(), |na, n|
             format!("{}  <node name=\"{}\"/>\n", na, &n.name[olen..])
         );

**Comment by a1ien** [comment]
It helped in part. But there is still the first root element left. Which create by `.add(f.object_path("/", ()).introspectable())`. If we could make a root element without an explicit introspection. This would solve the problem completely.

**Comment by diwic** [comment]
Great, thanks for testing! 

I don't see the root path showing up as a problem here. IMO, it would be more true to the spec to have it show up, than what the C libdbus library is doing (which is to answer to introspect calls on the root path, but without exposing that it could do so in the returned introspection data).

**Comment by a1ien** [comment]
Ok, maybe it's not a big problem. But as I say in first message we must pass for root our object.
if we could just use something like add_root_introspectable(). That'd be great.

**Comment by diwic** [comment]
I pushed a slightly improved version of the workaround above. 

 > we must pass for root our object.
 > if we could just use something like add_root_introspectable(). That'd be great.

This is not easily accomplished with the current tree design, unfortunately. My suggestion is that you make your object an `type ObjectPath = Option<MyObject>` instead of a `type ObjectPath = MyObject` and pass `None` for the root object.
