### ISSUE TITLE
dbus-tokio requires current_thread runtime

### ISSUE THREAD

**Issue by jgrund** [diwic/dbus-rs#209]
In:

https://github.com/diwic/dbus-rs/blob/a1f9c07af5b9f6c4fa7ca4d4f49a609bc1664cdb/dbus-tokio/src/adriver.rs#L38

`AConnection` requires use of a single-threaded executor. Is there any reason why the executor needs to be the single threaded variant instead of the thread_pool executor?

By doing this, it precludes usage from tokio applications that use other executors.

**Comment by diwic** [comment]
We're in a generation shift between the old `AConnection` + tokio 0.1, and the new `nonblock::Connection` + tokio master.

I believe the new version [outlined here](https://github.com/diwic/dbus-rs/blob/master/dbus-tokio/src/connection.rs) will not have this limitation.

As for reasons, I honestly don't know/remember as my Tokio knowledge is not the best and the reference to `&mut Runtime` was added by somebody else.

**Comment by jgrund** [comment]
Ah, great. How close to being usable is the new code?

**Comment by diwic** [comment]
@jgrund Hmm, good question. Try it and see 🙂 My plan was to hold off more development until async/await is stable (in november this year) and perhaps tokio 0.2 as well (by the end of this year) but I'm happy to merge PRs that accelerate that development, as long as they don't depend on unstable features.

It would be great if server method handlers could be `async fn`s but that's a bit further ahead.

**Comment by diwic** [comment]
@jgrund Hi! So I spent some time improving the `nonblock` module so that it actually works. You now have both a `LocalConnection` (for single-thread runtimes) and a `SyncConnection` (for multi-thread runtimes). There is also a `tokio02_client.rs` example that works; although the new connections should work just as well on the tokio 0.1 runtime.

Enjoy!

**Comment by diwic** [comment]
I have now release `dbus-tokio` 0.4 which works in a different way and where I hope this is not an issue. Therefore I think this is resolved. In case it is not, please reopen this bug. Thanks!
