### ISSUE TITLE
Is Dynamic DBus object path/interface checking implemented?

### ISSUE THREAD

**Issue by jbaublitz** [diwic/dbus-rs#213]
Do you happen to know if DBus or dbus-rs checks at runtime for whether an object path implements an interface before calling a method from the interface on the object path? I've tried to test this manually through a few different methods and I've even been reading through the DBus specification, but dbus-python, the library I'm using for testing, seems to handle that and error out before I can even get the invalid object path across the DBus to your library to see what the behavior is. My guess is that either DBus itself or dbus-rs will return an error if you call a method on an object path that does not implement the interface containing the called method, but I'd like to rule out any possibility that this would cause undefined behavior. Thank you!

**Comment by diwic** [comment]
It should error out in `ObjectPath.handle`: https://github.com/diwic/dbus-rs/blob/master/dbus/src/tree/objectpath.rs#L247

You should be able to use `dbus-send` to verify this (included in the `dbus` package, at least on Ubuntu).
