### ISSUE TITLE
Simple dbus-codegen example server

### ISSUE THREAD

**Issue by landersson** [diwic/dbus-rs#214]
Hi, thanks for creating this!

I'm trying to use dbus-codegen to create a minimal server and client, based on the simple XML test file in the README.md (Foo method / Laundry signal), but I'm struggling to put things together.

A full example on how to put together a minimal client/server using code generated by dbus-codegen would be really useful to me.

**Comment by diwic** [comment]
Hi, 

I agree this would be helpful, and it shouldn't be too difficult to accomplish, so I'm going to be bold enough to leave this open for someone (maybe yourself) to contribute this example code!

For the server part, there is one example using codegen here: https://github.com/diwic/dbus-rs/tree/master/dbus-codegen/examples

And the client part shouldn't be too many lines: create a session, create a proxy, use the trait, call the trait's methods. For receiving signals there is https://github.com/diwic/dbus-rs/blob/master/dbus/examples/match_signal.rs which uses codegen.

**Comment by landersson** [comment]
Ok! I'll send a PR when I manage to pull together something that works.

**Comment by deifactor** [comment]
I used dbus-codegen for [my notification daemon](https://github.com/deifactor/ninomiya); it's not super-well documented, but in case someone finds this issue it'll hopefully help.

The server is in `src/server.rs`, and there's a simple client jammed in `src/main.rs` (look for `Connection::new_session()?`).

**Comment by ammgws** [comment]
@landersson Did you ever come up with a working example?

**Comment by diwic** [comment]
Seems like no one else wanted to do it, so: https://github.com/diwic/dbus-rs/blob/master/dbus-codegen/examples/laundry_cr.rs
