### ISSUE TITLE
Inconsistency in *::Properties::set leads to incorrect codegen

### ISSUE THREAD

**Issue by singron** [diwic/dbus-rs#215]
dbus-codegen treats all three forms of this interface exactly the same

* `dbus::blocking::stdintf::org_freedesktop_dbus::Properties::set`
* `dbus::nonblock::stdintf::org_freedesktop_dbus::Properties::set`
* `dbus::ffidisp::stdintf::org_freedesktop_dbus::Properties::set`

However, the blocking version takes a `args::Variant<T>` instead of a `T`. I [patched](https://github.com/singron/dbus-rs/commit/0f3e6d7bcb69d8fe27783b7382a4335e7b0a162c) this in dbus-codegen, but maybe the right fix is to make all three interfaces the same?

**Comment by diwic** [comment]
> the right fix is to make all three interfaces the same?

Indeed, fixed now. Thanks for the report!
