### ISSUE TITLE
Error compiling 0.7

### ISSUE THREAD

**Issue by DmitriK** [diwic/dbus-rs#221]
Was previously using version 0.6, but when trying to update to latest 0.7 version, I get the following error when cargo gets to compiling this crate:

```
error[E0425]: cannot find function `dbus_get_local_machine_id` in crate `ffi`
   --> /home/dmitri/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.7.1/src/channel.rs:420:35
    |
420 |                     let id = ffi::dbus_get_local_machine_id();
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `dbus_try_get_local_machine_id`

error: aborting due to previous error
```
Based on commit 81b8d0c, I'm guessing my version of dbus is too new? I'm on Arch linux, and libdbus has version 1.12.16

**Comment by diwic** [comment]
It looks like a mismatch between the `dbus` and the `libdbus-sys` crates? The `dbus_get_local_machine_id` was added in `libdbus-sys` `0.2.1`.

But `dbus` `0.7.1` should depend on `libdbus-sys` `0.2.1`, so this should all resolve by itself, I'm not sure how it does not in your case? I'm assuming it the error goes away if you start a new project that depends on `dbus 0.7.1`, or perhaps if you run `cargo update`?

**Comment by DmitriK** [comment]
False alarm, a reboot fixed it. I think [lib]dbus was in a recent update and I hadn't restarted everything.
