### ISSUE TITLE
No such method?

### ISSUE THREAD

**Issue by tgharib** [diwic/dbus-rs#223]
I have the following code:

```
let c = dbus::blocking::Connection::new_session().unwrap();
let z = std::collections::HashMap::<String, dbus::arg::Variant::<Box::<dyn dbus::arg::RefArg>>>::new();
let m = dbus::Message::new_method_call("org.freedesktop.Notifications", "/org/freedesktop/Notifications", "org.freedesktop.Notifications", "CloseNotification").unwrap().append1(5);
let r = c.send_with_reply_and_block(m, time::Duration::from_secs(2)).unwrap();
```

But I get this panic:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: D-Bus error: No such method 'CloseNotification' in interface 'org.freedesktop.Notifications' at object path '/org/freedesktop/Notifications' (signature 'i') (org.freedesktop.DBus.Error.UnknownMethod)', src/libcore/result.rs:1165:5
```

I even tried using method_call instead:

```
let conn = dbus::blocking::Connection::new_session().unwrap();
let proxy = conn.with_proxy("org.freedesktop.Notifications", "/org/freedesktop/Notifications", time::Duration::from_millis(5000));
let (names,): (Vec<String>,) = proxy.method_call("org.freedesktop.Notifications", "CloseNotification", (5,)).unwrap();
```

But I still get the same issue. Honestly, I'm pretty lost and would appreciate a point in the correct direction. I can see the CloseNotification method in d-feet (dbus viewer) so I know it should exist and yet the library says "Unknown Method".

**Comment by tgharib** [comment]
I'm closing this issue since it sounds more like a support request than a bug report.

**Comment by tgharib** [comment]
Just to give some background for anyone that stumbles across this issue, I had been working at it for hours and I was past pulling my hair out and into the territory of tears.

I took a break and came back after a few hours. This time, I implemented it in python which took me about 10 minutes:

```
import dbus

session_bus = dbus.SessionBus()
proxy = session_bus.get_object('org.freedesktop.Notifications',
                               '/org/freedesktop/Notifications')
proxy.Notify("notify-send", 0, "", "hi mom3", "blah blah blah",
             [], [], 5000, dbus_interface="org.freedesktop.Notifications")
```

Python is pretty low friction so it allowed me to successfully implement the dbus method and verify that my conceptual understanding of dbus is correct. Anyway, I noticed in d-feet that `CloseNotification` takes an unsigned 32-bit integer and I was just passing `5` which is signed by default. Changing `5` to `5u32` fixed the issue in both methods. The first method still didn't work because of a different issue (because `CloseNotification` doesn't return anything) but the second method worked.

Now to implement the Notify method which has a very nasty signature in dbus `Notify (String app_name, UInt32 replaces_id, String app_icon, String summary, String body, Array of [String] actions, Dict of {String, Variant} hints, Int32 timeout) ↦ (UInt32 arg_0)`. I had the following code:

```
let c = dbus::blocking::Connection::new_session().unwrap();
    let m = dbus::Message::new_method_call("org.freedesktop.Notifications", "/org/freedesktop/Notifications", "org.freedesktop.Notifications", "CloseNotification").unwrap().append3("notify-send", 0, "").append3("Test", "test2", vec![""]).append2(z, 5000);
let r = c.send_with_reply_and_block(m, time::Duration::from_secs(2)).unwrap();
```

I changed the integer literals to use the `u32` suffix but still no dice.

Rust was giving me the following error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: D-Bus error: No such method 'Notify' in interface 'org.freedesktop.Notifications' at object path '/org/freedesktop/Notifications' (signature 'susssasa{sv}u') (org.freedesktop.DBus.Error.UnknownMethod)', src/libcore/result.rs:1165:5
```

The signature that I'm using is 'susssasa{sv}u' but that is the wrong signature. Luckily, when you get the signature wrong in python, it tells you that the correct signature is `susssasa{sv}i`. The last argument is supposed to be a signed 32-bit integer - not an unsigned 32-bit integer.

**Comment by diwic** [comment]
Indeed DBus arguments need to match exactly, or the remote peer will give you an error. To aid with getting this right, you can use the dbus-codegen to automatically generate boilerplate code with correct type signatures.
