### ISSUE TITLE
Get value from Variant

### ISSUE THREAD

**Issue by rustico** [diwic/dbus-rs#225]
Hello,

I am new at Rust (only read the book) and I am migrating a mini app I did that displays the lyrics from Spotify using dbus on Ubuntu.

I am following this example: https://github.com/diwic/dbus-rs/blob/master/dbus/examples/properties.rs with some minor changes.

The problem I am having is that I don't know how to get the value inside a Variant.

For example when I run the following code
```
extern crate dbus;

use std::collections::HashMap;
use std::time::Duration;
use dbus::{blocking::Connection, arg};
use dbus::blocking::stdintf::org_freedesktop_dbus::Properties;

fn print_refarg(value: &dyn arg::RefArg) {
    if let Some(s) = value.as_str() { println!("{}", s); }
    else if let Some(i) = value.as_i64() { println!("{}", i); }
    else { println!("{:?}", value); }
}

fn main() {
    let conn = Connection::new_session().unwrap();
    let p = conn.with_proxy("org.mpris.MediaPlayer2.spotify", "/org/mpris/MediaPlayer2", Duration::from_millis(5000));
    let metadata: HashMap<String, arg::Variant<Box<dyn arg::RefArg>>> = p.get("org.mpris.MediaPlayer2.Player", "Metadata").unwrap();

    let title = &metadata["xesam:title"];
    print_refarg(title);
    let artist = &metadata["xesam:artist"];
    print_refarg(artist);
}
```

I get this result
```
I Was Made For Lovin' You
Variant(["KISS"])
```

I added some new lines
```
let hola = &artist.0;
print_refarg(hola);
```

And I get this value
```
["KISS"]
```

The objective is to get the bands name and the song title but I am stuck int this step.

Sorry to bother you but I don't know where to ask.

Thank you!

Best,
Nico.

**Comment by diwic** [comment]
The variant's inner field is public so just access it with `.0` like any other tuple struct: https://doc.rust-lang.org/1.9.0/book/structs.html#tuple-structs

**Comment by diwic** [comment]
According to the specification here: https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/#index6h4 
`xesam:artist` is a list of strings, so 1) descend into the variant with `.0`, then 2) use `as_iter()` to iterate over all song artists, then 3) use `as_str()` for every artist to get the value as a string. 

Probably.

**Comment by rustico** [comment]
Thank you for looking at it! I will check that!
