### ISSUE TITLE
Tagging release

### ISSUE THREAD

**Issue by gaetanww** [diwic/dbus-rs#228]
Would it be possible to tag releases with `git tag`? It would make exploring the repos easier :) It would also make pulling the repo with git and specifying a version a lot easier.

**Comment by gaetanww** [comment]
For a bit of context, I had to use git for pulling the repository to be able to use dbus-crossroads.

**Comment by diwic** [comment]
It would be possible, given I come up with a good naming scheme (the repo has several crates, with separate versions). 

As for dbus-crossroads, it's still very much in development but if you try it out and have some comments/suggestions it would be appreciated!

**Comment by gaetanww** [comment]
I didn't think it through, tagging versions is not straightforward at all with different crates in the same repo.  I'll give it a think.

To use `dbus-crossroads` at the moment we have two solutions, either pulling out the project and refering it by path or pulling it with 
`dbus-crossroad = {git="https://github.com/diwic/dbus-rs.git" rev="<commit>"}`. It took me a bit of time to figure that out (I'm not very quick :) ), so it could be useful to have it written somewhere in a README; especially since the server example in `dbus-tokio` works only with `dbus-crossroads`.

**Comment by gaetanww** [comment]
There's been [a suggestion](https://github.com/rust-lang/cargo/issues/841#issuecomment-172326702) to tag with `packagename-VERSION`.
Do you think that would work?

**Comment by diwic** [comment]
Okay, I've now done this for the last release of dbus and dbus-tokio at least. dbus-crossroads has no release yet.
