### ISSUE TITLE
Connection example on front page is incorrect.

### ISSUE THREAD

**Issue by dszidi** [diwic/dbus-rs#230]
There is a line in the example code that reads...

`let obj = conn.with_path("org.freedesktop.DBus", "/", 5000);`

dbus::blocking::Connection has no method with_path();

**Comment by dszidi** [comment]
Suggested replacement example code taken from dbus-rs/dbus/examples/client.rs

**PR:** https://github.com/diwic/dbus-rs/pull/231

**Comment by diwic** [comment]
Merged now. Thanks!
