### ISSUE TITLE
Comparison of dbus implementations

### ISSUE THREAD

**Issue by KillingSpark** [diwic/dbus-rs#241]
I started a repo with benchmarks for the different dbus implementations available in rust, and dbus-rs seems to be a big outlier. Could you have a look and tell me if I used dbus-rs in an inefficient way?

[Repo](https://github.com/KillingSpark/rust-dbus-comparisons)

**Comment by diwic** [comment]
Not anything big, I'm afraid. 

As for the `send_rustbus` benchmark (if I read the code correctly?) seems to just send the hello message without waiting for a reply, where as `dbus_rs` waits for the reply before proceeding. That could be an important difference.

Here are my benchmarks, especially the "send" ones don't differ as much as yours. Dbus-rs is still the slowest though.

    marshal_rustbus         time:   [30.860 us 30.879 us 30.899 us]                             
    marshal_dbusrs          time:   [233.48 us 233.73 us 233.97 us]                           
    marshal_dbus_bytestream time:   [22.719 us 22.775 us 22.834 us]                                     
    marshal_zvariant        time:   [26.020 us 26.037 us 26.054 us]  
    send_rustbus            time:   [455.94 us 461.42 us 466.29 us]                         
    send_dbusrs             time:   [827.95 us 837.16 us 846.12 us]                        
    send_dbus_bytestream    time:   [507.39 us 512.58 us 517.98 us]

**Comment by diwic** [comment]
Also, an interesting benchmark would be sending a large message, say you have a `&[u8]` that is 1 MB or so, what is the speed of sending and receiving such an array, and what is the memory pressure?

**Comment by KillingSpark** [comment]
Good catch about the waiting on the hello message, thanks! I added the changes for the dbusrs benchmarks.

I'll definitely look into more interesting benchmark scenarios (e.g. something with more messages instead of one message per connection, and bigger messages as well).
