### ISSUE TITLE
Some things seems to be missing in v0.7

### ISSUE THREAD

**Issue by I60R** [diwic/dbus-rs#242]
I'm trying to migrate from using `ffidisp` module but cannot figure out what to do with the following:

1) `ObjectManager` trait
2) `MsgHandler` trait 
3) `Connection::open_private`

Would be this supported or should I continue to use `ffidisp` module?

**Comment by diwic** [comment]
I take it as you write client-side code rather than server-side, if not, the below may be incorrect.

 > ObjectManager trait

Fixed in dbus 0.8.2

 > Connection::open_private

Fixed in dbus 0.8.2 - connections implement  `From<Channel>` and `Channel` has an `open_private` method. 

 > MsgHandler trait

This has been replaced with the `MatchingReceiver` trait.
