### ISSUE TITLE
Unable to get org.freedesktop.dbus.Properties::PropertiesChanged events.

### ISSUE THREAD

**Issue by mikeb01** [diwic/dbus-rs#243]
I'm using the following code:
```
    let mut conn2 = Connection::new_system().unwrap();
    let dbus_proxy = conn2.with_proxy("org.freedesktop.DBus.Properties", "/org/freedesktop/NetworkManager/AccessPoint/318", Duration::from_millis(5000));
    dbus_proxy.match_signal(|h: dbus::blocking::stdintf::org_freedesktop_dbus::PropertiesPropertiesChanged, _: &Connection, _: &dbus::Message| {
        println!("{:?}", h);
        return true;
    }).unwrap();

    for i in 1..100 {
        println!("{}: {}", "polling", i);
        conn2.process(Duration::from_millis(1000)).unwrap();
    }
```
And I never see an event printed, however running with dbus-monitor shows PropertiesChanged events firing for the specified path.
```
signal time=1584351789.956702 sender=:1.11 -> destination=(null destination) serial=47858 path=/org/freedesktop/NetworkManager/Devices/3; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
```
I was able to get some other events to fire, I'm not sure what I'm doing wrong.

**Comment by diwic** [comment]
> conn2.with_proxy("org.freedesktop.DBus.Properties", "/org/freedesktop/NetworkManager/AccessPoint/318", Duration::from_millis(5000))

I think the first parameter should be "org.freedesktop.NetworkManager", but without `strict_sender` maybe it does not matter.

The second parameter `/org/freedesktop/NetworkManager/AccessPoint/318` does not match `/org/freedesktop/NetworkManager/Devices/3`, but maybe this was just a copy-paste error?

**Comment by mikeb01** [comment]
The interface name was the problem.  Thank you.
