### ISSUE TITLE
[dbus-codegen] not working README-code

### ISSUE THREAD

**Issue by Stunkymonkey** [diwic/dbus-rs#245]
I wanted to have a shared state across all method call i am receiving. Therefore I think my right option is to use `AsRefClosure` as described in the [README.md](https://github.com/diwic/dbus-rs/tree/master/dbus-codegen)
My attempt here:
```
let notifications = Rc::new(Notifications { queue: Vec::new() });

let factory = tree::Factory::new_fn::<()>();
let iface = interface::org_freedesktop_notifications_server(&factory, (), move |_| {
    notifications.clone()
});
```
throws the following error:
```
             notifications.clone()
   |         ^^^^^^^^^^^^^^^^^^^^^
   |         |
   |         expected reference, found struct `std::rc::Rc`
   |         help: consider borrowing here: `&notifications`
```
what am I missing?

**Comment by diwic** [comment]
Not sure, can you double-check that you actually used the asref method and nothing else? If you did, please link to the generated code.

Also, another option to share state between method calls is to use data stored in the tree object. There is an example of this in [adv_server_codegen.rs](https://github.com/diwic/dbus-rs/blob/master/dbus-codegen/examples/adv_server_codegen.rs#L169). In your case, that would probably be something like:

    impl tree::DataType for TData {
        type Tree = Notifications; // Or perhaps Rc<RefCell<Notifications>> depending on your use case
        type ObjectPath = ();
        type Property = ();
        type Interface = ();
        type Method = ();
        type Signal = ();
    }

**Comment by Stunkymonkey** [comment]
the last time i generated it, I forgot to add the parameter `AsRefClosure`.
Sorry for wasting your time, but thanks for the fast reply.

**Comment by Stunkymonkey** [comment]
sorry i still have some questions:
currently i create my interface like [this](https://github.com/durst-notification/durst/blob/master/durst/build.rs), which works perfectly fine.
as already said, i want to have a shared state across all function-calls. my current error is:
```
 --> durst/src/main.rs:73:17
   |
73 |     let iface = interface::org_freedesktop_notifications_server(&factory, (), move |_| {
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::AsRef<(dyn interface::OrgFreedesktopNotifications + 'static)>` is not implemented for `std::rc::Rc<Notifications>`
   |
  ::: durst/src/interface.rs:13:8
   |
13 | pub fn org_freedesktop_notifications_server<F, T, D>(factory: &tree::Factory<tree::MTFn<D>, D>, data: D::Interface, f: F) -> tree::Interface<tree::MTFn<D>, D>
   |        ------------------------------------
...
18 |     T: AsRef<dyn OrgFreedesktopNotifications>,
   |        -------------------------------------- required by this bound in `interface::org_freedesktop_notifications_server`
   |
   = help: the following implementations were found:
             <std::rc::Rc<T> as std::convert::AsRef<T>>
```
surely i have to implement something for `Notifications`.
my [`main.rs` ](https://github.com/durst-notification/durst/blob/master/durst/src/main.rs)

**Comment by Stunkymonkey** [comment]
sorry updated the wrong links

**Comment by diwic** [comment]
Yeah, you're missing this part:

    impl AsRef<dyn interface::OrgFreedesktopNotifications + 'static> for Rc<Notifications> {
        fn as_ref(&self) -> &(dyn interface::OrgFreedesktopNotifications + 'static) { &**self }
    }

I had to look it up myself, so needless to say, this wasn't very obvious. I've updated the codegen readme with this now.

**Comment by Stunkymonkey** [comment]
thanks it works.
maybe you want to include something like my `build.rs` in the examples. I think others will reuse it

**Comment by Stunkymonkey** [comment]
hopefully one last question:
doing something like this `self.queue.push(new_notification);` will produce:
```
  --> durst/src/main.rs:49:9
   |
28 |         &self,
   |         ----- help: consider changing this to be a mutable reference: `&mut self`
...
49 |         self.queue.push(new_notification);
   |         ^^^^^^^^^^ `self` is a `&` reference, so the data it refers to cannot be borrowed as mutable
```
how is it possible to write to the `queue`?

**Comment by diwic** [comment]
> how is it possible to write to the queue?

There is no way to get a mutable reference here so you'll have to resort to interior mutability, i e make the `queue` a `RefCell` (or possibly `Mutex`).
