### ISSUE TITLE
Trait bound not satisfied

### ISSUE THREAD

**Issue by JoshuaI96** [diwic/dbus-rs#247]
Hi, 
I am new to rust and chose it for my graduation assignment.

I am trying to implement a server with the generated code like the example: https://github.com/diwic/dbus-rs/blob/master/dbus-codegen/examples/adv_server_codegen.rs

I just changed it to use one of my `Manager` object instead of your vec of devices.
In my implementations of the interface methods my object tries to mutate itself, so I changed the Trait definition to use `&mut self`, generated the code with `-m FnMut` and changed `MTFn` to `MTFnMut` in the example.

Here is my problem:
In the `create_tree` function when the cloned interface is added to the tree I get a compiller error:
```
the trait `std::convert::From<std::sync::Arc<dbus::tree::objectpath::Interface<dbus::tree::methodtype::MTFnMut<dbus_server::TData>, dbus_server::TData>>>` is not implemented for `std::sync::Arc<dbus::tree::objectpath::Interface<dbus::tree::methodtype::MTFn<_>, _>>`
```

And likewise the returned tree has a mismatched type
```
expected struct `dbus::tree::methodtype::MTFnMut`, found struct `dbus::tree::methodtype::MTFn`
```

The main problem most likely beeing the `tree.add` method not accepting an interface of type `&Arc<Interface<MTFnMut<TData>, TData>>`.

Do you may have an idea where my mistake is and how to fix it?
Thanks in advance.

**Comment by diwic** [comment]
Hi,

It's hard to tell without seeing more of the code. My guess is that left an fn unchanged to an fnmut somewhere, maybe the factory is still created with `new_fn` instead of `new_fnmut` or something.

But you might be misunderstanding the difference between `MTFn` and `MTFnMut`. 
If your `Manager` object is stored using the `TData` method, it does not matter whether you use `MTFn` or `MTFnMut`. You'll still only have immutable access to `Manager`. 

The difference between `MTFn` and `MTFnMut`, as well as `Fn` and `FnMut` in general, only applies to the variables captured by the closure.

**Comment by JoshuaI96** [comment]
Hi,
Thank you for your fast reply.

Yes, the tree in the create tree function was a still `new_fn`.
After changing this, I got a new error from the generated code.
```
   |
26 |         let d = fclone(minfo);
   |             - help: consider changing this to be a mutable reference: `&mut T`
27 |         let reply = d.start(id)?;
   |                     ^ `d` is a `&` reference, so the data it refers to cannot be borrowed as mutable
```
The corresponding code:
```rust
pub fn com_example_myexample_server<F, T, D>(factory: &tree::Factory<tree::MTFnMut<D>, D>, data: D::Interface, f: F) -> tree::Interface<tree::MTFnMut<D>, D>
where
    D: tree::DataType,
    D::Method: Default,
    D::Signal: Default,
    T: ComExampleMyexample,
    F: 'static + for <'z> Fn(& 'z tree::MethodInfo<tree::MTFnMut<D>, D>) -> & 'z T,
{
    let i = factory.interface("de.gonicus.ictime.timer", data);
    let f = ::std::sync::Arc::new(f);
    let fclone = f.clone();
    let h = move |minfo: &tree::MethodInfo<tree::MTFnMut<D>, D>| {
        let mut i = minfo.msg.iter_init();
        let id: i32 = i.read()?;
        let d = fclone(minfo);
        let reply = d.start(id)?; <--- This line
        let rm = minfo.msg.method_return();
        let rm = rm.append1(reply);
        Ok(vec!(rm))
    };
.
.
.
```

So I changed the type of the f paramet to `f: &'static mut F`, which fixed the error above but raised a new one...
```
   |
54 |     timer_definition::com_example_myexample_server(&f, (), |m| {
   |                                                             ^ consider giving this closure parameter a type
   |
   = note: type must be known at this point
```

Tampering with given or generated code usually indicates that I am doing something wrong.
Is it even possible to have the object beeing mutated in the interface method?
Here is an example from the trait implementation for the interface methods:
```rust
impl timer_definition::ComExampleMyexample for manager::Manager {
    // type Err = tree::MethodErr; <--- commented out, not a member of trait?
    fn start(&mut self, id: i32) -> Result<bool, tree::MethodErr> {
        match self.start_timer_by_id(id as u32) {
            Ok(_) => return Ok(true),
            Err(e) => return Err(MethodErr::failed(&e))
        };
    }
.
.
.
```
Like I said, I am new to rust and have the feeling to totaly missuse it.

**Comment by diwic** [comment]
> Is it even possible to have the object beeing mutated in the interface method?

No - I agree that would be useful, but it's currently not supported. The trait generated by dbus-codegen should only have methods taking `&self`, not `&mut self`, if you manually changed this, that's an error. You'll have to work around this using `RefCell` or `Mutex`.

**Comment by JoshuaI96** [comment]
I didn't work with `RefCell` or `Mutex` befor, but from reading the docs I think Mutex would be the one to go for. Is my a assumption correct that I would have to rebuild my `Manager` struct to wrap the mutable fields in `Mutex`?

Here is the structure
```rust
pub struct Manager{
    timer_list: Vec<Timer>,
    last_timer_id: u32
}

pub struct Timer {
    name: String,
    id: u32,
    slices: Vec<Slice>
}
pub struct Slice {
    start: u64,
    end: Option<u64>
}
```
The mutability reaches down to the `Slice`. 
The `Manager` creates and manages `Timers`, `Timers` start by creating `Slices` and stopping by setting the stop field to a value. 

So I think the `slices` field in the `Timer` should be a `Mutex` and the `timer_list` in the manager should be too.

Sorry If these are dumb newbie questions. But wrapping my mind around some of this stuff is harder than I thought.

**Comment by diwic** [comment]
Hmm, maybe it's easier just to do something like this:

    impl timer_definition::ComExampleMyexample for Rc<RefCell<manager::Manager>> {
        fn start(&self, id: i32) -> Result<bool, tree::MethodErr> {
            let mut manager = self.borrow_mut();
            ... do things with manager here ...
        }
    }

Replace `Rc<RefCell<manager::Manager>>` with `Arc<Mutex<manager::Manager>>` if you need concurrent access (but if you did, you would be using `MTSync` so I don't think you do). Or just `RefCell<manager::Manager>` if you don't need to access the manager from outside the tree.

 > Sorry If these are dumb newbie questions. But wrapping my mind around some of this stuff is harder than I thought.

I asked the same type of questions a few years ago, and friendly people helped me understand the harder parts of Rust. Maybe you'll be helping others in a few years time as well?

**Comment by JoshuaI96** [comment]
Yes, that was easier.
Replaced all `manager::Manaǵer` with `Rc<RefCell<manager::Manager>>` and it compiled, what's a good sign :)

Do I have to manually tell the `mut manager = self.borrow_mut();` that I am done with it, or does `Rc` or `RefCell`  handle it when the borrow ends?

> Maybe you'll be helping others in a few years time as well?

I hope so, I am working at a company where knowledge transfer is a huge part and I am the first one to do a rust project. So yes, then it's my turn :)

**Comment by JoshuaI96** [comment]
> Do I have to manually tell the mut manager = self.borrow_mut(); that I am done with it, or does Rc or RefCell handle it when the borrow ends?

No I don't.

Everythink seems so work properly now, even wit multiple interfaces and trees.

Thank you for your help!
