### ISSUE TITLE
as_iter_of_u8 or similar method for RefArg

### ISSUE THREAD

**Issue by deifactor** [diwic/dbus-rs#248]
The [notification specification](https://developer.gnome.org/notification-spec/) indicates that images can be passed in the hints field of a message using a value of signature `(iiibiiay)`. Since the hint dict is untyped, at runtime when I'm implementing the server I only get a `HashMap<&str, Variant<Box<dyn RefArg>>>`. So I ultimately need to turn a `dyn RefArg` into a `Vec<u8>` or a `&[u8]` or similar... but as far as I can tell, the only way to do that is to use `as_iter`, which will box each individual byte of raw image data! I'd like to be able to just get an `Box<dyn Iterator<Item = u8>>` out. In theory this could be generalized to *any* of the types that can be stored in an array (byte, string, etc) but a `u8` is good enough for me for now.

(I saw that you're fairly uninterested in maintaining this these days; I don't think I could do full co-maintainership, but I'd definitely be interested in implementing this.)

**Comment by diwic** [comment]
Hi!

So `Box<dyn Iterator<Item = u8>>` would also be slow because of the virtual dispatch required for every byte. But since the internal representation of `ay` is `Vec<u8>`, you should be able to use `arg::cast()` to cast the `&dyn RefArg` directly to a `&Vec<u8>`.

This is not exactly well documented so if you'd like to contribute, feel free to go ahead and add a working example to the documentation of the `arg::cast()` method.

**Comment by deifactor** [comment]
Ah, yeah, I hadn't thought about the dynamic dispatch.

I was considering using `arg::cast`, but didn't want to rely on implementation details. But as long as it'll fail noisily and not UB, I'm fine with it.

**Comment by diwic** [comment]
> I was considering using arg::cast, but didn't want to rely on implementation details.

Good point. I can commit to using `Vec` for arrays of fixed types and string types (arrays of container types, such as arrays of arrays, arrays of structs etc should continue to be implementation details until someone needs them), and you can write a test case and/or documentation that confirms this?

**Comment by deifactor** [comment]
Yep, I can do that!
