### ISSUE TITLE
Question updating dbus

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [diwic/dbus-rs#250]
I found [this](https://github.com/GuillaumeGomez/systemd-manager) which uses dbus but is quite old and doesn't compile on my machine. It uses dbus version 0.3.3 and the api has changed quite a bit. 

I'd like to change these lines so that I can get ListUnitFiles

```rust
pub fn list_unit_files() -> Vec<SystemdUnit> {
    /// Takes the dbus message as input and maps the information to a `Vec<SystemdUnit>`.
    fn parse_message(input: &str) -> Vec<SystemdUnit> {
        let message = {
            let mut output: String = input.chars().skip(7).collect();
            let len = output.len()-10;
            output.truncate(len);
            output
        };


        // This custom loop iterates across two variables at a time. The first variable contains the
        // pathname of the unit, while the second variable contains the state of that unit.
        let mut systemd_units: Vec<SystemdUnit> = Vec::new();
        let mut iterator = message.split(',');
        while let Some(name) = iterator.next() {
            let name: String = name.chars().skip(14).take_while(|x| *x != '\"').collect();
            let utype = UnitType::new(&name);
            let state = UnitState::new(iterator.next().unwrap());
            systemd_units.push(SystemdUnit{name: name, state: state, utype: utype});
        }


        systemd_units.sort_by(|a, b| a.name.cmp(&b.name));
        systemd_units
    }


    let message = dbus_connect!(dbus_message!("ListUnitFiles")).unwrap().get_items();
    parse_message(&format!("{:?}", message))
}
```

How does that work with the newer api?

**Comment by Th3Whit3Wolf** [comment]
Here's the macros

https://github.com/GuillaumeGomez/systemd-manager/blob/17cf15451f534a314dd55867d6016dd7d970d48c/src/systemd/dbus.rs#L4-L21

**Comment by diwic** [comment]
The last macro should be something like:

    use dbus::blocking::BlockingSender; 
    dbus::blocking::Connection::new_system().unwrap()
        send_with_reply_and_block($message, Duration::from_millis(4000))

If anything else is wrong, please post the exact error messages you get. Thanks!

**Comment by Th3Whit3Wolf** [comment]
Okay so now I got

```sh
macro expansion ignores token `send_with_reply_and_block` and any following
the usage of `dbus_connect!` is likely invalid in expression context

[100,19]caused by the macro expansion here
[100,64]you may be missing a semicolon here
```

and it pointed me to these lines(100,101)

```rust
let message = dbus_connect!(dbus_message!("ListUnitFiles")).unwrap().get_items();
    parse_message(&format!("{:?}", message))
```
I'm not sure from here if it's best to drop the `unwrap().getitems()` or add a  `.process()` but either way it doesn't give me a message to use `.get_items()` on

**Comment by diwic** [comment]
I've updated my comment to show more of the context, and added a missing dot. 

    dbus_connect!(dbus_message!("ListUnitFiles")).unwrap()

...should give you a `Message`.

**Comment by Th3Whit3Wolf** [comment]
So I rewrote different parts of the SystemdUnit struct to have option type so that the binary wouldn't panic but I think I may have done something wrong.

I get back this as a result for printing all the names.
```
2
dReturn
ime
ime
```

You have already been a big help but do you think you could show me a simple example of how to get a list of all the unit files on a system with dbus?

**Comment by diwic** [comment]
Here's how I would write it:

    let conn = Connection::new_system()?;
    let proxy = conn.with_proxy("org.freedesktop.systemd1", "/org/freedesktop/systemd1", 
        Duration::from_millis(5000));
    let (names,): (Vec<(String, String)>,) = proxy.method_call(
        "org.freedesktop.systemd1.Manager", "ListUnitFiles", ())?;
    for (a, b) in names { println!("{} - {}", a, b); }

I e, the same way `examples/client.rs` is written.

**Comment by Th3Whit3Wolf** [comment]
That's works! Thank you for all the help!!!
