### ISSUE TITLE
Support: yet another variant extract question

### ISSUE THREAD

**Issue by Moret84** [diwic/dbus-rs#251]
Hello @diwic and thanks for your work on this crate.

I am new to rust and I am trying to extract a value from a variant, but the inner content seems unusal.

Here is the .0 debug format output:

``` rust
InternalDict {
    data: [
        (
            "0000fe95-0000-1000-8000-00805f9b34fb",
            Variant(
                [
                    80,
                    32,
                    170,
                    1,
                    85,
                    125,
                    189,
                    219,
                    168,
                    101,
                    76,
                    13,
                    16,
                    4,
                    229,
                    0,
                    109,
                    1,
                ],
            ),
        ),
        (
            "0000ffff-0000-1000-8000-00805f9b34fb",
            Variant(
                [
                    192,
                    75,
                    80,
                    56,
                    236,
                    7,
                ],
            ),
        ),
    ],
    outer_sig: Signature(
        "a{sv}",
    ),
}
```

I can't find how to get the inner data.
I have tried to cast it to a `HashMap<String, Vec<u8>>`, to a `HashMap<String, Variant<Box<dyn RefArg>>>` too, but without success.

This field come from the Bluez Device API. It is called ServiceData and the documentation describe it the following : "Keys are the UUIDs in string format followed by its byte array value."
https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/device-api.txt

I am sorry but I don't know where to ask . Could you help me ?

Thanks

**Comment by diwic** [comment]
Yes, what you're looking at is an implementation detail which I added to fix another bug a while ago...

If what you got was a `Box<RefArg>` then you cannot directly cast the dict to something else. You need to use `as_iter()` instead, something like:

    let x = myprop.as_iter()?;
    while let Some(key) = x.next() {
       println!("{}", key.as_str()?);
       let value = x.next()?;
       let inner_value = x.as_iter()?.next()?; // descend into the variant
       let v: &Vec<u8> = arg::cast(&*inner_value)?;
       println!("{:?}", v);
    }

This is just straight out of my head, so not sure everything is correct above.

As an option, you might be able to get a `Variant<HashMap<String, Variant<Vec<u8>>>>` directly from the start. I can't say if this is easier or not as I have not seen your code.

**Comment by Moret84** [comment]
First many thanks for your response.

> As an option, you might be able to get a `Variant<HashMap<String, Variant<Vec<u8>>>>` directly from the start. I can't say if this is easier or not as I have not seen your code.

I've tried, without success. Maybe related to 

> If what you got was a `Box<RefArg>` then you cannot directly cast the dict to something 

As for the iterator sample you provided, in 

> ```  let x = myprop.as_iter()?; ``` 

What does myprop exactly refer to ? Is this the Variant ? The inner of the variant ?
Here is my attempt

```
const BLUEZ_DBUS_DEVICE_INTERFACE: &str = "org.bluez.Device1";

let on_interface_added = {
    | p: OrgFreedesktopDBusObjectManagerInterfacesAdded, _: &Connection, m: &Message| {

        let service_data = &p.interfaces[BLUEZ_DBUS_DEVICE_INTERFACE]["ServiceData"].0;

        let mut x = service_data.as_iter().unwrap();

        while let Some(key) = x.next() {
            println!("{}", key.as_str().unwrap());

            let value = x.next().unwrap();
            let inner_value = value.as_iter().unwrap().next().unwrap(); // descend into the variant
            let v: &Vec<u8> = dbus::arg::cast(&*inner_value).unwrap();
            println!("{:?}", v);
        }

        true
    }
};

```
But I get this compile error:
```
error[E0597]: `p.interfaces` does not live long enough
   --> src/main.rs:142:25
    |
142 |             let mut x = p.interfaces[BLUEZ_DBUS_DEVICE_INTERFACE]["ServiceData"].0.as_iter().unwrap();
    |                         ^^^^^^^^^^^^ borrowed value does not live long enough
...
149 |                 let v: &Vec<u8> = dbus::arg::cast(&*inner_value).unwrap();
    |                                                   ------------- cast requires that `p.interfaces` is borrowed for `'static`
...
154 |         }
    |         - `p.interfaces` dropped here while still borrowed

```

As for now I can't understand why. I can't see where p.interfaces is borrowed and not returned back.

But this seems rather related to my poor rust skills than your implementation.
So sorry to bother you with that,

**Comment by diwic** [comment]
Ok, so in this case I don't think it's possible to get a `Variant<HashMap<String, Variant<Vec<u8>>>>` directly.

Does it help if you add a `box_clone` like this: 

    let inner_value = value.as_iter().unwrap().next().unwrap().box_clone();

**Comment by Moret84** [comment]
> 
> Does it help if you add a `box_clone` like this:
> 
> ```
> let inner_value = value.as_iter().unwrap().next().unwrap().box_clone();
> ```

Nope the cast of `inner _value` to `Vec<u8>` on the following line fails (contains None)

**Comment by diwic** [comment]
> Yeah it could but the cast of inner _value to Vec<u8> on the following line fails (contains None).

Does debug printing give any hint of what type it is instead? Like this:

    let inner_value = value.as_iter().unwrap().next().unwrap().box_clone();
    println!("{:?}", inner_value);

 > I can always iterate the inner_value byte after byte to put it in a new Vec but don't know if it is the right way.

Sure, whatever floats the boat 😀

**Comment by Moret84** [comment]
> > Yeah it could but the cast of inner _value to Vec on the following line fails (contains None).
> 
> Does debug printing give any hint of what type it is instead? Like this:

Yes, InternalArray rather than InternalDict:
```
InternalArray { data: [80, 32, 170, 1, 236, 125, 189, 219, 168, 101, 76, 13, 16, 4, 225, 0, 133, 1], inner_sig: Signature("y") }`
```
> 
> ```
> let inner_value = value.as_iter().unwrap().next().unwrap().box_clone();
> println!("{:?}", inner_value);
> ```
> 
> > I can always iterate the inner_value byte after byte to put it in a new Vec but don't know if it is the right way.
> 
> Sure, whatever floats the boat 

I think I 'll do it that way, I have bothered you enough :p

**Comment by diwic** [comment]
> Yes, InternalArray rather than InternalDict:

But meh! It's `box_clone` that destroys the `Vec`. I should fix this. Some day. 😀

**Comment by Moret84** [comment]
> > Yes, InternalArray rather than InternalDict:
> 
> But meh! It's `box_clone` that destroys the `Vec`. I should fix this. Some day. grinning

No problem guy. Thanks for your support.
I will close the issue.
