### ISSUE TITLE
Failing to process large message replies with dbus-tokio

### ISSUE THREAD

**Issue by ivoisbelongtous** [diwic/dbus-rs#254]
I've been trying to use these bindings to interface with `connman`, but have been having issues when `connman` sends large payloads in reply to methods I've called, e.g., a long array of properties when querying for services. I suspect this is related to issues discussed in the initial tokio integration proposal, particularly https://github.com/diwic/dbus-rs/issues/72#issuecomment-312346002. The `dbus-tokio` implementation appears to have changed quite a lot since then (now using `dbus_connection_read_write` in favour of `dbus_connection_read_write_dispatch`) and so has `tokio` (the previous solution seems to have been switching to level triggers which is no longer an option with modern `tokio`.)

To summarise the linked issue and my own findings (corrections very welcome): the future gets woken up when D-Bus's watch object – represented by a file descriptor – is marked as ready for writing to or reading from. In this case, we care about whether we can read from D-Bus as this means there are messages to handle from the incoming queue. On waking up, the future calls `dbus_connection_read_write` to process the queue, then `dbus_connection_pop_message` to get the first message. However, when we receive a large message we run into a quirk where the watch is marked as ready but even after processing the queue still no message is popped. This seems to be because `dbus_connection_read_write` stops after 2048 bytes are processed, meaning the message is not actually ready to be dispatched, even if the watch claims it's ready to be read. The solution to this problem in the past was to set `tokio` to be level-triggered, meaning it would wake the future up whenever anything in the watch changed, spuriously waking up whenever any number of bytes were processed but ensuring we're awake to dispatch the final message. Unfortunately, `tokio` now only supports 'edge-triggering' which means the future will only be woken up when the watch first transitions to be read ready, and going back to sleep before the message is actually ready to dispatch (nor driving it to completion enough by calling `dbus_connection_read_write`.) This results in the reply never being handled and `Proxy::method_call` erroring with a timeout. (Big thanks to albel727 in the original issue who I won't @ directly so as not to rope them in)

I've created a minimal example to demonstrate the problem: https://github.com/ivoisbelongtous/dbus-large-message-timeout-example. Fiddling around with the number of entries and property fields in the method reply factory function should demonstrate that receiving the replies is dependent on the size of the payload. I've also confirmed this behaviour is only exhibited when using the `nonblock` module and not the `blocking` variation.

The limit for message sizes seems to be increased by repeated calls to `dbus_connection_read_write` in `dbus-tokio/src/connection.rs`'s `poll_internal` function, but this isn't a proper long-term solution, with `connman` still managing to generate replies larger than two calls to the read/write function can process. As was noted in the original issue, D-Bus certainly doesn't make it easy for us to implement a readiness-based main loop, but perhaps others will have insight into how to know when messages are actually ready to be popped from the incoming queue without blocking when we're woken up to write messages to the outgoing queue?

**Comment by diwic** [comment]
Hmm. So if we would need to check if there is more data to read after every call to read_write and if so call read_write again, possibly later. We could use `recvmsg` with the `MSG_PEEK` and `MSG_DONTWAIT` flags to do this perhaps? 

Also, googling found this reference which confirms libdbus supports level triggered only: https://lists.freedesktop.org/archives/dbus/2012-May/015125.html

**Comment by diwic** [comment]
@ivoisbelongtous Ok, so I pushed the above solution and your test case now works. Your test case was really good, would you mind adding that as a test case to dbus-tokio? Preferrable with delays minimized so it does not take long to run.
