### ISSUE TITLE
blocking::Connection processing time very long.

### ISSUE THREAD

**Issue by flukejones** [diwic/dbus-rs#256]
I'm currently using `blocking::Connection` with an `MTFn` tree to keep things simple. My little app doesn't need async or threaded handling (yet).

But I was trying to understand why my USB transfer times (using dbus to send data to daemon, which is the app) were taking longer than I accounted for. 

`connection.process()` is taking 6ms! Is this usual? It's a very long time. Taken in to account with some polling reads and a 10ms USB transfer I end up needing to budget 17-18ms, so that 6ms time becomes very valuable to get back.

Are there any hints as to what I can try before I move to async? The async part shouldn't be hard really, I separated the required data out from structs that require it, and it's already behind an Rc<RefCell>> so can be changed to Arc<Mutex> when needed.

Speaking of async, I've not really used it before - if I use the async version of connections and `.await` it, that holds up the main loop until it returns, right?

**Comment by diwic** [comment]
D-Bus in general and libdbus (which this code binds to), is not known to be fast. 

If 6 ms is a long time or not I think depends on exactly what is included in that 6 ms, and if you're on a modern CPU or a tiny embedded system. 

The only Rust + dbus benchmark I know of is here: https://github.com/KillingSpark/rust-dbus-comparisons

I don't think moving to async will lead to anything good in terms of performance, my gut feeling is that it would be slower, but that again depends on exactly what's in those 6 ms.

**Comment by flukejones** [comment]
Hmm, dbus-client is fine, it's fast. But a dbus server is what seems to be slow.

I'm passing ten args to a method (10*64byte array). I ended up using tokio-dbus and that seems to have had enough of an impact that the main loop is now throttled by the write to USB (1ms per write, 10 writes).

Still curious about the time use here though, so I'll maybe keep looking at it.

A side question here, my main block of dbus server bits looks like this:

```
connection
        .request_name(DBUS_IFACE, false, true, false)
        .await?;

    let factory = Factory::new_sync::<()>();

    let input: Arc<Mutex<Option<Vec<u8>>>> = Arc::new(Mutex::new(None));
    let effect: Arc<Mutex<Option<Vec<Vec<u8>>>>> = Arc::new(Mutex::new(None));

    let tree = factory.tree(()).add(
        factory.object_path(DBUS_PATH, ()).add(
            factory
                .interface(DBUS_IFACE, ())
                .add_m(
                    factory
                        // method for ledmessage
                        .method("ledmessage", (), {
                            let input = input.clone();

                            move |m| {
                                let bytes: Vec<u8> = m.msg.read1()?;
                                if let Ok(mut lock) = input.try_lock() {
                                    *lock = Some(bytes.to_vec());
                                    let mret = m
                                        .msg
                                        .method_return()
                                        .append1(&format!("Wrote {:x?}", bytes));
                                    return Ok(vec![mret]);
                                } else {
                                    return Err(MethodErr::failed(
                                        "Could not lock daemon for access",
                                    ));
                                }
                            }
                        })
                        .outarg::<&str, _>("reply")
                        .inarg::<Vec<u8>, _>("bytearray"),
                )
                .add_m(
                    factory
                        // method for ledmessage
                        .method("ledeffect", (), {
                            let effect = effect.clone();
                            move |m| {
                                if let Ok(mut lock) = effect.try_lock() {
                                    let mut iter = m.msg.iter_init();
                                    let byte_array: Vec<Vec<u8>> = vec![
                                        iter.read()?,
                                        iter.read()?,
                                        iter.read()?,
                                        iter.read()?,
                                        iter.read()?,
                                        iter.read()?,
                                        iter.read()?,
                                        iter.read()?,
                                        iter.read()?,
                                        iter.read()?,
                                    ];

                                    *lock = Some(byte_array);
                                    let mret =
                                        m.msg.method_return().append1(&format!("Got effect part"));
                                    return Ok(vec![mret]);
                                } else {
                                    return Err(MethodErr::failed(
                                        "Could not lock daemon for access",
                                    ));
                                }
                            }
                        })
                        .outarg::<&str, _>("reply")
                        .inarg::<Vec<u8>, _>("bytearray")
                        .inarg::<Vec<u8>, _>("bytearray")
                        .inarg::<Vec<u8>, _>("bytearray")
                        .inarg::<Vec<u8>, _>("bytearray")
                        .inarg::<Vec<u8>, _>("bytearray")
                        .inarg::<Vec<u8>, _>("bytearray")
                        .inarg::<Vec<u8>, _>("bytearray")
                        .inarg::<Vec<u8>, _>("bytearray")
                        .inarg::<Vec<u8>, _>("bytearray")
                        .inarg::<Vec<u8>, _>("bytearray"),
                ),
        ),
    );
```

I tried to split this out in to a couple of functions so make things clearer but return types trip me up. Do you have any suggestions for organisation here?

**Comment by diwic** [comment]
There's nothing in the code above that looks like it would take 6 ms so maybe you'll have to do some more precise profiling to figure out exactly where it is.

As for organising your tree code, the alternative option is to use `dbus-codegen`, which starts with xml introspection data and generates a trait which you need to implement. But it's not necessarily easier as you have to provide some way from the tree to the object that implements the trait.

**Comment by flukejones** [comment]
Hmm. I don't have any complexity requiring more robust methods like code gen. I'll do some proper profiling through CLion sometime soon, but for now I'll close this as there certainly doesn't seem to be anything to do with dbus-rs here.
