### ISSUE TITLE
as_any() for non-'static RefArg references?

### ISSUE THREAD

**Issue by deifactor** [diwic/dbus-rs#257]
Finally got around to writing the code that I wanted #248 for. Then I ran into a problem:

```
error[E0597]: `*variant.0` does not live long enough
   --> src/hints.rs:161:24
    |
161 |         let mut iter = variant.0.as_iter().unwrap();
    |                        ^^^^^^^^^ borrowed value does not live long enough
...
169 |         let image_data = arg::cast::<Vec<u8>>(iter.next().unwrap()).unwrap();
    |                                               -------------------- cast requires that `*variant.0` is borrowed for `'static`
...
183 | }
    | - `*variant.0` dropped here while still borrowed
```

Here, `variant: Variant<Box<dyn arg::RefArg>>` is the variant I pulled out of the HashMap dbus-rs gives me. Unfortunately, my lifetime-awareness isn't strong enough to fully understand what's going on.

Of course, I can transmute the `&dyn RefArg` I'm iterating over into a `&'static dyn RefArg`, but I'd... rather not. Some way of being able to get at the `Vec<u8>` without having to pray to the gods of undefined behavior would be nice.

Oh, and I can't just `box_clone` since that changes the internal representation into an `InternalArray`, and plus that incurs an extra overhead of boxing the individual pixels up anyway.

**Comment by deifactor** [comment]
After thinking about it a bit more, I realized I can transmute it into a `&(dyn RefArg + 'static)` without extending the lifetime... and that what I'm asking also might be kind of hard since you can't really do anything with an `Any` that isn't known to be `'static` anyway.

**Comment by diwic** [comment]
I think the fix for this is to make sure `box_clone` does not turn the `Vec<u8>` into an `InternalArray`, so that you can actually use `arg::cast::<Vec<u8>>`.

**Comment by deifactor** [comment]
Yeah, that works too. Whatever you feel is best :)

**Comment by diwic** [comment]
So I tried something else, since the box-clone solution would have required either specialization or unsafe (I think). You should be able to descend into the variant using `as_static_inner` without losing the "static", so you could the cast it into the vec. Could you try it and see if it works for you (and please reopen in case it does not)?

**Comment by deifactor** [comment]
Yeah, this works fine.

I'm curious whether it would suffice to somehow propagate the lifetime bounds through `as_iter`, but I don't know enough to say whether that would be possible.
