### ISSUE TITLE
async-std support?

### ISSUE THREAD

**Issue by flukejones** [diwic/dbus-rs#259]
I'm currently using tokio-dbus, and it works pretty well. The only issue is in exploring other crates which might require async-std (or are neutral and you want to use async-std).

Is there any consideration in making either a neutral crate, or an async-std crate?

From what I gather `nonblocking` was meant to be the neutral part, but unless you're experienced with this crate, dbus, async, and an executor it's really quite intimidating to get started.

**Comment by diwic** [comment]
Yep, `nonblock` is meant to be the neutral part. If someone wants to make an dbus-async-std crate I'll be happy to review it (and merge it if it looks good). Right now I'm prioritizing other tasks.

**Comment by diwic** [comment]
Actually async-std support is blocked on support for custom fds, https://github.com/async-rs/async-std/issues/60

**Comment by diwic** [comment]
I'm closing this one for now, feel free to reopen if the async-std starts accepting custom fds.
