### ISSUE TITLE
Just a Question

### ISSUE THREAD

**Issue by mmstick** [diwic/dbus-rs#26]
I'm writing a GUI front-end to systemd for managing system services and although I am able to get a list of unit files from dbus using this wrapper, I'm not quite sure how to go about sending the information needed to disable and enable services through dbus. The following is what I'm using to get the information I need, and this works perfectly.

```
let connection = dbus::Connection::get_private(dbus::BusType::System).unwrap();
let message = dbus::Message::new_method_call("org.freedesktop.systemd1",
	"/org/freedesktop/systemd1", "org.freedesktop.systemd1.Manager", "ListUnitFiles").
	unwrap_or_else(|e| panic!("{}", e));
let reply = connection.send_with_reply_and_block(message, 1000).unwrap();
```

Now I need to call the EnableUnitFiles() and DisableUnitFiles() methods with information I've gained from the first method, which requires a list of pathnames (I'll only do one at a time) with two booleans, yet I'm not quite sure how to accomplish this.

**Comment by diwic** [comment]
// Append a list of strings and two booleans:
    message.append_items(&[["FirstUnitFile", "SecondUnitFile"][..].into(), false.into(), true.into()]);

**Comment by mmstick** [comment]
Thanks, that worked perfectly in my program, available here: https://github.com/mmstick/systemd-manager

It might be a good idea to make that an example in the readme.
