### ISSUE TITLE
lint + clippy warnings in generated code

### ISSUE THREAD

**Issue by lupine** [diwic/dbus-rs#265]
Hi,

One other thing I've come across - `cargo clippy` has complaints about the code `dbus-codegen-rust` generates (v0.5.0), and it seems to be impossible to disable them for *just* the generated code without either putting it in a separate crate, or manually modifying the generated code (which I'd like to avoid, where possible).

I run `rustfmt` on the generated files and commit the result of that, as it's an easily automated step. The clippy thing is more awkward.

I generate a facade module to go along with my autogenerated code, and put:

```rust
#![allow(unused)]
#![allow(clippy::all)]
```

at the top of it. This suppresses some warnings, but not everything; in particular, I still get this kind of thing right now:

```
warning: 6 bindings with single-character names in scope
  --> src/telepathy/account_interface_addressing.rs:18:5
   |
18 |     f: F,
   |     ^
...
27 |     let i = factory.interface(
   |         ^
...
33 |     let h = move |minfo: &tree::MethodInfo<tree::MTFn<D>, D>| {
   |         ^
...
43 |     let m = factory.method("SetURISchemeAssociation", Default::default(), h);
   |         ^
...
48 |     let p = factory.property::<Vec<&str>, _>("URISchemes", Default::default());
   |         ^
...
54 |         let d = dd.as_ref();
   |             ^
   |
   = note: `#[warn(clippy::many_single_char_names)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#many_single_char_names
```

We could probably fix this **specific** message (I get 515 of them in my current generated source), with the only cost being slightly inflated file size, but it's probably a losing battle to make autogenerated code pass linter checks. WDYT to a flag that would allow clippy ignores to be put at the top of each generated file?

...while writing this up, I've realised I can do this with sed too, so I have ;) - https://code.ur.gs/lupine/telepathy-padfoot/src/branch/master/scripts/dbus-codegen#L34 - but it would be nice for this to be supported as part of the tool.

**Comment by diwic** [comment]
How to disable clippy for a specific module is a question for the clippy developers, I don't know how since I don't run clippy myself (hey, it's hard enough to get the code through rustc! 😀)
As long as the generated code is free from compiler/rustc warnings I'm happy.

But you don't need a "facade module", just apply the attributes when you include the module, like this:

    #[allow(clippy::all)]
    mod autogenerated_dbus_code;

**Comment by lupine** [comment]
Ach, I hadn't thought about doing it per-`mod`, that works fine :thumbsup: - thanks!
