### ISSUE TITLE
Could not parse server address error on basic example code

### ISSUE THREAD

**Issue by cbondurant** [diwic/dbus-rs#271]
I attempted to run the basic server example provided in the documentation, and it complies without issue, however when I attempt to run the code it fails on the first call to `dbus::blocking::Connection::new_session`, returning an Err type of `Error: D-Bus error: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix") (org.freedesktop.DBus.Error.BadAddress)`

I am unsure how to resolve this, as my minimal test case that replicates it is the following:
```rust
use dbus::blocking::Connection;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    Connection::new_session()?;
    Ok(())
}
```
I assume this might be a configuration problem with the actual dbus system on my environment, but I have no idea what steps I would need to take next, and was hoping to get some advice, as I cannot tell where in the dbus-rs code this error would originate.

Any advice would be greatly appreciated.

**Comment by diwic** [comment]
Hi,

What distribution are you running and have you reconfigured it in any way w r t dbus? 

Are you running a dbus daemon at all? I e, in my case, running `ps aux` will show one `/usr/bin/dbus-daemon --system` and one `/usr/bin/dbus-daemon --session` where the session one runs as the current user.

Even if you're trying to implement a dbus server, you still need a dbus daemon for the communication between client and server.

**Comment by diwic** [comment]
Also what is the output of: 

    $ export | grep DBUS

**Comment by cbondurant** [comment]
I appreciate the help, `ps aux` shows both a --system and --session daemon for dbus, with the session one being under my user, however I see nothing listed when running `export |grep DBUS`

My system is running debian stable, and I havent done any special configuration. 

However now that I knew what to look for with export + dbus, I was able to find additional information about making sure to use dbus-launch. I think i might be able to work from here, thank you.
