### ISSUE TITLE
[dbus-crossroads] Please ship the license files in the crate

### ISSUE THREAD

**Issue by nullr0ute** [diwic/dbus-rs#275]
Please ship the MIT and Apache 2 license files in the crate.

**Comment by diwic** [comment]
Hi,
this repository contains several crates and I believe all of them already ship the license files you're asking for. Could you clarify?

**Comment by nullr0ute** [comment]
Sorry, I meant dbus-crossroads, at least for 0.2.1 it's not there

**Comment by diwic** [comment]
Okay! Fixed in crossroads 0.2.2
