### ISSUE TITLE
Best way to trigger PropertiesChanged signal?

### ISSUE THREAD

**Issue by ids1024** [diwic/dbus-rs#279]
Dbus-rs already has support for automatically sending this signal when a property is changed by a dbus client. But what is the best way to trigger this from the server, when a client hasn't changed it?

[`Property::set_as_variant`](https://docs.rs/dbus/0.8.4/dbus/tree/struct.Property.html#method.set_as_variant) is the closest thing I can find, which returns a `Message`. But this calls `on_set()`, and it isn't necessarily desirable to do this. In particular, when what the property represents has been changed by mean other than dbus, and we don't want to set it again in response to it having been set.

The other possible solution I see is to manually construct a [`PropertiesPropertiesChanged`](https://docs.rs/dbus/0.8.4/dbus/ffidisp/stdintf/org_freedesktop_dbus/struct.PropertiesPropertiesChanged.html), then call [`.to_emit_message()`](https://docs.rs/dbus/0.8.4/dbus/message/trait.SignalArgs.html#method.to_emit_message), and finally passing that to [`Channel::send()`](https://docs.rs/dbus/0.8.4/dbus/channel/struct.Channel.html#method.send).

Is this an accurate description of the APIs available for this purpose, and the library doesn't (yet) have a good method for doing this? Or am I missing something?

**Comment by diwic** [comment]
> The other possible solution I see is to manually construct a PropertiesPropertiesChanged, then call .to_emit_message(), and finally passing that to Channel::send().

You can use [https://docs.rs/dbus/0.8.4/dbus/tree/struct.Property.html#method.add_propertieschanged](add_propertieschanged) instead of constructing `PropertiesPropertiesChanged` manually.

**Comment by ids1024** [comment]
Ah yes, I guess `add_propertieschanged` works. It seems like a somewhat odd API; it's not really clear exactly how it will mutate the vector passed without looking at the implementation. Though I guess what it does makes sense.

**Comment by diwic** [comment]
If you call add_propertieschanged for several different properties, it will automatically merge properties from the same interface/path into the same message, or otherwise create a new one. Hence the vec.
