### ISSUE TITLE
Connect to an existing signal

### ISSUE THREAD

**Issue by GabRider** [diwic/dbus-rs#283]
Hello,
I am trying to connect to an existing dbus signal. More precisely I would like to retrieve the information sent by the "InterfacesAdded" signal of the "org.freedesktop.DBus.ObjectManager" interface of "org.bluez". When i execute this code :
``` rust
use dbus::ffidisp::stdintf::org_freedesktop_dbus::ObjectManagerInterfacesAdded as IA;
use dbus::{arg, blocking::Connection, message::SignalArgs, Path};
use std::collections::HashMap;
use std::error::Error;
use std::time::Duration;

pub fn signal() {
    let c = Connection::new_system().unwrap();
    // Add a match for this signal
    
    let mr = IA::match_rule(Some(&"org.bluez".into()), None).static_clone();
    c.add_match(mr, |ir: IA, _, _| {
        println!(
            "Interfaces {:?} have been added from bluez on path {}.",
            ir.interfaces, ir.object
        );
        true
    })
    .unwrap();

    // Wait for the signal to arrive.
    loop {
        c.process(Duration::from_millis(1000)).unwrap();
    }
}
```
nothing is printed.

Thank you, in advance for your  help

**Comment by diwic** [comment]
Hi, at a glance, I think the code looks correct. Could you verify that a signal is actually sent from "org.bluez" on the system bus? 

As a test, you could change `Some(&"org.bluez".into())` to `None` to see if you get InterfacesAdded signals from anything at all?

**Comment by GabRider** [comment]
Indeed the code works, I misunderstood how the signal work. it's trigger when a new bluetooth adapter is added and not when a new bluetooth device is detected.

Sorry for the inconvenience and thanks you for your help.
