### ISSUE TITLE
dbus-crossroads can't be used with dbus

### ISSUE THREAD

**Issue by grelltrier** [diwic/dbus-rs#285]
When updating the dbus crate to 0.9.0, dbus-crossroad's cargo.toml was updated but the version of it published on crates.io remained to be 0.2.2. This version still is dependent on dbus 0.8.4 and thus can not be used with 0.9.
Please bump dbus-crossroads version and publish it on crates.io or is there a reason why it would not be compatible?

**Comment by diwic** [comment]
With RefArg now being Send + Sync, that untangles some issues within dbus-crossroads and opens up for better api and/or implementation. So I was planning to do that before releasing a new version. But as I have not done this and probably won't do it this week either, it makes sense to release a dbus-crossroads version as it is now. Thanks for the reminder!

**Comment by ids1024** [comment]
Similarly, the version of `dbus-tokio` on crates.io still seems to depend on dbus 0.8.

**Comment by diwic** [comment]
@ids1024 fixed now, thanks.
