### ISSUE TITLE
tokio 1.0 support

### ISSUE THREAD

**Issue by incker** [diwic/dbus-rs#289]
New version of tokio is released
current version of tokio is 0.2 [Cargo.toml](https://github.com/diwic/dbus-rs/blob/master/dbus-tokio/Cargo.toml)

Better upgrade, to avoid downloading two versions of tokio in projects

**Comment by diwic** [comment]
Ok, feel free to submit a PR!

**Comment by ids1024** [comment]
This seem to require a few straightforward changes, but also `tokio::io::Registration` is no longer publicly exposed. Not sure what to replace the uses of that with (I'd need to look more into exactly how it works).

**Comment by diwic** [comment]
Filed https://github.com/tokio-rs/tokio/issues/3040 upstream, let's see what they say.

**Comment by f-koehler** [comment]
The issue https://github.com/tokio-rs/tokio/issues/3040 was closed and a comment about using `AsyncFd` was added (see https://github.com/tokio-rs/tokio/pull/2903). This new type is available in `tokio` from version `v0.3.2` onwards.

**Comment by qwandor** [comment]
Has anyone been able to make progress on this? Tokio 1.0 is now out, so it would be great to support that.

**Comment by diwic** [comment]
Nothing that I'm aware of. But we should probably target 1.0 rather than 0.3 now, so I changed the title.

**Comment by coolreader18** [comment]
I'm looking into this now, it's definitely possible to replace watch_reg/`Registration::new(mio::EventedFd)` with AsyncFd, but waker_reg is a bit more tricky; I'm not very well-versed in how event loops/reactors work, but I think it might be possible to just use the `Waker` from the `Context` that we get passed, along with a `Arc<Mutex<Waker>>` or similar.
