### ISSUE TITLE
Cross compiling with rust-embedded/cross as alternative method

### ISSUE THREAD

**Issue by jobale** [diwic/dbus-rs#292]
This is an answer to my own problem. Thought it may interest someone trying to cross compile dbus-rs. 
I tried to cross compile a little program for raspberrypi 3. It uses [Blurz](https://crates.io/crates/blurz) which in turn pull dbus-rs as dependency and in the end libdbus.

The program compiled very well on my computer but I encountered linking errors with [rust-embedded/cross](https://github.com/rust-embedded/cross). At compile time the linker tried to use the x86 version of libdbus instead of armhf one. I finally found a way to pass the right locations to the linker through cross. Now libdbus is linked properly and my program compile.
 
I thought that, maybe, it can be of interest for people who wants to use _cross_ to have this information. So here is a little guide:

Tested on Ubuntu 20.04 | rustc 1.47.0

- Install [rust-embedded/cross](https://github.com/rust-embedded/cross)
- In your project directory, create a **Cross.toml** file: `touch Cross.toml`
Add this code in it:

> ```
> [target.armv7-unknown-linux-gnueabihf]
> image = "rustcross:dbus-armhf"
> 
> [build.env]
> passthrough = [
> 	"RUSTFLAGS",
> ]
> ```

- In your project directory create a **Dockerfile**: `touch Dockerfile`
Put this code in it: 

> ```
> # Base image for rapsberrypi 3 target
> FROM rustembedded/cross:armv7-unknown-linux-gnueabihf
> 
> # Install libdbus libraries and pkg-config
> RUN dpkg --add-architecture armhf && \
> 	    apt-get update && \
> 	    apt-get install --assume-yes libdbus-1-dev libdbus-1-dev:armhf pkg-config
> ```

For whatever reason, _in the docker image_, armhf libraries are installed in at least 2 locations. That's the reason of all my troubles:
- /usr/arm-linux-gnueabihf/lib/
- /usr/lib/arm-linux-gnueabihf/

- Cross needs to know those locations. We pass them to the compiler through a command flag. For convenience I put it in a bash script: 

> ```
> #!/bin/bash
> set -o errexit
> set -o nounset
> set -o pipefail
> set -o xtrace
> 
> readonly TARGET_ARCH=armv7-unknown-linux-gnueabihf
> readonly LINK_FLAGS='-L /usr/arm-linux-gnueabihf/lib/ -L /usr/lib/arm-linux-gnueabihf/'
> 
> RUSTFLAGS=${LINK_FLAGS} cross build --release --target=${TARGET_ARCH}
> 
> ```

Some more explanations for newcomers like me:

- Cross command act as cargo command (e.g: `cross build` is the same as `cargo build` but for cross-compiling).
- In Cross.toml,  `passthrough = [ "RUSTFLAGS",]` is what enable us to pass flags/parameters to the compiler in the docker image.

In my research for an answer I landed on the [Cross compiling dbus](https://github.com/diwic/dbus-rs/blob/master/libdbus-sys/cross_compile.md) page. I would have loved to have this alternate method leveraging rust-embedded/cross. Maybe considering adding it to the page?

**Comment by diwic** [comment]
Hi and thanks for sharing!

It's been over a year since "cross compiling dbus" was written, and likely rust-embedded/cross was not as mature as it is now (or perhaps didn't even exist).

Is rust-embedded/cross now the recommended way of cross compiling Rust in general, or is it more complex than that? I'm not following the embedded Rust community closely.

**Comment by jobale** [comment]
Hi,
I honestly don't know if it is the _recommended way_. The _Cross_ tool is actively developed by the [rust embedded group tool team](https://github.com/rust-embedded/wg#the-tools-team). The same team is responsible of several other [projects](https://github.com/rust-embedded/wg#projects-9) in the Rust ecosystem.

I didn't find any clear statement about Cross being **the** way of doing cross-compilation. However, the pace of development and the usability of the tool make it a really nice addition to my workflow:

- No more files littering my system. Everything is in docker images.
- Cross behave like cargo so I don't need to learn new command.
- I can test through cross as if I was on my target system.
- I just have to take care of adding dependencies in the docker image. The base docker image contain everything else for cross-compiling.

Honestly, without Cross, I wouldn't do cross-compiling for more than one target at a time and without linking against C libs! It's just too much hassle without this tool. 
That being said, one pain point of cross-compiling for me is linking against C libraries. On that specific area, Cross doesn't help that much (but doesn't add problem either).

**Comment by diwic** [comment]
Thanks! Your instructions have been added now.

**Comment by plafer** [comment]
There's just a little step missing: after adding the Dockerfile, you need to run `docker build -t rustcross:dbus-armhf .`. Otherwise, everything works perfectly!

**Comment by ThePicoNerd** [comment]
I'm trying to cross-compile for my Pi Zero. As far as I understand, it's running on ARMv6 and thus I need to install `armel` rather than `armhf` packages. Naïve as I am, I tried to just replace all occurences of `armhf` with `armel` and initially, it seems to work. However, apparently there is no `libdbus-1-dev:armel` package:
```
Unable to locate package libdbus-1-dev:armel
```
Any ideas? Am I a complete idiot?
