### ISSUE TITLE
Debugging errors for failed methods

### ISSUE THREAD

**Issue by WhyNotHugo** [diwic/dbus-rs#302]
I'm working on a D-Bus method which is failing (I'm certain the issue is my code). However, I'm not entirely sure how to further debug this; my code simply fails silently and I'm not sure what I should do for `dbus-rs` to actually show some error of what went wrong (even panicing would be fine since I'm still in a quite exploratory phase).

```rust

#[derive(Debug)]
struct Notification {
    app_name: String,
    replaces_id: u32,
    app_icon: String,
    summary: String,
    body: String,
    actions: Vec<String>,
    hints: HashMap<String, Variant<Box<dyn RefArg + 'static>>>,
    expire_timtout: u32,
}

// ...

.add_m(
    f.method("Notify", (), move |m| {
        let mut iter = m.msg.iter_init();

        println!("got a message");

        let notification = Notification {
            app_name: iter.read()?,
            replaces_id: iter.read()?,
            app_icon: iter.read()?,
            summary: iter.read()?,
            body: iter.read()?,
            actions: iter.read()?,
            hints: iter.read()?,
            expire_timtout: iter.read()?,
        };
        println!("{:#?}", notification);

        let id = 12;
        let mret = m.msg.method_return().append1(id);
        Ok(vec![mret])
    })
    .outarg::<&u32, _>("id")
    .inarg::<&str, _>("app_name")
    .inarg::<&u32, _>("replaces_id")
    .inarg::<&str, _>("app_icon")
    .inarg::<&str, _>("summary")
    .inarg::<&str, _>("body")
    .inarg::<Vec<&str>, _>("actions")
    .inarg::<Dict<&str, Variant<()>, ()>, _>("hints")
    .inarg::<&u32, _>("expire_timeout"),
)
```

I believe that `hints: iter.read()?,` is what fails; I'm properly not getting the types right here. However, when I run this, I simply get:

```
got message
```

And nothing else. Is there a way to print the errors of what's going wrong here?

---

Side question: is is possible to de-duplicate code here: my struct and the `inarg` both model the exact same thing twice.

**Comment by WhyNotHugo** [comment]
Update: I managed to figure out the specific error in this particular snippet, but I'm still curious about how to better debug this (e.g.: actually figure out what errors).

Normal code would just panic, but errors inside dbus methods seem to be swallowed...?

**Comment by diwic** [comment]
> Is there a way to print the errors of what's going wrong here?

Sure, just wrap all the "read"s into a separate function or closure (that returns a `Result<Notification, TypeMismatchError>`) and print the result.

 > possible to de-duplicate code here: my struct and the inarg both model the exact same thing twice.

This is one of the design flaws I've tried to improve in `dbus-crossroads`, which is better, newer and shinier than the `dbus-tree` you're using :-)

 > errors inside dbus methods seem to be swallowed

The errors are returned to the client who called the method. While that would be the right thing to do in most cases, it isn't the most helpful for your use case...hmm...

**Comment by WhyNotHugo** [comment]
Thanks, I'll keep that in mind! :+1: 

> This is one of the design flaws I've tried to improve in dbus-crossroads, which is better, newer and shinier than the dbus-tree you're using :-)

Oh, nice. For a new project, would you recommend I went with the latter, or is it too fresh / unstable yet?

> The errors are returned to the client who called the method. While that would be the right thing to do in most cases, it isn't the most helpful for your use case...hmm...

Yeah, during development it's far handier to print them -- the type of errors one sees while experimenting are pretty different from what'd be expected with a stable codebase.

**Comment by diwic** [comment]
> > This is one of the design flaws I've tried to improve in dbus-crossroads, which is better, newer and shinier than the dbus-tree you're using :-)
> 
> Oh, nice. For a new project, would you recommend I went with the latter, or is it too fresh / unstable yet?

I would. I don't think it's unstable, and it would be helpful for me as well if more people were trying it out.

**Comment by WhyNotHugo** [comment]
It's not clear to me how to avoid this duplication with `dbus-crossroads` though. The only example also duplicates arguments names (though not the types):

https://github.com/diwic/dbus-rs/blob/master/dbus-crossroads/examples/server_cr.rs#L39

Is it just the types that one avoids duplicating?

**Comment by diwic** [comment]
> Is it just the types that one avoids duplicating?

The names are written twice, one time as strings and one as identifiers. I've thought of making a macro to get rid of that, but I'm not sure if that would be over engineering.

Notice how the types are already correct inside the closure, so no more `iter.read()?`. That's the bigger win for ergonomics - but if you have the wrong closure arguments that's an error being returned to the client and your closure is never called.

**Comment by WhyNotHugo** [comment]
It's a great improvement in that, rather than deal with a "message", my method receives the right data in the right types (it's a bit higher level and easier to think about).

I'm struggling a bit to define `ArgAll` though. The syntax is a bit too advanced for me...

```rust
impl dbus::arg::ArgAll for Notification {
    type strs = (); // ???
    fn strs_sig<F: FnMut(&'static str, Signature<'static>)>(_: Self::strs, _: F) {
         // ???
    }
}
// ...

b.method(
    "Notify",
    (
        "app_name",
        "replaces_id",
        "app_icon",
        "summary",
        "body",
        "actions",
        "hints",
        "expire_timeout",
    ),
    ("id",),
    |ctx: &mut Context, hello: &mut Hello, notification: Notification| {
```

Should I just use raw parameters here?

**Comment by diwic** [comment]
> Should I just use raw parameters here?

That's what's expected. Implementing `strs_sig` manually would lead to more code.

**Comment by WhyNotHugo** [comment]
> I've thought of making a macro to get rid of that, but I'm not sure if that would be over engineering.

From an user-of-the-library point of view, a simple macro for that would be great.

I'm going to close this since my doubt has been resolved. Thanks for all the help! :)

**Comment by WhyNotHugo** [comment]
I finished porting my code to `crossroads`, and yeah, the ergonomics are a lot better and the code is a lot easier to structure!

Thanks for the help!
