### ISSUE TITLE
Any way to open a connection to a bus identified by an address?

### ISSUE THREAD

**Issue by DataTriny** [diwic/dbus-rs#315]
Hello,
I am experimenting with D-Bus and I need to open a connection to a bus which I know the address.

The address looks something like this: `unix:abstract=/tmp/dbus-OOudoYAa3s,guid=c7bdeec81d858d0bf589a9b76022b9e5`.

For testing purpose, I added this to `src/blocking.rs`:

```rust
pub fn open(addr: &str) -> Result<Self, Error> {
    Channel::open_private(addr).map(From::from)
}
```

But now I know that I am still missing the bus registration part, however I am not really sure on how and where to put it.

I see that this feature exists on the legacy ffidisp module. Do you plan on adding it to the blocking and nonblock modules as well?

Kind regards.

Arnold

**Comment by diwic** [comment]
For "custom" usages of channel, like the one you describe, you can do:

    let x = Channel::open_private(addr)?;
    x.register()?;
    let y: Connection = x.into();

Feel free to reopen the issue if this does not help. Thanks!

**Comment by DataTriny** [comment]
Hi @diwic,
This perfectly answers my question.
Thank you for your fast reply, and for this quite amazing crate!
