### ISSUE TITLE
nonblock::SyncConnection::request_name() appears to hang forever

### ISSUE THREAD

**Issue by jbaublitz** [diwic/dbus-rs#316]
When I call `request_name()`, it appears to correctly acquire the name based on `busctl monitor` but `.await` never returns.

**Comment by diwic** [comment]
The only implementor currently is the dbus-tokio crate, are you using that to create the `SyncConnection`? (If not, then start doing so)
Otherwise please post a code example where the issue can be replicated. Thanks!

**Comment by jbaublitz** [comment]
I'm leaving this just in case anyone else bumps into this.

The steps I needed to take to make this work were essentially:

```rust
let (io, conn) = dbus_tokio::connection::new_system_sync()?;

tokio::spawn(io);

conn.request_name(YOUR_NAME_HERE, false, true, true).await?;

let match_msg = conn.add_match(MatchRule::new_method_call()).await?;
// Dropping _match_msg appears to cause message processing to stop.
let (_match_msg, mut stream) = match_msg.msg_stream();
while let Some(msg) = stream.next().await {
    ...
} 
```

Closing. Thanks for the help!
