### ISSUE TITLE
Behavior when method called on a non-existant path

### ISSUE THREAD

**Issue by mulkieran** [diwic/dbus-rs#317]
We've noticed some behavior of our D-Bus layer with respect to non-existant paths which is a bit surprising and which isn't consistent with the behavior of systemd. Generally speaking, systemd refuses all calls of methods on non-existant paths, more or less like this:

```
# busctl call org.freedesktop.systemd1 /junk org.freedesktop.DBus.ObjectManager GetManagedObjects
Call failed: Unknown object '/junk'
```

stratisd is behaving differently for different interfaces. For Introspectable:

```
$ busctl call org.storage.stratis2 /junk org.freedesktop.DBus.Introspectable Introspect
s "<!DOCTYPE node PUBLIC \"-//freedesktop//DTD D-BUS Object Introspection 1.0//EN\"\n\"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd\">\n<node>\n</node>\n"
```

i.e., it returns a chunk of empty introspection data.

For GetManagedObjects:

```
$ busctl call org.storage.stratis2 /junk org.freedesktop.DBus.ObjectManager GetManagedObjects
Call failed: Method "GetManagedObjects" with signature "" on interface "org.freedesktop.DBus.ObjectManager" doesn't exist
```

For most interfaces, the behavior is like that for GetManagedObjects.

Is this what you intended?

We're trying to follow up a question from a potential user who expects our D-Bus interface to behave more like systemd's.
I scrutinized the D-Bus spec, and couldn't find any place in the spec where method calls on non-existent object paths were discussed.

**Comment by diwic** [comment]
I tried a few others:

    $ busctl call org.freedesktop.ModemManager1 /junk org.freedesktop.DBus.Introspectable Introspect
    s "<!DOCTYPE node PUBLIC \"-//freedesktop//DTD D-BUS Object Introspection 1.0//EN\"\n                      \"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd\">\n\n<node>\n</node>\n"

    $ busctl call org.freedesktop.NetworkManager /junk org.freedesktop.DBus.Introspectable Introspect
    s "<!DOCTYPE node PUBLIC \"-//freedesktop//DTD D-BUS Object Introspection 1.0//EN\"\n                      \"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd\">\n\n<node>\n</node>\n"

    $  busctl call com.ubuntu.USBCreator /junk org.freedesktop.DBus.Introspectable Introspect
    s "<!DOCTYPE node PUBLIC \"-//freedesktop//DTD D-BUS Object Introspection 1.0//EN\"\n\"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd\">\n<node>\n</node>\n"

Looks like systemd is the one standing out! That said, it seems more logical to return an error in this case, which I believe is what `dbus-crossroads` would do - I suspect that stratis has not migrated from `dbus-tree` yet, or has it?

**Comment by mulkieran** [comment]
> I tried a few others:
> 
> ```
> $ busctl call org.freedesktop.ModemManager1 /junk org.freedesktop.DBus.Introspectable Introspect
> s "<!DOCTYPE node PUBLIC \"-//freedesktop//DTD D-BUS Object Introspection 1.0//EN\"\n                      \"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd\">\n\n<node>\n</node>\n"
> 
> $ busctl call org.freedesktop.NetworkManager /junk org.freedesktop.DBus.Introspectable Introspect
> s "<!DOCTYPE node PUBLIC \"-//freedesktop//DTD D-BUS Object Introspection 1.0//EN\"\n                      \"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd\">\n\n<node>\n</node>\n"
> 
> $  busctl call com.ubuntu.USBCreator /junk org.freedesktop.DBus.Introspectable Introspect
> s "<!DOCTYPE node PUBLIC \"-//freedesktop//DTD D-BUS Object Introspection 1.0//EN\"\n\"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd\">\n<node>\n</node>\n"
> ```
> 
> Looks like systemd is the one standing out! That said, it seems more logical to return an error in this case, which I believe is what `dbus-crossroads` would do - I suspect that stratis has not migrated from `dbus-tree` yet, or has it?

Thanks for pointing this out!

Yes, we're still on dbus-tree.

**Comment by diwic** [comment]
@mulkieran I think this is some fallback behavior of libdbus, so moving away from `ffidisp` to `blocking` or `nonblock` connections would change this behavior. Closing for now, feel free to reopen in case this does not help.
