### ISSUE TITLE
Arguments to dbus_message_iter_open_container are incorrect

### ISSUE THREAD

**Issue by agrover** [diwic/dbus-rs#32]
```process 11575: arguments to dbus_message_iter_open_container() were incorrect, assertion "(type == DBUS_TYPE_ARRAY && contained_signature && *contained_signature == DBUS_DICT_ENTRY_BEGIN_CHAR) || (contained_signature == NULL || _dbus_check_is_valid_signature (contained_signature))" failed in file dbus-message.c line 2878.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace```

Looks like this is in `iter_append_array`. The typesig for the failing operation is `{sv}` and the a parameter is `[DictEntry(Str("BlockDevices"), Variant(Array([Struct([Str("/dev/vdd"), UInt32(0)]), Struct([Str("/dev/vdb"), UInt32(0)]), Struct([Str("/dev/vdc"), UInt32(0)])], "(su)")))]`

For reference, the code where I'm building the MessageItem is https://github.com/agrover/froyo/blob/master/src/dbus_api.rs#L38 in case the error lies there.

**Comment by diwic** [comment]
Hmm. Looking at the dbus code that fails this assertion, there is a comment that says:

     2871   /* this would fail if the contained_signature is a dict entry, since
     2872    * dict entries are invalid signatures standalone (they must be in
     2873    * an array)
     2874    */

...and looking at the type of your parameter, it seems like you have a `DictEntry` which is not inside an array. 

Apparently this is a restriction of D-Bus itself, which I was unaware of it until today. I wonder if there's something one can do to prevent it on the Rust side...

**Comment by diwic** [comment]
Looking at it now, it's actually in the [spec](http://dbus.freedesktop.org/doc/dbus-specification.html) too. Maybe it makes sense to ditch `DictEntry` altogether and replace it with a `Dict` which would be the entire array of dict entries. Unfortunately it seems like I can't represent that as a map, because the spec allows floating point keys (argh).

**Comment by agrover** [comment]
Just not support floating-point keys? :smile: Or convert to u64?

**Comment by diwic** [comment]
Hi,
I just fixed a bug which is related to having an Array directly inside a Variant, which you have. Could you see if [this commit](https://github.com/diwic/dbus-rs/commit/06522506d8a593dcd3aca56b74dfd79a14ab26e0) fixes your problem as well?

**Comment by agrover** [comment]
Works now! Much thanks! Closing.
