### ISSUE TITLE
Packaging dbus-tree for Fedora

### ISSUE THREAD

**Issue by jbaublitz** [diwic/dbus-rs#322]
Hi @diwic! I'm packaging dbus-tree for Fedora right now. It appears that the crate for dbus-tree doesn't include the license files that need to be distributed according to the terms of ASL 2 and MIT. Would you be willing to put up a 0.9.1 release including the desired license files so I can package it? Thanks!

**Comment by diwic** [comment]
Ok, done now. Enjoy!
