### ISSUE TITLE
What is the preferred way to manually emit ProperiesChanged signal when writing server code with crossroads?

### ISSUE THREAD

**Issue by nadyushka228** [diwic/dbus-rs#335]
AFAICU the only way to do this is to manually construct a signal message (so, basically copy-paste [`make_emits_message()`](https://github.com/diwic/dbus-rs/blob/740a9e7f1a04d31565960755f6f56152ec24c75f/dbus-crossroads/src/stdimpl.rs#L38-L52)) and send it with `Context.push_msg()`. Is is supposed to be like this?

**Comment by diwic** [comment]
Hi!

Indeed, it seems you're right and there's room for improvement here. Do you have a good suggestion of how to improve the API to make it easier to send this signal (and maybe other signals as well)?

**Comment by nadyushka228** [comment]
I almost like the way they do it in [`GDbus`](https://developer.gnome.org/gio/stable/gdbus-convenience.html), but they have a different architecture. Basically, they have a hashtable that stores the properties' values, implement D-Bus property getter/setter as functions that get/set property from/in this hashtable, and also emit `PropertiesChanged` signal every time a property in this hashtable is changed (either from the inside of the program or from the outside via D-Bus `org.freedesktop.DBus.Properties.Set` method). The only real downside of this way I have experienced is that you're unable to properly implement a getter for a property that constantly changes (eg. [`org.mpris.MediaPlayer2.Player.Position`](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:Position)).

So, I suggest to add a possibility to set/get properties this way in Crossroads. 

BTW, my initial statement was a bit wrong, because you need to create `ProperiesProperiesChanged` and then send it via `Connection.send()`, which sounds much less clunky then method in original post, so now I doubt if the issue makes sense.

**Comment by diwic** [comment]
Over the years of developing dbus-rs I've encountered both those who thing GDBus is awesome and those who think it's terrible :-)

In the end I decided against storing the properties inside the crossroads instance, both for the reason you specify (properties that constantly change) and also because of double storage: you likely store the value of the property somewhere else as well, which means that there is a potential footgun where you update the value somewhere else but not in Crossroads' hashmap.

**Comment by nadyushka228** [comment]
I didn't suggest to store **all** properties like they do in `GDBus`, I don't think that's the right way. Instead, I suggested to add an **option** for storing certain properties in `Crossroads` instance. This way doesn't have the downsides you mentioned but is a bit handy in some situations.

Another suggestion (if you don't want to add storing option) is to add some easy way to emit `PropertyChanged` signal from outside of getter and setter. I think of adding a method to `PropContext` and a way to use this struct outside of getter/setter.

**Comment by diwic** [comment]
Test case here if that helps: https://github.com/diwic/dbus-rs/blob/master/dbus-crossroads/src/test.rs#L48
