### ISSUE TITLE
Question: about the object path hierarchy 

### ISSUE THREAD

**Issue by chirping78** [diwic/dbus-rs#339]
I found some dbus services have the object path looks like a directory, like this one (take `org.freedesktop.Notifications` as an example):
```
$ gdbus introspect --session --dest org.freedesktop.Notifications --object-path / --recurse
node / {
  node /org {
    node /org/gnome {
      node /org/gnome/Mutter {
        node /org/gnome/Mutter/DisplayConfig {
          interface org.freedesktop.DBus.Properties {
            methods:
              Get(in  s interface_name,
                  in  s property_name,
                  out v value);
```
But when I use the crossroad, and insert the interface like this
```
cr.insert("/a/b/c",
```
I only got 
```
node / {
  node /a/b/c {
```
but I expect the hierarchy looks like:
```
node / {
  node /a {
    node /a/b {
      node /a/b/c {
```
How do I achieve this effect?

**Comment by diwic** [comment]
Hi, 
It seems like what you're describing is not the usual behavior. E g check with

    dbus introspect --session --dest org.freedesktop.DBus --object-path / --recurse

And you'll find `/` and `/org/freedesktop/DBus` only, no `/org` or `/org/freedesktop` nodes.

That said, if you still want `/a` and `/a/b` nodes as well, just insert them:

    cr.insert("/a", &[], ());
    cr.insert("/a/b", &[], ());

**Comment by diwic** [comment]
Feel free to reopen this issue if the above does not answer your question. Thanks!
