### ISSUE TITLE
publish to crates.io for bugfix?

### ISSUE THREAD

**Issue by hwchen** [diwic/dbus-rs#35]
Hello,

I also commented in the now-closed issue #33, which fixed the bug, but wasn't sure if you'd be notified.

But I was wondering if you could publish a new version to crates with the bugfix. I'd like to publish my secret service library, which depends on the bugfix.

I don't think I can use your github repo as the dependency source for crates.io, but if there's another workaround for now I'd be happy to do it.

**Comment by diwic** [comment]
Sorry. Indeed I should make a new version and publish to crates.io. I hope to have time for this in a day or two (I've just been swamped with other things).

**Comment by hwchen** [comment]
Thanks!

**Comment by diwic** [comment]
Pushed now. You don't see it on github because I've pushed a few things to master afterwards that aren't finished yet, but it's this commit https://github.com/diwic/dbus-rs/commit/fc6ed34fd9c280f117fcc9c03da699d15355e03f plus just a changed version number.

**Comment by hwchen** [comment]
Thanks a bunch!
