### ISSUE TITLE
Clearer Documentation on How Matches Occur

### ISSUE THREAD

**Issue by msdrigg** [diwic/dbus-rs#358]
I spent an hour or two trying to debug an issue where there were no message notifications captured from dbus for a MatchRule. I was filtering for the correct object and path, but the arguments to my closure didn't match the message that was being sent. I eventually learned that dbus-rs drops all messages silently that don't match the closure's arguments. This behavior was quite unexpected for me. I would expect a parse-error or something when a message matches a MatchRule but cannot be formatted according to the arguments given.

Maybe there could be a new api for this that emits errors somehow, but at the least I think there needs to be some documentation under MatchRule or Proxy that clearly states that all signals not matching the closure's arguments get dropped silently, and listing a argument format that will match all messages. I am not a dbus expert, so maybe this is standard with dbus messaging handling, but I think this should be stated for beginners.

**Comment by diwic** [comment]
Hi,

I agree that it would be good to have this stated more clearly. Where would you have looked for this documentation; and if you are qualified to add it there, could you submit a PR?

**Comment by msdrigg** [comment]
I will write up a PR to the best of my understanding and I'll let you make any changes if anything isn't quite right. There are a lot of places that matching with a callback comes up. `MsgMatch` and `MatchRule` come to mind as possibilities but also `proxy::match_signal`. 

Maybe a little note under `MatchRule` would be bset because you always need to use MatchRule whenever matching for anything so anyone will have to see it? Also potentially a comment in one of the matching examples because those are targeted at beginners.

**Comment by diwic** [comment]
Closing due to lack of interest/activity.

**Comment by msdrigg** [comment]
Fair
