### ISSUE TITLE
Introspect output on Manager object seems to be missing object paths with similar names

### ISSUE THREAD

**Issue by bgurney-rh** [diwic/dbus-rs#360]
Hello,

I'm currently trying to diagnose an issue in the Stratis project where some object paths are being dropped due to what appears to be an algorithm that tries to detect duplicate entries.  After asking the systemd team via an issue, it appears that the Introspect data does not contain the node that is "dropped" during this behavior.  (I apologize ahead of time if I'm mixing up terminology.)

Stratis is currently using dbus version "0.9.0", and dbus-tree "0.9.0".

Basic steps to reproduce:

Start the stratisd daemon (either by "systemctl start stratisd", or "/usr/libexec/stratisd --log-level debug". Using the "stratis" command, create a test pool on a device (i.e.: "stratis pool create spool1 /dev/vdb1"), then create several filesystems (i.e.: "stratis fs create spool1 sfs1", "stratis fs create spool1 sfs2", and so on).  Alternatively, create many pools and a few filesystems, to the point where the object count exceeds ten.

What appears to happen is that object names that start with the same characters before the end of the string are filtered out.  For example, if "1" is present, "10" will not appear; if "2" is present, "20" will not appear, and so on. 

Here's a quick sample of what occurs when the object count exceeds ten:

Output from `busctl tree org.storage.stratis3`:
```
└─/org
  └─/org/storage
    └─/org/storage/stratis3
      ├─/org/storage/stratis3/0
      ├─/org/storage/stratis3/1
      ├─/org/storage/stratis3/2
      ├─/org/storage/stratis3/3
      ├─/org/storage/stratis3/4
      ├─/org/storage/stratis3/5
      ├─/org/storage/stratis3/6
      ├─/org/storage/stratis3/7
      ├─/org/storage/stratis3/8
      └─/org/storage/stratis3/9
```

Output from `stratis report managed_objects_report | grep org/storage/stratis.*\: | sort` (a Stratis managed objects report output that looks similar to what would ideally appear in the above "busctl tree" output):
```
    "/org/storage/stratis3/0": {
    "/org/storage/stratis3/1": {
    "/org/storage/stratis3/10": {
    "/org/storage/stratis3/2": {
    "/org/storage/stratis3/3": {
    "/org/storage/stratis3/4": {
    "/org/storage/stratis3/5": {
    "/org/storage/stratis3/6": {
    "/org/storage/stratis3/7": {
    "/org/storage/stratis3/8": {
    "/org/storage/stratis3/9": {
```

An excerpt of the output from `busctl --verbose call org.storage.stratis3 /org/storage/stratis3 org.freedesktop.DBus.Introspectable Introspect`:
```
  <node name="0"/>
  <node name="1"/>
  <node name="2"/>
  <node name="3"/>
  <node name="4"/>
  <node name="5"/>
  <node name="6"/>
  <node name="7"/>
  <node name="8"/>
  <node name="9"/>
</node>";
```

**Comment by diwic** [comment]
Hi and thanks for the report! I believe this is fixed in the commit above, feel free to test and let me know if you need a release.

**Comment by bgurney-rh** [comment]
Confirmed; I rebuilt with this commit, and here's the output of `busctl tree org.storage.stratis3`, using the same test (1 pool with 20 filesystems):
```
└─/org
  └─/org/storage
    └─/org/storage/stratis3
      ├─/org/storage/stratis3/0
      ├─/org/storage/stratis3/1
      ├─/org/storage/stratis3/10
      ├─/org/storage/stratis3/11
      ├─/org/storage/stratis3/12
      ├─/org/storage/stratis3/13
      ├─/org/storage/stratis3/14
      ├─/org/storage/stratis3/15
      ├─/org/storage/stratis3/16
      ├─/org/storage/stratis3/17
      ├─/org/storage/stratis3/18
      ├─/org/storage/stratis3/19
      ├─/org/storage/stratis3/2
      ├─/org/storage/stratis3/20
      ├─/org/storage/stratis3/21
      ├─/org/storage/stratis3/3
      ├─/org/storage/stratis3/4
      ├─/org/storage/stratis3/5
      ├─/org/storage/stratis3/6
      ├─/org/storage/stratis3/7
      ├─/org/storage/stratis3/8
      └─/org/storage/stratis3/9
```
