### ISSUE TITLE
Help with building a struct from a value in `PropMap` (crossroads)

### ISSUE THREAD

**Issue by Toqozz** [diwic/dbus-rs#363]
Hey, I searched around and tried to find some examples relating to this but couldn't find anything, apologies if there's some information on how to do this somewhere.

I'm trying to implement the [Desktop Notifications Specification](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html), specifically I'm trying to grab the `image-data` hint from the `hints` component.  The signature for this property is `iiibiiay`.

This is one of my attempts:
```rust
pub struct DBusImage {
    pub width: i32,
    pub height: i32,
    pub rowstride: i32,
    pub one_point_two_bit_alpha: bool,
    pub bits_per_sample: i32,
    pub channels: i32,
    pub data: Vec<u8>,
}

impl dbus_codegen::OrgFreedesktopNotifications for Notify {
    ...

    fn notify(&mut self, app_name: String, replaces_id: u32, app_icon: String, summary: String, body: String, actions: Vec<String>, hints: arg::PropMap, expire_timeout: i32) -> Result<u32, dbus::MethodErr> {
        let var = hints.get("image-data");
        if let Some(img) = var {
            if let Some(mut iter) = img.0.as_iter() {
                // Just trying to cast one thing as an example, but maybe there is a way to easily pull everything into the struct?
                // error: cast requires that `hints` is borrowed for `'static`
                let w = arg::cast::<i32>(iter.next().unwrap());
            }
        }

        Ok(0)
    }
    ...
}
```

I was looking at the [argument guide](https://github.com/diwic/dbus-rs/blob/master/dbus/examples/argument_guide.md), but most of the examples are for doing `value.read()` into the specific variant.  I noticed that I can probably do `value.as_i64().unwrap() as i32` or something like that, but I feel like I'm just completely missing something.

I should mention also that I had this working before with  `dbus-tree` and am trying to migrate over.  Here's what I did previously:
```rust
impl<'a> arg::Get<'a> for DBusImage {
    fn get(i: &mut arg::Iter) -> Option<Self> {
        let width = i.read::<i32>().ok()?;
        let height = i.read::<i32>().ok()?;
        let rowstride = i.read::<i32>().ok()?;
        let one_point_two_bit_alpha = i.read::<bool>().ok()?;
        let bits_per_sample = i.read::<i32>().ok()?;
        let channels = i.read::<i32>().ok()?;
        let data = i.read::<Vec<u8>>().ok()?;

        Some(
            DBusImage {
                width,
                height,
                rowstride,
                one_point_two_bit_alpha,
                bits_per_sample,
                channels,
                data,
        })
    }
}

impl<'a> arg::Get<'a> for Value {
    fn get(i: &mut arg::Iter) -> Option<Self> {
        let arg_type = i.arg_type();
        if let ArgType::Invalid = arg_type {
            return None;
        }
        let signature = i.signature();

        match arg_type {
            // This seems ugly, but is definitely the image data struct.
            ArgType::Struct if *signature == *"(iiibiiay)" =>
                i.recurse(ArgType::Struct).and_then(|mut iter| iter.get::<DBusImage>()).map(Value::Struct),
            ArgType::Boolean => i.get::<bool>().map(Value::Bool),
            ...
            _ => None,
        }
    }
}
```

Thanks for anything here!

**Comment by diwic** [comment]
Hmm, so structs are internally represented as `VecDequeue<Box<RefArg>>` and I think we could commit to that being so.

So will this work?

    let imageData: Option<&VecDeque<Box<dyn RefArg>>> = prop_cast(&hints, 'image-data');

If it does not, could you debug print `hints` and post here?

**Comment by diwic** [comment]
I have updated the argument guide slightly, not sure if it would have helped you but maybe :-)

**Comment by Toqozz** [comment]
Thanks so much for your help!  I will get back to you tomorrow when I get a chance to try this.

**Comment by Toqozz** [comment]
Ok, that solved the lifetime issue, here's what I have now:
```rust
fn notify(&mut self, app_name: String, replaces_id: u32, app_icon: String, summary: String, body: String, actions: Vec<String>, hints: arg::PropMap, expire_timeout: i32) -> Result<u32, dbus::MethodErr> {
    let image_data: Option<&VecDeque<Box<dyn RefArg>>> = prop_cast(&hints, "image-data");
    let mut it = image_data.unwrap().iter();
    if let Some(img) = image_data {
        let width = dbus::arg::cast::<i32>(&img[0]);
        let height = dbus::arg::cast::<i32>(&img[1]);
        let rowstride = dbus::arg::cast::<i32>(&img[2]);
        let one_point_two_bit_alpha = dbus::arg::cast::<bool>(&img[3]);
        let bits_per_sample = dbus::arg::cast::<i32>(&img[4]);
        let channels = dbus::arg::cast::<i32>(&img[5]);
        let data = dbus::arg::cast::<Vec<u8>>(&img[6]);
    }

    Ok(0)
}
```

This seems to correctly fill all the variables when an `image-data` hint is present.

Index issues/safety/etc aside, is this the correct way to do that?

If you like, I can post a better example that could maybe be used in the arguments guide once I've cleaned everything up.

**Comment by diwic** [comment]
>     let mut it = image_data.unwrap().iter();

This row can be skipped (the `it` variable is not used anyway), otherwise it looks correct, and all improvements to the documentation are welcome :-)
