### ISSUE TITLE
Documentation for Signals and Server-Side Properties

### ISSUE THREAD

**Issue by Kilobyte22** [diwic/dbus-rs#37]
While writing an application making quite a bit of use of dbus i realized nowhere is documented how to use signals. Furthermore it is not documented how a server might implement properties. The rustdoc documentation is not really useful. Both of those are fairly important features of dbus, so documentation should be added.

**Comment by diwic** [comment]
Ok, how do you suggest we best improve the rustdoc so that it is obvious how to make use of signals and server-side properties?

**Comment by Kilobyte22** [comment]
I think the approach you picked with the client is quite nice. Add a module wide doc comment with a code example. Furthermore you might want to add the corresponding examples to the examples/ directory.

**Comment by diwic** [comment]
Hi, I just released v0.4.0 of dbus-rs, which includes a rewrite of the tree module and in the process, I added an example (adv_server.rs) where there are server-side properties and signals. Enjoy!

**Comment by Kilobyte22** [comment]
Nice, will check out later. Thanks!
