### ISSUE TITLE
Reply missed when dispatcher thread is used

### ISSUE THREAD

**Issue by satirebird** [diwic/dbus-rs#375]
Running the following example the method calls fails sporadically. The replies are missed sometimes.

```
fn main() {
    let c = Arc::new(SyncConnection::new_system().unwrap());

    let c1 = Arc::clone(&c);
    thread::spawn(move || {
        loop {
            c1.process(Duration::from_secs(1));
        }
    });

    let p = c.with_proxy("org.bluez", "/org/bluez/hci0", Duration::from_secs(10));

    for _ in 0..4 {
        println!("Start discovery");
        if let Err(e) = p.start_discovery(){
            println!("Error 1 occurred: {}", e.to_string());
        }
        thread::sleep(Duration::from_secs(1));
        println!("Stop discovery");
        if let Err(e) = p.stop_discovery(){
            println!("Error 2 occurred: {}", e.to_string());
        }
        thread::sleep(Duration::from_secs(1));
    }
}
```
The result looks like this:

```
Start discovery
Stop discovery
Start discovery
Error 1 occurred: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Stop discovery
Error 2 occurred: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Start discovery
Stop discovery
Start discovery
Stop discovery
```

Without the dispatch thread I have no issues. It seems that something goes wrong if the dbus sends some signals before the method result comes in?

Version used:
`dbus = "0.9.5"`

The "bluez" proxy is generated with `dbus-codegen-rust -s -g -d org.bluez -p /`

**Comment by diwic** [comment]
Sorry, but this is not supported. `process` should essentially take a `&mut self` but I had to change it to avoid some borrow checker issue long ago. If `process` took a `&mut self` then the compiler would not allow what you're trying to do.

I've added some extra clarification to the docs now.

**Comment by satirebird** [comment]
If it isn't possible to call the process method from a different thread, whats the intention of a SyncConnection? As a result it's not possible receive any signals from dbus. 
Regarding to the examples/match_signal.rs, it wouldn't possible to call the proxy from a user input (e.g. stdin().read_line()) while waiting for signals. Is this correct?

**Comment by diwic** [comment]
> whats the intention of a SyncConnection?
 
You can still do method calls, and emit signals, in parallel from different threads. 

 >  it wouldn't possible to call the proxy from a user input (e.g. stdin().read_line()) while waiting for signals.

As long as you're using blocking connections: you need to have two threads. One that's waiting for user input, once that is received, sends a message to the other thread. The other thread calls `process`, and between calls to `process` it checks for incoming messages from other threads and acts accordingly.

Nonblocking connections work differently; you might want to look into those for your use case.
