### ISSUE TITLE
Settable D-Bus properties

### ISSUE THREAD

**Issue by jbaublitz** [diwic/dbus-rs#377]
In the project that I'm using this library for, we've recently started adding some settable properties. I recently discovered that dbus-rs automatically sends a `PropertiesChanged` signal when a property is set, but we share properties across multiple versioned interfaces. Is there a way to trigger a `PropertiesChanged` signal for all interfaces that contain the property that has been set?

**Comment by diwic** [comment]
Well, the library has no idea that you're sharing properties between objects or interfaces, but there are methods that help you send PropertiesChanged signals programmatically.  

dbus-crossroads: [changed_msg_fn](https://docs.rs/dbus-crossroads/latest/dbus_crossroads/struct.PropBuilder.html#method.changed_msg_fn).

dbus-tree: [add_propertieschanged](https://docs.rs/dbus-tree/latest/dbus_tree/struct.Property.html#method.add_propertieschanged)

dbus: [PropertiesPropertiesChanged](https://docs.rs/dbus/0.9.5/dbus/blocking/stdintf/org_freedesktop_dbus/struct.PropertiesPropertiesChanged.html) - fill struct fields manually.

In the cases you end up with a `PropertiesPropertiesChanged` struct, you then call [to_emit_message](https://docs.rs/dbus/latest/dbus/message/trait.SignalArgs.html#method.to_emit_message) and then send the message over the connection.
