### ISSUE TITLE
How to get the args of existing signal

### ISSUE THREAD

**Issue by yyyymux** [diwic/dbus-rs#381]
Hello,
I am trying to connect to an existing dbus signal. More precisely I would like to retrieve the information sent by the "Subscribe" signal of the "tvos.sgp.device.DNetwork", When i execute this code :

#[tokio::main]
pub async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let (resource, conn) = connection::new_session_sync()?;
    println!("connect dbus");
    let _handle = tokio::spawn(async {
        let err = resource.await;
        panic!("Lost connection to D-Bus: {}", err);
    });
    let mr = MatchRule::new_signal("tvos.sgp.device.DNetwork", "Subscribe");
    println!("=====rule_str={}", mr.match_str());
   let incoming_signal = conn.add_match(mr).await?.cb(|_, (source,):(Vec<HashMap<String,dbus::arg::Variant<Box<dyn RefArg + 'static>>>>,)| {
        println!("Hello from {:#?}happened on the bus!",source);
        true
    });
    _handle.await;
    conn.remove_match(incoming_signal.token()).await?;
    unreachable!()
}

it prints "Hello from []happened on the bus",  the dhus monitor gets 
![image](https://user-images.githubusercontent.com/22656608/161262673-723f3550-c97f-4053-8bb5-46078a8b95f9.png)

i want to know how to get the args of signal,thanks very much!

**Comment by diwic** [comment]
From the look of your screenshot, I'd say there's `Vec` too much in your code, i e, `Vec<HashMap<String,dbus::arg::Variant<Box<dyn RefArg + 'static>>>>` should be shortened to just `PropMap` (which is a type alias for the hashmap part of the argument). 

Feel free to reopen the issue (or start a discussion instead) in case this is not the problem.
