### ISSUE TITLE
Support : How to read Array of HashMap

### ISSUE THREAD

**Issue by bettercalldasappan** [diwic/dbus-rs#394]
```
  let mut iter = message.iter_init();
 while let Some(args) = iter.get_refarg() {
                    println!("{:?}", args.arg_type());
                    println!("{:?}", args);
}
```

Output

```
------
Array
InternalDict {
 	data: [
 		("org.freedesktop.DBus.Introspectable", {}), 
 		("org.bluez.Device1", 
 			{"Address": 
				Variant("AC:AC:AC:AC:AV:BE"), 
				"Paired": Variant(false), 
				"UUIDs": Variant(["0000005-0000-1000-8000-00800000", "00000000-0000-0000-0000-000000000000"]), 
				"Name": Variant("V50 ThinQ"), 
				"Connected": Variant(false), 
				"Icon": Variant("phone"), 
				"AddressType": Variant("public"), 
				"RSSI": Variant(-55), 
				"ServicesResolved": Variant(false), 
				"Trusted": Variant(false), 
				"Blocked": Variant(false), 
				"Alias": Variant("V50 ThinQ"), 
				"Class": Variant(5898764), 
				"Adapter": Variant(Path("/org/bluez/hci0\0")), 
				"LegacyPairing": Variant(false)
			}
 		), 
 		("org.freedesktop.DBus.Properties", {})
 	], 
 	outer_sig: Signature("a{sa{sv}}\0") 
 }
```

How to read this type?

**Comment by diwic** [comment]
Does this work:

    let args: HashMap<String, PropMap> = message.read1()?;

**Comment by bettercalldasappan** [comment]
Very Sorry for the delayed reply. Due to some personal issues.
I used `Message` instead of `ObjectManagerInterfacesAdded` to decode the data in `match_signal` closure.

Now I'm using
 `              let dic =
                        arg::cast::<HashMap<String, HashMap<String, Variant<Box<dyn RefArg>>>>>(
                            &o.interfaces,
                        )
                        .unwrap();`

It can be rewriiten in 
`                        let dic =
                        arg::cast::<HashMap<String, PropMap>>(
                            &o.interfaces,
                        )
                        .unwrap();` Right?

**Comment by diwic** [comment]
> let dic = arg::cast::<HashMap<String, PropMap>>( &o.interfaces, ) .unwrap();` Right?

Right.

**Comment by bettercalldasappan** [comment]
Thanks
