### ISSUE TITLE
How does dbus-crossroads start X11?

### ISSUE THREAD

**Issue by HaoYU17** [diwic/dbus-rs#395]
Hey, there,
I try to use the **/dbus-crossroads/example/server_cr.rs** as an example, and I use cargo bitbake change it into recipe file. When I want to run the service, I meet two errors:

- when I run the service, I got an Error: D-Bus error: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead (org.freedesktop.DBus.Error.NotSupported). In this code, where did we use X11?
- When I use busctl tree <service name>, I got an error: Failed to introspect object / of service com.example.dbustest: The name is not activatable

I find one solution in Stackoverflow, the url is https://stackoverflow.com/questions/41242460/how-to-export-dbus-session-bus-address, but when I run the following command export $(dbus-launch) in the terminal, the first error is soluted, but the second error is still not soluted. I don't know why, can anybody help me?

Thanks for your time!

**Comment by diwic** [comment]
1) Nowhere, that's what it complains about :-) When you compiled `libdbus` (the C bindings this crate binds to), the X11 way to connect to dbus was not compiled in. Which means you need to set DBUS_SESSION_BUS_ADDRESS for it to find the dbus server.

 2) I just tried `busctl tree --user` and got this output:

```
Service com.example.dbustest:
└─/hello
```

...seems like it's working like it should, here at least?

**Comment by HaoYU17** [comment]
> 1. Nowhere, that's what it complains about :-) When you compiled `libdbus` (the C bindings this crate binds to), the X11 way to connect to dbus was not compiled in. Which means you need to set DBUS_SESSION_BUS_ADDRESS for it to find the dbus server.
> 2. I just tried `busctl tree --user` and got this output:
> 
> ```
> Service com.example.dbustest:
> └─/hello
> ```
> 
> ...seems like it's working like it should, here at least?

Yes, when I run this in a x86 machine, it works fine, everything is ok! I use `cargo run` to run the service program, and then I use 
```
busctl --user tree <service name>
```
I got the same answer...

But when I use bitbake tool and try to run the service in an Arm machine, it comes out this issue:
```
Error: D-Bus error: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead (org.freedesktop.DBus.Error.NotSupported)
```
The code is same as [server_cr.rs](https://github.com/diwic/dbus-rs/blob/master/dbus-crossroads/examples/server_cr.rs), so I was confused about where we use X11 at compile time. Thanks for your reply.

And when I run this command `export $(dbus-launch)` to set DBUS_SESSION_BUS_ADDRESS for it, and I try to run it again, the service is running, but then I use busctl tree <service name>, I got an error: 
```
Failed to introspect object / of service xyz.openbmc_project.dbustest: The name is not activatable
```
It seems confusing... It seems that it did not connect to the dbus correctly.

Thanks for your help, let me show you my recipe file:
```
# Auto-Generated by cargo-bitbake 0.3.16
#
inherit cargo
inherit pkgconfig

DEPENDS += "dbus"

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get dbus-crossroads could be as easy as but default to a git checkout:
# SRC_URI += "crate://crates.io/dbus-crossroads/0.5.0"

# I am sorry that I can not show you my company's repo, but it works fine here.
SRC_URI += "xxx"
SRCREV = "xxx"

S = "${WORKDIR}/git"
CARGO_SRC_DIR = "dbus-crossroads"
PV:append = ".AUTOINC+5afdaf2031"

# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
    crate://crates.io/ansi_term/0.12.1 \
    crate://crates.io/atty/0.2.14 \
    crate://crates.io/autocfg/1.1.0 \
    crate://crates.io/bitflags/1.3.2 \
    crate://crates.io/camino/1.1.1 \
    crate://crates.io/cargo-pkgconfig/0.1.4 \
    crate://crates.io/cargo-platform/0.1.2 \
    crate://crates.io/cargo_metadata/0.14.2 \
    crate://crates.io/cfg-if/1.0.0 \
    crate://crates.io/clap/2.34.0 \
    crate://crates.io/clap/3.2.21 \
    crate://crates.io/clap_lex/0.2.4 \
    crate://crates.io/fastrand/1.8.0 \
    crate://crates.io/futures-channel/0.3.23 \
    crate://crates.io/futures-core/0.3.23 \
    crate://crates.io/futures-executor/0.3.23 \
    crate://crates.io/futures-io/0.3.23 \
    crate://crates.io/futures-macro/0.3.23 \
    crate://crates.io/futures-sink/0.3.23 \
    crate://crates.io/futures-task/0.3.23 \
    crate://crates.io/futures-util/0.3.23 \
    crate://crates.io/futures/0.3.23 \
    crate://crates.io/hashbrown/0.12.3 \
    crate://crates.io/hermit-abi/0.1.19 \
    crate://crates.io/indexmap/1.9.1 \
    crate://crates.io/instant/0.1.12 \
    crate://crates.io/itoa/1.0.3 \
    crate://crates.io/libc/0.2.131 \
    crate://crates.io/log/0.4.17 \
    crate://crates.io/memchr/2.5.0 \
    crate://crates.io/mio/0.8.4 \
    crate://crates.io/num_cpus/1.13.1 \
    crate://crates.io/once_cell/1.13.0 \
    crate://crates.io/os_str_bytes/6.3.0 \
    crate://crates.io/path-slash/0.1.5 \
    crate://crates.io/pin-project-lite/0.2.9 \
    crate://crates.io/pin-utils/0.1.0 \
    crate://crates.io/pkg-config/0.3.25 \
    crate://crates.io/proc-macro2/1.0.43 \
    crate://crates.io/quote/1.0.21 \
    crate://crates.io/redox_syscall/0.2.16 \
    crate://crates.io/remove_dir_all/0.5.3 \
    crate://crates.io/ryu/1.0.11 \
    crate://crates.io/semver/1.0.13 \
    crate://crates.io/serde/1.0.144 \
    crate://crates.io/serde_derive/1.0.144 \
    crate://crates.io/serde_json/1.0.85 \
    crate://crates.io/slab/0.4.7 \
    crate://crates.io/socket2/0.4.4 \
    crate://crates.io/strsim/0.10.0 \
    crate://crates.io/strsim/0.8.0 \
    crate://crates.io/syn/1.0.99 \
    crate://crates.io/tempfile/3.3.0 \
    crate://crates.io/termcolor/1.1.3 \
    crate://crates.io/textwrap/0.11.0 \
    crate://crates.io/textwrap/0.15.0 \
    crate://crates.io/tokio-macros/1.8.0 \
    crate://crates.io/tokio/1.20.1 \
    crate://crates.io/unicode-ident/1.0.3 \
    crate://crates.io/unicode-width/0.1.9 \
    crate://crates.io/vec_map/0.8.2 \
    crate://crates.io/wasi/0.11.0+wasi-snapshot-preview1 \
    crate://crates.io/winapi-i686-pc-windows-gnu/0.4.0 \
    crate://crates.io/winapi-util/0.1.5 \
    crate://crates.io/winapi-x86_64-pc-windows-gnu/0.4.0 \
    crate://crates.io/winapi/0.3.9 \
    crate://crates.io/windows-sys/0.36.1 \
    crate://crates.io/windows_aarch64_msvc/0.36.1 \
    crate://crates.io/windows_i686_gnu/0.36.1 \
    crate://crates.io/windows_i686_msvc/0.36.1 \
    crate://crates.io/windows_x86_64_gnu/0.36.1 \
    crate://crates.io/windows_x86_64_msvc/0.36.1 \
    crate://crates.io/xml-rs/0.8.4 \
"



# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM = " \
    file://LICENSE;md5=86d3f3a95c324c9479bd8986968f4327 \
"

SUMMARY = "Framework for writing D-Bus method handlers"
HOMEPAGE = "xxx"
LICENSE = "Apache-2.0 | MIT"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include dbus-crossroads-${PV}.inc
include dbus-crossroads.inc
```
I hope I articulate my problem clearly, thank you again!

**Comment by diwic** [comment]
I'm afraid I can't help you further - this is not an issue with the dbus-rs bindings but with something else, most probably the environment you run it in. I'm not very familiar with bitbake either.

**Comment by HaoYU17** [comment]
> I'm afraid I can't help you further - this is not an issue with the dbus-rs bindings but with something else, most probably the environment you run it in. I'm not very familiar with bitbake either.

Ok, fine, thank you again~
