### ISSUE TITLE
GetManagedObjects doesn't respond with async properties

### ISSUE THREAD

**Issue by zevweiss** [diwic/dbus-rs#402]
Using the following minimized reproducer (cut down from a modified version of `tokio_adv_server_cr.rs`):

```rust
use tokio::sync::Mutex;
use dbus::channel::MatchingReceiver;
use dbus_crossroads::{Crossroads, IfaceBuilder};
use std::sync::{Arc, Mutex as SyncMutex};

struct Item { value: i32 }

#[tokio::main]
pub async fn main() {
    let (resource, c) = dbus_tokio::connection::new_session_sync().unwrap();
    let _handle = tokio::spawn(async {
        let err = resource.await;
        panic!("Lost connection to D-Bus: {}", err);
    });

    let mut cr = Crossroads::new();
    cr.set_async_support(Some((c.clone(), Box::new(|x| { tokio::spawn(x); }))));
    cr.insert("/", &[cr.object_manager()], ());

    let token = cr.register("com.example.item", |b: &mut IfaceBuilder<Arc<Mutex<Item>>>| {
        b.property("value")
            .get_async(move |mut ctx, device| {
		let device = device.clone();
		async move {
		    let d = device.lock().await;
		    ctx.reply(Ok(d.value))
		}
	    });
    });
    cr.insert("/item", &[token], Arc::new(Mutex::new(Item { value: 42 })));

    c.request_name("com.example.bugdemo", false, true, false).await.unwrap();

    let cr = Arc::new(SyncMutex::new(cr));
    c.start_receive(dbus::message::MatchRule::new_method_call(), Box::new(move |msg, conn| {
        let mut cr_lock = cr.lock().unwrap();
        cr_lock.handle_message(msg, conn).unwrap();
        true
    }));

    futures::future::pending::<()>().await;
    unreachable!()
}
```

With that running, if I then run
```
$ busctl --user call com.example.bugdemo / org.freedesktop.DBus.ObjectManager GetManagedObjects
```
it simply hangs without receiving a response.

After adding some print calls to [`dbus_crossroads::stdimpl::get_managed_objects()`](https://github.com/diwic/dbus-rs/blob/2c29b4393f2073a019f2c9a2a96b140dd3ceb6ba/dbus-crossroads/src/stdimpl.rs#L332-L385), I first see the `lock.take()` at the end of the function producing `None`, followed by the (nested) closure from a few lines above calling `msg.append_all()`, so I assume the async property retrieval is allowing the ordering to get a little rearranged from what was intended there.  I'm not terribly familiar with the code and don't know offhand what an appropriate fix might be (though if I have any wonderful insights I'll post a PR).

**Comment by diwic** [comment]
Hi,

I tried to run the example and it fails to compile with the following errors:


    error[E0432]: unresolved import `tokio::sync::Mutex`
     --> dbus-tokio/examples/bug402.rs:1:5
      |
    1 | use tokio::sync::Mutex;
      | 
        ^^^^^^^^^^^^^^^^^^ no `Mutex` in `sync`

    error[E0603]: module `sync` is private
       --> dbus-tokio/examples/bug402.rs:1:12
        |
    1   | use tokio::sync::Mutex;
        |            ^^^^ private module
        |


Could you provide a matching Cargo.toml, full repo or something? Thanks!

**Comment by zevweiss** [comment]
As, sorry about that -- the following `Cargo.toml` should work:

```toml
[package]
name = "bugdemo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.22", features = ["full"] }
dbus = "0.9"
dbus-tokio = "0.7"
dbus-crossroads = "0.5"
futures = "0.3"
```

**Comment by diwic** [comment]
Writing this for myself mostly:

There are multiple `Option<Context>` here and the one that needs to get async support / send_on_drop in order to actually send the message when dropped:

            ctx.do_reply(|msg| {
                msg.append_all((&rr.temp_map,));
            });

Is not getting it because it is not sent into the methods - `Propctx::set_send_on_drop` tries to set it but there is no context for that to set it. Therefore the message is dropped without being actually being sent.

**Comment by diwic** [comment]
I believed I fixed it now. If you would submit a PR adding your reproducer into `dbus-crossroads/test.rs`, that would be appreciated. Thanks!

**Comment by zevweiss** [comment]
Hmm, unfortunately after updating Cargo.toml to specify the latest versions that include commit 971a151 (dbus-crossroads 0.5.1 and dbus 0.9.6) I still see my `busctl`hanging before eventually timing out.  I thought maybe I was still somehow running a stale version with the old code, but even after a `cargo clean` and `cargo update` followed by another from-scratch `cargo build` its behavior doesn't seem to change.

**Comment by zevweiss** [comment]
...ah, and now of course I realize I misread the order of the commits in the git commits I fetched, and those versions actually did _not_ include the relevant commit.  After testing with the right code the problem does indeed appear to be fixed (and I've created a PR adding a test as #405).
