### ISSUE TITLE
Use standard library `OwnedFd`

### ISSUE THREAD

**Issue by ids1024** [diwic/dbus-rs#403]
Currently `dbus` defines an `OwnedFd` type. Since a type with that name and purpose [exists in std](https://doc.rust-lang.org/std/os/fd/struct.OwnedFd.html) now, it would be best to use the standard type (the `io-lifetimes` crate can be used to support the same thing on older compilers, if needed).

This would be a breaking API change since the type is defined differently.

Looking into this, there are a few complications:
* `dbus` relies on the type implementing `PartialOrd`, while the standard `OwnedFd` doesn't. This could be addressed by a manual implementation of `PartialOrd` in types that contain a `OwnedFd`, but that's awkward.
* `dbus` also relies on `Clone`. While the standard library doesn't offer this and provides `OwnedFd::try_clone` since the operation may fail. Similar considerations for manual implementations.
* `dbus` provides a placeholder `OwnedFd` on non-Unix platforms. Maybe instead the `UnixFd` enum variant should only exist on Unix? Not sure if there are other complications. 

Or without API break, or having to deal with these issue, implementing `AsFd` and `From` would offer better interoperability with the standard types, at least.

**Comment by diwic** [comment]
I think a first step could be to implement possible traits for `std::os::fd::OwnedFd` just like we do for `std::fs::File`. 

Could you clarify what part of dbus relies on the type implementing `PartialOrd` and `Clone`? I checked `Arg`, `RefArg`, `Append` and `Get` and neither of those required `PartialOrd` and `Clone`.

**Comment by ids1024** [comment]
`MessageItem` has a `UnixFd(OwnedFd)` variant, and implements `PartialOrd` and `Clone`. Looks like removing `PartialOrd` from that as well as `MessageItemDict` and `MessageItemArray` compiles. But removing `Clone` leads to errors.

**Comment by diwic** [comment]
Ok, so `MessageItem` is really legacy and I don't care that much about it. Is `MessageItem` the primary place you want it in? Arg/Append/Get can take multiple types. `RefArg` has a single representation w r t what you get out when you read something, but can also be implemented for many types.

**Comment by ids1024** [comment]
So yeah, if implementing those traits for the standard library type is sufficient to use that with non-legacy APIs, that should be doable enough without any breaking API changes.

**Comment by diwic** [comment]
Hmm, so even if the API changes are not breaking, it does not seem easy to implement this without either bumping rust version or add additional dependencies...right?

**Comment by ids1024** [comment]
If it's just a a matter of implementing a few traits, `io-lifetimes` could be added as an optional dependency.

**Comment by ids1024** [comment]
https://github.com/diwic/dbus-rs/pull/407 adds such an optional dependency.

**Comment by diwic** [comment]
See also https://github.com/diwic/dbus-rs/pull/410

**Comment by diwic** [comment]
Ok, so I decided to remove the `io-lifetimes` feature and add a `stdfd` feature instead. I believe this fixes your issue. See #418
