### ISSUE TITLE
Multi-interface fdo Properties GetAll behaves erratically with async properties

### ISSUE THREAD

**Issue by zevweiss** [diwic/dbus-rs#414]
Mult-interface GetAll support was added recently in [a PR I submitted](https://github.com/diwic/dbus-rs/pull/406), so quite arguably I should be on the hook for fixing it, but I'm presently a bit lost in all the callbacks and context objects and `Option`s involved, and I'm wondering if it might have some relation to https://github.com/diwic/dbus-rs/issues/402 and/or https://github.com/diwic/dbus-rs/commit/971a151bb073f8da90983c41a9ef48f7e1d30c3b.

Using the test added in https://github.com/diwic/dbus-rs/pull/413, I get inconsistent behavior from repeated runs.  I added some debug prints to `getall_all()` to try to see a bit more about what was going on, but things only got more confusing.

**Usually** I get a panic from the `.unwrap()` on [line 418 of `test.rs`](https://github.com/diwic/dbus-rs/pull/413/files#diff-eddc0c3150d9c4e73a8ad11b978b0d3ae922fd60bd0e69aec5da2c17701b9ed7R418) (the `method_call().await.unwrap()`) with the call timing out -- often this happens without any of my debug print output appearing.

**Sometimes** the above is also accompanied by output from my debug prints in `getall_all()`, and another panic from a failing `.unwrap()` in `getall_all()` [here](https://github.com/diwic/dbus-rs/commit/28613f79faae45da0f09f8e6cefb4393a2e72b91#diff-7d384b33e38db8195962c90b1997d6c90535eb2fa70b60c321970baddf8243caR233).

**Rarely** but occasionally I see a different `None`-unwrap panic from [the first unwrap of the results from the second interface](https://github.com/diwic/dbus-rs/pull/413/files#diff-eddc0c3150d9c4e73a8ad11b978b0d3ae922fd60bd0e69aec5da2c17701b9ed7R421), like it somehow worked but only for the first interface.

I'd be grateful for any further insight into what might be going on here or how to fix it.

**Comment by diwic** [comment]
Hi and thanks for looking into it. I hope I've been able to fix it, but I'm not sure if there can still be sporadic failures, the async code is indeed not that easy to understand.
