### ISSUE TITLE
Crossroad example not working

### ISSUE THREAD

**Issue by jruiss** [diwic/dbus-rs#428]
I'm using dbus 1.14.6-1, and can see "com.example.dbustest" listed with
`dbus-send --print-reply --dest=org.freedesktop.DBus  /org/freedesktop/DBus org.freedesktop.DBus.ListNames`
and when executing the example "dbus-send ..."
```
signal time=1680150226.876200 sender=:1.46 -> destination=com.example.dbustest serial=2 path=/hello; interface=com.example.dbustest; member=Hello
   string "test"
```
with dbus-monitor, however nothing is printed by the example nor is a response returned

**Comment by diwic** [comment]
It seems like dbus-send defaults to sending a signal instead of a method call unless the `--print-reply` flag is added. Updated documentation.

```
dbus-send --print-reply --dest=com.example.dbustest /hello com.example.dbustest.Hello string:MyName
```
