### ISSUE TITLE
`vendored` feature's build script writes outside of `$OUT_DIR`

### ISSUE THREAD

**Issue by Seeker14491** [diwic/dbus-rs#429]
When using the `vendored` feature, `libdbus-sys` writes to some files in `vendor/dbus`:

https://github.com/diwic/dbus-rs/blob/a8f0ea07ffd6e9b9690d7ff9c6a53a65e70fcdb8/libdbus-sys/build_vendored.rs#L201-L202

Per the Cargo docs, build scripts shouldn't modify any files outside `$OUT_DIR`. This [broke](https://docs.rs/crate/opener/0.6.0/builds/776608) the building of documentation of my crate on docs.rs, as directories outside `$OUT_DIR` are read-only in that environment.

**Comment by diwic** [comment]
@landhb I'm quite busy ATM, can you take a look at this?

**Comment by diwic** [comment]
@Seeker14491 fixed by @landhb now, let me know if you need a release.

**Comment by Seeker14491** [comment]
Thanks for the fix. A release would be appreciated.

**Comment by diwic** [comment]
@Seeker14491 released now, enjoy!
