### ISSUE TITLE
register object of type X on dbus?

### ISSUE THREAD

**Issue by kaii-lb** [diwic/dbus-rs#449]
say i have a struct which defines how an ObexAgent should work, i need to register this ObexAgent on dbus with a path so that dbus picks it up and the correct methods get called when a bluetooth transfer is inbound. How would i do this?

**Comment by kaii-lb** [comment]
something like this: https://dbus.freedesktop.org/doc/dbus-python/dbus.service.html#dbus.service.Object

**Comment by diwic** [comment]
Are you looking for porting something like this https://github.com/pauloborges/bluez/blob/master/test/simple-obex-agent to Rust? 

For the server part (that listens to incoming method calls) you should look into dbus-crossroads.

**Comment by kaii-lb** [comment]
yes thats exactly what i was looking for actually, and dbus-crossroads solves my problem perfectly, thanks a lot!
