### ISSUE TITLE
Question about asynchronous server.

### ISSUE THREAD

**Issue by meh** [diwic/dbus-rs#45]
Couldn't find if there were any other venues to ask question, sorry for the issue noise.

I'm working on a screensaver and I'd like to use DBus for communication, so I can have a server that creates a DBus interface and whatnot and wait for requests like to start the screensaver or lock the screen.

Since there are also other things involved the design from the example with the closures seems rather complicated to fit into my design.

What I'm trying to achieve is having a `Server` struct that contains the connection/tree/whatever which spawns a thread, and this thread sends the DBus calls being received through a channel, then the loop in `main` reads from the channel, does some thing and calls the proper stuff to respond to the request and writes back to another channel, and then the thread spawned by `Server` responds back through DBus.

Is this currently possible without hacking it up using the `Factory::method` closures? Are there any examples to do this I missed?

Thanks.

**Comment by diwic** [comment]
It's possible to have one thread listen and receive D-Bus calls and another thread handle them.

Your D-Bus thread would look like this (rough outline) :

    for item in connection.iter() {
        if let MethodCall(m) = item {
            channel.send(m);
            let reply = other_channel.receive();
            connection.send(reply);
        }
    }

The main thread can either have a `Tree`, and handling is then done by calling `Tree.handle()` and the result back on the channel, or you can handle the message manually by calling methods on the message to figure out what message it is, and construct an appropriate reply using `message.method_return().append(/* ... *)`.

**Comment by meh** [comment]
Could you elaborate a little on the `Tree` way please?

**Comment by diwic** [comment]
You would set up the Tree like in the [server example](https://github.com/diwic/dbus-rs/blob/master/examples/server.rs) but instead of calling `tree.run` your code would look like (rough outline, add proper error handling) :

    loop {
         let msg = channel.recv();
         let reply = tree.handle(msg);
         other_channel.send(reply);
    }

**Comment by meh** [comment]
Got another related question, how would I go about sending asynchronous signals?

Let's say I want to emit the signals directly from the main thread, is there a way to do it?

I was trying to put the `Connection` into an `Arc` but it's not `Sync` and `Send` and share the `Arc<tree::Signal>` between the tree thread and the main thread, but I guess it wouldn't really work.

Any hints?

**Comment by diwic** [comment]
The easiest way is to have two connections. I could see if I could make `Connection` `Send`, because I think it should be, but I doubt that will help much in your case.

There is also some stuff written about connection and thread safety [in the API](https://dbus.freedesktop.org/doc/api/html/group__DBusConnection.html) indicating that it could maybe even be `Sync`. That would require some work on my part though as my wrapper currently isn't sync.

**Comment by meh** [comment]
Won't the `register_name` explode because I'm overriding an already existing interface?

**Comment by diwic** [comment]
> Won't the register_name explode because I'm overriding an already existing interface?

You don't need to register a name to send signals, AFAIK?
