### ISSUE TITLE
Bytestrings (ay)

### ISSUE THREAD

**Issue by LEW21** [diwic/dbus-rs#50]
Hi,

I'm the creator of [pydbus](https://github.com/LEW21/pydbus), DBus bindings for Python. I've stumbled upon the case of bytestrings - ay - which are commonly used to send non-Unicode data over DBus.

Because of the GDBus's API, apps commonly require these strings to be '\0'-terminated. And that's completely unintuitive for high-level languages, and something that requires the user to read API docs.

I'm thinking about solving the problem automatically, and I see two solutions:

1. Auto-append and auto-strip the last character of "ay"s; [EDIT: impossible, some APIs use not-terminated strings]
2. Decree (how?) that GDBus API is wrong, and strings sent over the wire should not be \0-terminated.
3. [EDIT:] Create a new DBus annotation meaning "All "ay"s in the arguments of this method/signal are \0-terminated bytestrings" - and auto-append/auto-strip \0 if it's present.

Whatever we choose, the solution should be agreed upon by authors of bindings for all languages. That's why I'm here.

Do you have any experience with "ay"-encoded bytestrings?

Relevant discussion: https://github.com/LEW21/pydbus/issues/27

**Comment by diwic** [comment]
I don't think we should auto-append and auto-strip any zeros at the end of arrays of byte. That seems very unintuitive to me (and would perhaps also have a performance cost).

I have not used GDBus, but if it doesn't properly support byte arrays, then they should fix that.

**Comment by LEW21** [comment]
I've updated my proposal, because smcv has proven the first option is impossible (in the pydbus issue comments).

I also think that in the ideal world nobody should use \0-terminated arrays here, but there is at least one case (besides Flatpak, which is new, and can easily be changed) where they're used:

"The D-Bus core protocol has adopted this convention for the LinuxSecurityLabel value in the hash table returned by GetConnectionCredentials(), although the older GetConnectionSELinuxContext() method doesn't do it."

You might want to reply on https://github.com/LEW21/pydbus/issues/27 - as I've opened issues on 8 different bindings to get their authors attention, and it's starting to get hard to keep track of all of them.

**Comment by diwic** [comment]
Rust does not use zero-terminated strings and thus has no use for the extra zero anyway. Also, for now, we only know of two places where this happens so I doubt it's commonly used.

If the D-Bus specification grows some kind of annotation about autoremoval/autoadd of `\0` then I'll consider supporting that in my bindings - until then, it's trivial for whoever uses dbus-rs to do that add/removal manually. It's even easier than it would be for me, considering that these zero-terminated arrays may be inside an arbitrary level of containers.
