### ISSUE TITLE
Distinguish between missing args and bad arg types using get*() methods.

### ISSUE THREAD

**Issue by mulkieran** [diwic/dbus-rs#51]
Is there a recommended way to do this?

I think that the get*() methods themselves do not distinguish; they return None if the arg is missing or has the wrong type.

I've come up with an approach that looks something like this:

```
    let message: &Message = m.msg;
    let item: MessageItem = try!(message.get1().ok_or_else(MethodErr::no_arg));
    let name: &str = try!(message.get1().ok_or_else(|| MethodErr::invalid_arg(&item)));
    ...
```

The results I get are nice and distinguish between the two situatons:

```
[mulhern@dhcp-25-209 stratisd]$ busctl --user call org.storage.stratis1 /org/storage/stratis1 org.storage.stratis1.Manager DestroyPool
Not enough arguments
[mulhern@dhcp-25-209 stratisd]$ busctl --user call org.storage.stratis1 /org/storage/stratis1 org.storage.stratis1.Manager DestroyPool i 2
Invalid argument Int32(2)
[mulhern@dhcp-25-209 stratisd]$ busctl --user call org.storage.stratis1 /org/storage/stratis1 org.storage.stratis1.Manager DestroyPool s name
qs 0 "Ok"
```

Notice, though, how I have to call get1() twice, one to detect if the argument is there at all, and once to detect if the item has the correct type. Should some one in need of this amount of specificity be doing something different?

There is another approach that just considers the entire message an invalid arg, that yields results something like this, if the message has too few args or if the args are ill-typed:

```
[mulhern@dhcp-25-209 stratisd]$ busctl --user call org.storage.stratis1 /org/storage/stratis1 org.storage.stratis1.Manager DestroyPool i 2
Invalid argument [Int32(2)]
[mulhern@dhcp-25-209 stratisd]$ busctl --user call org.storage.stratis1 /org/storage/stratis1 org.storage.stratis1.Manager DestroyPool
Invalid argument []
[mulhern@dhcp-25-209 stratisd]$ busctl --user call org.storage.stratis1 /org/storage/stratis1 org.storage.stratis1.Manager DestroyPool s name
qs 0 "Ok"
```

It is implemented kind of like this:

```
    let message: &Message = m.msg;
    let name: &str = try!(message.get1().ok_or_else(|| MethodErr::invalid_arg(&message.get_items())));
    ...
```

Thanks for any help you can give.

**Comment by diwic** [comment]
The get* methods are just short wrappers around [arg::Iter](https://docs.rs/dbus/0.4.0/dbus/arg/struct.Iter.html). That struct has an `arg_type` method, which returns what type you're currently at. It will return 0 in case in case there is no argument at the current position (this could be better documented).

Example:

    let mut i = message.iter_init();
    if i.arg_type() == 0 { return Err(MethodErr::no_arg) };
    let name: &str = try!(i.get().ok_or_else(|| MethodErr::invalid_arg(0));
    
But I see your point that this could be smarter done somehow. Perhaps I could do something smart with [https://docs.rs/dbus/0.4.0/dbus/arg/struct.TypeMismatchError.html](TypeMismatchError)...

**Comment by mulkieran** [comment]
Thanks! Code is much tidier.

**Comment by diwic** [comment]
Ok, and with that commit you should be able to do:

    let mut i = message.iter_init();
    let name: &str = try!(i.read());

And get error messages like:

    D-Bus argument type mismatch: expected String, found i32
    D-Bus argument type mismatch: expected String, found nothing

Let me know if that's not working as expected (MethodErr implements From<TypeMismatchError> so should convert automatically with try).
