### ISSUE TITLE
Handling adding and removing object paths from a single tree

### ISSUE THREAD

**Issue by agrover** [diwic/dbus-rs#52]
Hiya,

We're still stuck on the issues raised by #40. We want the good stuff a tree provides (introspection, object manager, method dispatch) and also be able to add and remove object paths. This is important because we want to have our DBus interface create and remove objects and interfaces at runtime, and it's currently not possible, although we keep coming back to this as a natural way to want to design an API.

One easy thing would be to Add `Tree::add_o_path()` to tree/objectpath.rs `Tree`. This makes it possible to add an objectpath to the tree from a tree's method (although this requires an `unsafe` conversion of `&m.tree` to a `&mut m.tree`, it's a least possible) (This should not cause issues as long as it's always a different ObjectPath we're adding or removing than the objectpath/interface our method was invoked on)

Thinking longer-term, I'm wondering how hard it would be to make MethodInfo::tree a mutable ref (I tried it, `'a`s blossomed everywhere and I gave up, but you might have more luck) Or, I noticed that the only users of MethodInfo::tree are introspection and managed_objects, that call `tree::children()`, which then filters for children within the object path -- could there be a more distributed method of iterating and looking up object paths that would not require the entire `&Tree`? If so then an objectpath's method could be called without referencing the tree, and enclosing `Tree` in `Rc<RefCell>>` would let us close over and modify the tree without `unsafe`.

cc @tasleson @trgill @mulkieran

**Comment by agrover** [comment]
Proposed implementation of tree/objectpath.rs Tree add_o_ref:
```
    pub fn add_o_ref<I: Into<Arc<ObjectPath<M, D>>>>(&mut self, s: I)
                                                     -> Arc<ObjectPath<M, D>> {
        let m = s.into();
        self.paths.insert(m.name.clone(), m.clone());
        m
    }
```

**Comment by diwic** [comment]
Well, I'm not happy about sending a `&mut Tree` in, because if you could, you could remove all object paths, which could include the one you're currently calling a method on. That Rust protects you from being able to write that code is more a good than a bad thing IMO.

I believe the way to do this is in two steps: The method would just add an "add" or "remove" instruction in a TODO list. Back outside `tree::run` you have full mutable access to the tree, where you can carry out the instruction.

If you want to wait to send the reply back to the client until after the instruction has been fully carried out, you can also store the `method_return` message in the TODO list (and return an empty vec back in the method handler).

**Comment by diwic** [comment]
I believe your suggested `add_o_ref` can be done today as:

    *tree = mem::replace(&mut tree, Tree::new()).add(my_new_path);

**Comment by tasleson** [comment]
@diwic Maybe it's not a good API design choice, but for a different project that I've worked on I exposed a dbus **job** object for long running operations.  The [job object](https://github.com/tasleson/lvm-dubstep/blob/master/api.md#interface-comredhatlvmdbus1job) has properties and methods , one of which is to remove itself when the client no longer needs it.  Thus in this case it was required that the dbus library have the ability to remove a dbus object from one of the methods on the object itself.

**Comment by diwic** [comment]
@tasleson I don't mind that the API exposes a function to remove its own object path (or interface, etc). But when we implement such functionality, we need to do this in a safe manner, avoiding dangling pointers.

IMO, the TODO list approach is the best one. The other option would be to do refcounting, but then every time you call into a method you need to up the reference count to the object path, interface, method etc, and down the refcount afterwards. While that would not be much of a performance hit compared to sending messages over D-Bus in general, it still feels like an unnecessary complication for something that happens quite rarely or not at all for most D-Bus applications.

**Comment by agrover** [comment]
@diwic: I'm afraid I still need more help understanding your use of `mem::replace`. Assuming we have obtained a mut ref of Tree, we want to add an objectpath to the existing tree -- your snippet appears to replace the tree entirely with a new tree with just the new object path, no?

**Comment by diwic** [comment]
@agrover 

here's a slightly longer way of doing the same thing, but probably easier to understand:

    // we want to add "my_new_path" to "tree"
    let mut temp = Tree::new();
    mem::swap(&mut temp, &mut tree);
    let mut newtree = temp.add(my_new_path);
    mem::swap(&mut newtree, &mut tree);

Nothing is ever added to the empty tree, it's just used to be temporarily stored in `tree` while we change the tree.

**Comment by diwic** [comment]
That said, using mem::replace is still unergonomic compared just calling a method. So I just added one. Enjoy :-)

**Comment by diwic** [comment]
> (although this requires an unsafe conversion of &m.tree to a &mut m.tree, it's a least possible) (This should not cause issues as long as it's always a different ObjectPath we're adding or removing than the objectpath/interface our method was invoked on)

It is never allowed to directly convert a `&` to a `&mut`. This is because there are LLVM annotations on `&` that indicates the pointer is read-only. This allows LLVM to do some interesting optimisations which, obviously, can cause random behaviour if you in fact break them. [More information](https://github.com/rust-lang/rust/issues/34496)

**Comment by diwic** [comment]
So, the add_o_ref method has been added (renamed to "insert"), the `&mut Tree` suggestion is unlikely to happen and I suggest to use a TODO list instead as a more "rustic" approach to the problem.

With that, is there anything else in this issue that needs fixing / clarification?

**Comment by agrover** [comment]
Much thanks @diwic. I think `insert` and `remove` plus the TODO list approach could work well (and avoid undefined behavior), we'll give that a try!
