### ISSUE TITLE
Why is it not possible to verify that values sent by a service match the published signature?

### ISSUE THREAD

**Issue by mulkieran** [diwic/dbus-rs#53]
Hi!

This is more of a question than a bug as it seems like all the dbus implementations that I have looked at work the same.

Basically, it seems that a service writes some code that determines the introspection information that can be obtained over the dbus via the Introspect method. Also, it writes some code that puts messages on the dbus. These messages are supposed to conform to the signature information that the client can get via the Introspect method. But the dbus libraries, including yours, don't seem to have any mechanism in place for ensuring that this happens correctly, or for detecting errors. Basically, making sure that the actual values match the published signature seems to be entirely up to the programmer.

I am wondering if there is a way of fixing this problem in a library written in a language which is statically checked and has a fairly flexible type system like Rust does.

**Comment by diwic** [comment]
Indeed. I've been thinking of what the best way to implement such checking would be, but I'm not sure I have come to an answer yet.

A while ago I found [dbus-macros](https://docs.rs/dbus-macros/0.0.6/dbus_macros/) which seems to be an interesting approach to the problem. Do you have other ideas?

Just for reference, is it the server or client side you're interested in, or both?

**Comment by mulkieran** [comment]
Both, but server more than client. And I think that problem might be slightly more tractable.

I honestly don't have any other ideas, if I come up w/ any I'll let you know.

I think g-dbus, which is in C, produces tons of code from an XML spec, code both for client and server. But I think there should be some other way.

I haven't really figured out dbus-macros yet, I'll take another pass.

**Comment by diwic** [comment]
Note to myself as well as you. I tried to make a macro to encapsulate a tree method, and I think verifying the types will be straight forward enough, but soon you'll encounter things such as:

 * What if the method wants to optionally return an error?
 * What if the method wants to send a signal as well as a method return?
 * What if the method wants access to the MethodInfo, e g to verify the sender of the message?
 * What if the method wants to add associated data?
 * What if the method wants to name the output argument(s)?

All this is solvable, but the macro grows in complexity and I need to figure out a way to do this and still keep things reasonably ergonomic.

**Comment by mulkieran** [comment]
Note to myself as well as to you :)

There is a nice way to, given a signature, generate a list of functions that convert a structure in core Python types to one in the correct types for dbus-python so long as they are conformable to the correct type: https://github.com/stratis-storage/into-dbus-python. I wrote it, so I have a lot of confidence in it. However, I don't think the technique would even work in Rust, as it would require dependent types. Also, it only solves half the problem in the dbus service, since the information that gets put in the Introspectable interface is still separate from the functions that actually do the work to put values on the dbus.

It turns out, as I discovered recently, that the dbus-python client will, if the object implements the Introspectable interface, read the data returned by the Introspect() method, and massage it into the
correct type or fail w/ a TypeError before sending it across the dbus.

So, it is amusing that the client programmatically conforms to the interface declared by the Introspectable interface, but the service, which actually declares the (optional) interface, does not.

**Comment by diwic** [comment]
Also, I can't stop thinking about traits. Rust traits look very much like dbus interfaces. At least the methods. You can probably shoehorn dbus properties in; they are basically set/get calls. But signals, which are also a part of dbus interfaces, but I'm not sure how to fit them in.

We are a few months away from macros 1.1 stabilization - it could be interesting to see how that is possible to (ab)use for our purposes.

**Comment by diwic** [comment]
Hi!

So, I've been finishing up a first draft of dbus-codegen today, and it would be nice if you could try it out, see if you can use it or if it's all too difficult to make sense, what adjustments are needed, etc.

In short,
 1) sync latest git master and go to the codegen/dbus-codegen directory.
 2) Run `cargo run -- -d DEST -p PATH > somefile.rs` with the D-Bus service you want to get introspect data from (there are some other flags too).
 3) Integrate `somefile.rs` with your project. You can look in `tests/test2.rs` for a quick test/example of both client and server sides. The top part is the server part (a bogus implementation of some property methods). The part run in a separate thread is the client part.

**Comment by mulkieran** [comment]
It compiles!

AFAICT, it's a piece of interface for a client of the service, and makes sense to me up to that point.

Not a criticism of your work, per se, but there are some problems that bother me.
*. You need to run the service to get the introspection data to generate the code. Not just run the service, but generate objects of every variety and make sure that they have all the interfaces that they will ever have. (I know someone who dynamically adds and and remove interfaces to objects depending on their context, so this could be a really challenging problem).
* It doesn't close the loop, because it doesn't ensure that introspection information put out by the service matches the behaviour of the service, type of objects consumed and type of objects returned, which would be great if possible.

Let me know if I'm wrong about this. I may be misunderstanding what I'm looking at.

Big plus for making it possible to read data from stdin, and not be dependent on the ability to run the service when building!

Currently our client is in Python: https://github.com/stratis-storage/stratisd-client-dbus. We may very well end up writing a client in Rust, but currently, there is none such. What I do currently is use data structures to encode the relevant introspection information in the client, and then run tests to verify that the information in the client matches what the service puts out. That is not such a huge burden, since it is pretty easy to dynamically generate the Python classes from these tables. I could make it more automatic by generating the tables from the introspection data, and if this code lives very long, may do that.

Anyway, the generated code makes a lot of sense to me. I wish I could try it out right now, but I can't.

**Comment by mulkieran** [comment]
Ok, thanks! Taking another look.

**Comment by mulkieran** [comment]
The first thing I notice is that no code is generated for properties of the interface. I assume that properties would be handled in the interface, in a similar way to methods?

**Comment by mulkieran** [comment]
I may be misunderstanding, but it looks like our implementation must provide a singe closure that, when applied to a msg info struct will return an object that implements the trait that you have generated and therefore implements all the expected methods? I believe that that is possible.

But, if the interface also implements properties, which are expected to be handled in the same way, doesn't the type of the closure have to be extended or modified somehow?

**Comment by diwic** [comment]
> The first thing I notice is that no code is generated for properties of the interface. I assume that properties would be handled in the interface, in a similar way to methods?

Yeah, I have just not done it yet. The easy way would be to just expose `get_xx` and `set_xx` methods in the trait, and potentially a `get_all` method that returns a struct with all properties in. Or maybe there is a more elegant way?

**Comment by diwic** [comment]
> our implementation must provide a singe closure that, when applied to a msg info struct will return an object that implements the trait that you have generated

Right. This will work fine if, say, you're implementing it on associated data on the object path, then your closure will just be `|minfo| minfo.path.get_data()`, but it becomes problematic if you want to do something else, like check the sender of a message or such. Here's where I feel I don't have the best design yet.

**Comment by diwic** [comment]
Added property support today. Not more than compile tested though. And I have a plan for signals but that'll be the topic for another day.

**Comment by diwic** [comment]
Signals added now :-)

**Comment by diwic** [comment]
Okay, I'm going to close this oldie as I think it's implemented now. When using the code generator, indeed the values sent by a service is type checked. You can run `cargo install dbus-codegen` to try the code generator.

**Comment by mulkieran** [comment]
Thanks!
