### ISSUE TITLE
Problems installing dbus-rs via cargo on Travis-CI

### ISSUE THREAD

**Issue by mulkieran** [diwic/dbus-rs#58]
Hi!

Here's a link to my failure: https://travis-ci.org/stratis-storage/stratisd/builds/174912560. Let me know if you aren't able to view it.

The failure is here:

```
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `dbus v0.4.1`
process didn't exit successfully: `/home/travis/build/stratis-storage/stratisd/target/debug/build/dbus-5e9bab8f37d6caf2/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1\"` did not exit successfully: exit code: 1\n--- stdout\nPackage dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'dbus-1\' found\n"', ../src/libcore/result.rs:79
```

The problem is, possibly, a question around Ubuntu which doesn't seem to actually have a package called dbus-1. See: http://packages.ubuntu.com/search?keywords=dbus. Have you heard about install issues on Ubuntu before or could you offer any suggestions?

Thanks and let me know if I can give you more information.

**Comment by diwic** [comment]
The error message says it's missing the file `dbus-1.pc`. So just [search for this file](http://packages.ubuntu.com/search?searchon=contents&keywords=dbus-1.pc&mode=exactfilename&suite=xenial&arch=any). 

I e, the package you need to install is `libdbus-1-dev`. At least on Ubuntu 16.04. I'll leave this issue open as the Readme should mention this.

**Comment by mulkieran** [comment]
Thanks, I've definitely made progress, but still experiencing problems:
https://travis-ci.org/stratis-storage/stratisd/builds/175734869. Again, if this rings a bell, could you let me know?

**Comment by diwic** [comment]
It does ring a bell: https://github.com/diwic/dbus-rs/issues/44

Apparently you're running this on Ubuntu 12.04 - which ships with 1.4 of DBus and the version supported is 1.6 or higher. Since 12.04 should EOL on April 2017, is there any reason you use such an old version?

**Comment by mulkieran** [comment]
Thanks! It's the default Travis version...maybe the highest they are using. I will try to find out more about that from them.

**Comment by mulkieran** [comment]
Thanks again. It turns out that it is possible to specify the Trusty Tapir distribution, though Precise Pangolin remains the default. And with that, it works!
