### ISSUE TITLE
Convert Hashmap<String, u64> to MessageItem

### ISSUE THREAD

**Issue by tekjar** [diwic/dbus-rs#63]
Hi. I've a message of type

```
published_count: HashMap<String, u64>,
```

I want to broadcast a signal with above message. How do I do that?

I'm trying to do something like this.

```
let m3 = dbus::Message::new_signal("/com/tekjar/Test",  "com.tekjar.Test",  "TotalPublishCount").unwrap();
let m3 = m3.append(total_published_count.into());
connection.send(m3).unwrap();
```

**Comment by diwic** [comment]
You probably want to send this argument as a dict? Something like this:

    let d = dbus::arg::Dict::new(total_published_count.iter());
    let m3 = m3.append1(d);

**Comment by tekjar** [comment]
Oh Thanks. Can I add a dict signal example to `examples`? Also Is there a way to create a tree using XMLs and then register it ? Code might look cleaner that way.

**Comment by diwic** [comment]
> Also Is there a way to create a tree using XMLs and then register it ? Code might look cleaner that way.

Btw, if you have a good example of how you wish your code to look like? I could use some inspiration.

**Comment by tekjar** [comment]
@diwic Oh this is cool. Thanks. 

> how you wish your code to look like? I could use some inspiration

I remember seeing something like this in go dbus. I'll try to find an example

**Comment by tekjar** [comment]
go dbus is doing this

https://github.com/godbus/dbus/blob/master/_examples/server.go#L11-L16

**Comment by diwic** [comment]
Ok, thanks for the example. Always good to know how other languages do it.

Btw, there is the [dbus-macros](https://github.com/antoyo/dbus-macros-rs/blob/master/examples/server.rs) crate, which is written by someone else, but anyhow an inspiration. Maybe it's helpful to you?
