### ISSUE TITLE
Is there / will be any support of dbus signal?

### ISSUE THREAD

**Issue by Nimamoh** [diwic/dbus-rs#65]
Hello,

This is more a question than an issue but I wondered if there was / will be any way to work with dbus signal in dbus-rs?

**Comment by diwic** [comment]
Yes, you can both send, receive and declare dbus signals. 

 [Signal receive example](https://github.com/diwic/dbus-rs/blob/master/examples/unity_focused_window.rs) 

Signal send: `connection.send(Message::signal() /* append arguments */)`

Signal declare (for introspection of a D-Bus service): [here](https://github.com/diwic/dbus-rs/blob/master/examples/adv_server.rs#L57) and [here](https://github.com/diwic/dbus-rs/blob/master/examples/adv_server.rs#L122)

**Comment by Nimamoh** [comment]
Oh ok, thank you for answering me ;)
