### ISSUE TITLE
Adding authentication to interfaces/methods

### ISSUE THREAD

**Issue by Timidger** [diwic/dbus-rs#68]
Hey there, sorry if this is a dumb question, but the docs for D-Bus are very technical and there doesn't seem to be much else out there on the web.

If I want to only allow certain clients to use an interface/method, how would I go about doing that through this crate? I saw [this question on stackexchange](http://unix.stackexchange.com/questions/194308/d-bus-authentication-and-authorization) that mentioned a `~/.dbus-keyrings` folder, but wasn't sure how that relates to having different interfaces/methods exposed to clients.

I could do something application side (e.g with tokens/a listing of whitelisted clients), but I wanted to see if there was an easier and more idiomatic way before going down that route.

**Comment by diwic** [comment]
I would first check if [polkit](http://smcv.pseudorandom.co.uk/2015/why_polkit/) can serve your purpose. That's what's usually used to say that some users can do things and others can't.
Second, if you're sure AppArmor installed on the target system(s), then that can be used, too. (Or SELinux? Haven't used that very much, but can probably do that too.)

That way you can filter the calls in the dbus daemon itself, before they even reach your process.
