### ISSUE TITLE
New to Rust, how to retrieve Props content data?

### ISSUE THREAD

**Issue by apiraino** [diwic/dbus-rs#77]
Hi, I'm using your library to cut my teeth with Rust.

Namely I'm trying to retrieve metadata of the current song played by VLC:
```
let c = Connection::get_private(BusType::Session).unwrap();                                                   
let p = Props::new(&c, "org.mpris.MediaPlayer2.vlc",                                                          
                       "/org/mpris/MediaPlayer2",                                                             
                       "org.mpris.MediaPlayer2.Player",                                                       
                       10000);                                                                                
let res : Result<MessageItem, _> = p.get("Metadata");
match res {                                                                                                   
    dbus::arg::Array(res) => Ok(res),
    // ....
};                                                                                                            
```
However I can't use the `dbus::arg::XXX` methods as suggested in #39 to retrieve the item(s) from the `Props`, I have a casting error like `mismatched types (expected enum 'std::result::Result', found struct 'dbus::arg::Array')`. Dumping directly with a `println!` shows the correct content:
```
Ok(Array([DictEntry(Str("mpris:trackid"), Variant(ObjectPath(Path("/org/videolan/vlc/playlist/15")))), DictEntry(Str("xesam:url"), ....)
```
How do I iterate the `std::result::Result` to a `dbus::arg::Array` and friends (`Variant`, `Dict`, etc.)?

Thank you so much for a hint!

**Comment by diwic** [comment]
Hi!

So, the properties stuff is a bit in flux between the old msgitem stuff and the newer arg stuff. I've just added a new example [here](https://github.com/diwic/dbus-rs/blob/master/examples/properties.rs) that uses arg instead of msgitem that should help you get going.

**Comment by diwic** [comment]
I've also been experimenting with code generation lately, but that stuff is still in alpha.

    cd codegen/dbus-codegen/
    cargo run -- -m None -d org.mpris.MediaPlayer2.rhythmbox -p "/org/mpris/MediaPlayer2" > /tmp/mediaplayer2.rs

Here's the result: [mediaplayer2.rs.zip](https://github.com/diwic/dbus-rs/files/823560/mediaplayer2.rs.zip)

With it should be able to do things like:

    let c = Connection::get_private(BusType::Session).unwrap();
    let p = c.with_path("org.mpris.MediaPlayer2.rhythmbox", "/org/mpris/MediaPlayer2", 5000);
    use mediaplayer2::OrgMprisMediaPlayer2Player;
    let metadata = p.get_metadata().unwrap();
    
...and get the metadata conviently collected into a hashmap for you.

**Comment by apiraino** [comment]
Thanks, those samples are working just fine.
So, since I need just a basic DBUS interaction (show metadata) I think the module `stdinf` is all I need.

Volume control can be done using any ALSA Rust crate; like yours for example ;-)

thanks
