### ISSUE TITLE
warning: redundant linker flag specified for library `dbus-1`

### ISSUE THREAD

**Issue by SimonSapin** [diwic/dbus-rs#79]
Compiling this crate with a recent Nightly Rust produces the warning in the title. I haven’t looked into it further.

**Comment by SimonSapin** [comment]
Hi. It looks like a292ac06a6030968a82ddfda5c10cc8fecf22151 is not on crates.io yet. Could you publish a new version? Thanks!

**Comment by diwic** [comment]
Hmm, yes, I really should. I got stuck halfway into doing some async helpers and never finished it off properly; just need to figure out whether I should release with or without that...

**Comment by SimonSapin** [comment]
You can do both! :)

**Comment by diwic** [comment]
0.5.3 is now released! The async helpers are far from finished but at least they work for one scenario (method calls).
