### ISSUE TITLE
Help with returning tuple of values

### ISSUE THREAD

**Issue by Timidger** [diwic/dbus-rs#80]
I'm trying to have a d-bus method return a tuple of two values (specifically a width and height) and I for some reason can't get the signature right.

Here's a snippet of the test code I have:

```
            .add_m(
                f.method("Resolution", (), |m| {
                    Ok(vec![m.msg.method_return()
                            .append2(1u32, 1u32)
                    ])
                }).outarg::<(u32, u32), _>("success")
```

But when trying to test it with a Python repl + pydbus I get the error:

```
Method 'Resolution' returned type '(uu)', but expected '((uu))' (13)
```

**Comment by diwic** [comment]
Either you return two output arguments, and then your code would look like this:

            .add_m(
                f.method("Resolution", (), |m| {
                    Ok(vec![m.msg.method_return()
                            .append2(1u32, 1u32)
                    ])
                }).outarg::<u32,  _>("width").outarg::<u32,  _>("height")

Or, you want to return one output argument, which is a struct of two values, and then the code should look like this:

            .add_m(
                f.method("Resolution", (), |m| {
                    Ok(vec![m.msg.method_return()
                            .append1((1u32, 1u32)) // Append one argument only, but that argument is a tuple
                    ])
                }).outarg::<(u32, u32), _>("success")

**Comment by Timidger** [comment]
Ah, that looks obvious now that I see it. Thanks!
