### ISSUE TITLE
Not easy to decipher how to handle arrays

### ISSUE THREAD

**Issue by zeenix** [diwic/dbus-rs#82]
This is more a documentation issue I think. If you want to pass arrays on D-Bus, the relevant API you find is:

https://docs.rs/dbus/0.5.2/dbus/arg/struct.Array.html

which has a few issues:

* It's quite a complicated type (or at least seems to be)
* docs don't mention that you can just use the Vec type
* examples/client.rs uses Array as is, rather than Vec so it becomes even less obvious that you can use Vec.
* Array docs page don't specify any conversion trait implementations for Vec either.

**Comment by diwic** [comment]
I've added an argument guide, see here: https://github.com/diwic/dbus-rs/blob/master/examples/argument_guide.md 

Does it look useful to you? Mind proofreading? From where should we link it so that it is discoverable?

**Comment by zeenix** [comment]
Looks good to me. I see you included the type I had problem with, Vec<Vec<u8>> as example. :)

I think it's likely good to have the relevant bits in the docs on argument types, e.g https://docs.rs/dbus/0.5.2/dbus/arg/struct.Array.html . And maybe good idea to change the examples/client.rs to use Vec instead of Array as it does currently?

**Comment by diwic** [comment]
Well, `Array` is the perfect match for examples/client.rs. And you can use arrays with vec's too, like this:

        let m = m.append1(Array::new(&vec![129u8, 5, 254]));

But I've added advertisements/links from both README.md, dbus::arg module docs and Array, Dict and Variant now.

**Comment by diwic** [comment]
More examples wouldn't hurt, of course - feel free to submit a PR now that you know how it works. :-)

**Comment by zeenix** [comment]
Thanks so much! I'll look into it. :)

**Comment by zeenix** [comment]
About the Array example, I'm not sure why this type needs to be exposed to use in the example. It confused me so I'd think it'll confuse others too.

**Comment by diwic** [comment]
`Array` is the most idiomatic way in that particular example. Not sure I want to remove it :-)
