### ISSUE TITLE
How do I get the PID of a client?

### ISSUE THREAD

**Issue by Timidger** [diwic/dbus-rs#83]
I see that `GetConnectionUnixProcessID` is in the [generate script](https://github.com/diwic/dbus-rs/blob/42f18356444aef5a8093fb4cc029b0f053042f12/codegen/dbus-codegen/src/generate.rs#L555), but I couldn't find any way in the docs for me to get this information from a connection client to my server. Is that operation exposed?

**Comment by diwic** [comment]
The code you found is just input to a test case. If you like to generate client-side code yourself, checkout git master, go to the codegen/dbus-codegen directory and run `cargo run -- -d org.freedesktop.DBus -m None > dbusintf.rs`.

**Comment by Timidger** [comment]
Ok thanks for your help, I think I understand what I need to do.
