### ISSUE TITLE
Work with gtk gui application and provide DBus service.

### ISSUE THREAD

**Issue by sbwtw** [diwic/dbus-rs#84]
I have a gui application and is writting by gtk-rs.
And I want to provide a DBus service to let other APP know some infomation about my mainwindow, like visible state, position, etc.

but I have some problems: gtk application is running in gtk's main thread. and I dont know how to access it in dbus thread.

Can you please help me to write an example code.

**Comment by diwic** [comment]
Writing a complete example is too time consuming for me, sorry.

Also, I have used gtk/glib, but not gtk-rs. If you just want to write something quick-and-dirty, I'd keep dbus and gtk in the same thread, and every x milliseconds I would just process incoming messages by calling `connection.iter(1)` and handle messages until you get an `ConnectionItem::Nothing`.

If you want to keep the two-thread approach, I would probably use a [channel](https://doc.rust-lang.org/std/sync/mpsc/) from the gtk thread to the dbus thread. For the other direction, ask the gtk-rs people.

(Btw - the best thing would probably be if glib-rs started supporting unix fds, but that does not seem to be supported yet.)

**Comment by sbwtw** [comment]
ok. I'll try your suggestion.

**Comment by pavelmachek** [comment]
sbwtw: if you have some working code that is public, that would be quite welcome.

**Comment by pavelmachek** [comment]
This might be related: https://github.com/antoyo/gdbus-rs
