### ISSUE TITLE
Rename the Cargo package to simply "dbus"

### ISSUE THREAD

**Issue by lfairy** [diwic/dbus-rs#9]
Two reasons:

1. The `-rs` suffix is redundant, since the fact that it's on crates.io already tells us it's Rust.

2. The extra hyphen means I have to rename the crate every time I use it: `extern crate "dbus-rs" as dbus;`.

`dbus` is still free on crates.io, so now's a great opportunity to grab the name.

**Comment by diwic** [comment]
Hmm, would it not be confusing if there was *both* a dbus-rs and a dbus crate on crates.io ?

**Comment by lfairy** [comment]
You can upload a final version of `dbus-rs` with a deprecation message as its description. Since the description is shown in search results, anyone who types `dbus` into the search bar will (hopefully) know which one to use.

Funnily enough, while researching this issue I found `phf_macros`, which was recently renamed from `phf_mac` without any announcement whatsoever. I guess if a core dev can rename their packages with impunity we can too :wink:

**Comment by diwic** [comment]
Your wish has been granted! :-)

**Comment by lfairy** [comment]
Thank you! :heart:
