### ISSUE TITLE
AMethodCall future never finishes

### ISSUE THREAD

**Issue by manuels** [diwic/dbus-rs#94]
I am calling a DBus method but somehow the Future's `then` function is never called.
This is what my code looks like:

    let dht_publish = move |(stream, sink, c)| {
        remote.spawn(move |handle | {
            let (key, value): (Vec<u8>, Vec<u8>) = dht_encode(c);

            let conn = Rc::new(Connection::get_private(BusType::Session).unwrap());
            let aconn = AConnection::new(conn, handle.clone()).unwrap();

            let m = Message::new_method_call("org.manuel.BulletinBoard", "/", "org.manuel.BulletinBoard", "Put").unwrap();
            let m = m.append3("wg-p2p", key, value);
            let future = aconn.method_call(m).unwrap();

            debug!("Method called.");
            future.then(|_| {
                debug!("Method returned.");
                ok(())
            })
        });
        ok(())
    };

In the console 'Message called.' appears, but 'Method returned.' never appears.
Here are the last lines of the output with `RUST_LOG=debug`:

    [...]
    DEBUG:tokio_core::reactor: consuming notification queue
    DEBUG:tokio_core::reactor: adding a new I/O source
    DEBUG:wireguard_p2p: Method called.
    DEBUG:tokio_core::reactor: loop process - 2 events, Duration { secs: 0, nanos: 4138144 }
    DEBUG:tokio_core::reactor: consuming notification queue
    DEBUG:tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 44084 }
    DEBUG:tokio_core::reactor: loop time - Instant { tv_sec: 208187, tv_nsec: 134969097 }
    DEBUG:tokio_core::reactor: loop process - 4 events, Duration { secs: 0, nanos: 301445 }
    DEBUG:tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 33763 }
    DEBUG:tokio_core::reactor: loop time - Instant { tv_sec: 208187, tv_nsec: 135338394 }
    DEBUG:tokio_core::reactor: consuming notification queue
    DEBUG:tokio_core::reactor: dropping I/O source: 2
    DEBUG:tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 126770 }
    DEBUG:tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 21864 }
    DEBUG:tokio_core::reactor: loop time - Instant { tv_sec: 208187, tv_nsec: 135507518 }
    DEBUG:tokio_core::reactor: loop process - 0 events, Duration { secs: 0, nanos: 35763 }

Any idea what could be going wrong here?

PS: The program does not return to the shell. It stays in `Core::run(some_other_future)` (which is fine).
PPS: The org.manuel.BulletinBoard.Put method should return within ~20 sec.

**Comment by manuels** [comment]
Replacing the method call with

    let m = Message::new_method_call("org.freedesktop.DBus", "/", "org.freedesktop.DBus", "ListNames").unwrap();

results in the same problem.

**Comment by diwic** [comment]
Hmm, it looks like `aconn` is dropped too soon. If the AConnection is dropped, then the method call dispatcher is dropped too. It needs to stay alive until the method is returned. Does that help?

**Comment by manuels** [comment]
Thanks, it does: adding `drop()` solves this issue.

        future.then(|_| {
            debug!("Method returned.");
            drop(aconn);
            ok(())
        })

Should I close this issue or do you want to keep it open until this issue is fixed?

**Comment by diwic** [comment]
It's currently intended to work this way, so let's close this issue, and if you have a suggestion of a redesign that would make dbus-tokio easier to use, feel free to open a new one (or reopen this one).
