### ISSUE TITLE
How to use dbus-codegen to generate Rust code?

### ISSUE THREAD

**Issue by fschutt** [diwic/dbus-rs#96]
I have an XML declaration of my client-side dbus interface. How do I tell dbus-codegen to generate the rust code for this? XML in question: https://gist.github.com/fschutt/938aeb6eefc28ff45c0a24723f01cc5b

How do I use rust-codegen? The README says that it generates code, but how do I tell it where the XML file is? If I just start the main application, it just waits endlessly.

**Comment by diwic** [comment]
Just pipe it into the application, i e `cargo run < dbus.xml`. If you add options as well, do it like this: `cargo run -- -m None < dbus.xml`.

**Comment by fschutt** [comment]
Made a PR to add this to the README: https://github.com/diwic/dbus-rs/pull/97
